namespace ControlPenales
{
    public class cHistoriaClinicaDentalReporte
    {
        public string NoExpediente { get; set; }
        public string NombrePaciente { get; set; }
        public string Edad { get; set; }
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public string Complicaciones { get; set; }
        public string Hemorragia { get; set; }
        public string ReaccionNegativa { get; set; }
        public string TomandoMedicamento { get; set; }
        public string CualMedicamentoToma { get; set; }
        public string AlergicoMedicamento { get; set; }
        public string CualMedicamentoAlergico { get; set; }
        public string EstaEmbarazada { get; set; }
        public string AmenazaAborto { get; set; }
        public string Lactando { get; set; }
        public string Alcohlismo { get; set; }
        public string Tabaquismo { get; set; }
        public string Toxicomanias { get; set; }
        public string Labios { get; set; }
        public string Lengua { get; set; }
        public string MucosaNasal { get; set; }
        public string Amigdalas { get; set; }
        public string PisoBoca { get; set; }
        public string PaladarDuro { get; set; }
        public string PaladarBlanco { get; set; }
        public string Carrillos { get; set; }
        public string Frenillos { get; set; }
        public string OtrosExploracionBucod { get; set; }
        public string Caries { get; set; }
        public string Fluorosis { get; set; }
        public string AnomaliasForma { get; set; }
        public string AnomaliasTamanio { get; set; }
        public string Hipoplasias { get; set; }
        public string OtrosDientes { get; set; }
        public string Dolor { get; set; }
        public string DolorEspecifique { get; set; }
        public string RigidezMusculsMand { get; set; }
        public string EspecifiqueRigidezMuscMand { get; set; }
        public string Chasquidos { get; set; }
        public string EspecifiqueChasquidos { get; set; }
        public string CansancioMusculosCaraCuello { get; set; }
        public string EspecifiqueCansancioMusculosCaraCuello { get; set; }
        public string Color { get; set; }
        public string Forma { get; set; }
        public string Textura { get; set; }
        public string Pulso { get; set; }
        public string TensionArt { get; set; }
        public string Temperatura { get; set; }
        public string FrecuenciaCard { get; set; }
        public string FrecuenciaResp { get; set; }
        public string Glicemia { get; set; }
        public string Peso { get; set; }
        public string Estatura { get; set; }
        public string NombreEnfermero { get; set; }
        public string Odontograma { get; set; }
        public string Bruxismo { get; set; }
        public string EspecifiqueBruxismo { get; set; }
        public string Generico { get; set; }
        public string Generico1 { get; set; }
        public string Generico2 { get; set; }
        public string Generico3 { get; set; }
        public string Generico4 { get; set; }
        public string Generico5 { get; set; }
        public string Generico6 { get; set; }
        public string Generico7 { get; set; }
        public string Generico8 { get; set; }
        public string Generico9 { get; set; }
        public string Generico10 { get; set; }
        public string Generico11 { get; set; }
        public string Generico12 { get; set; }
        public string Generico13 { get; set; }
        public string Generico14 { get; set; }
        public string Generico15 { get; set; }
        public string Generico16 { get; set; }
        public string Generico17 { get; set; }
        public byte[] Generico18 { get; set; }
        public byte[] ImagenPatologisoDentales { get; set; }

        public byte[] Im1 { get; set; }
        public byte[] Im2 { get; set; }
        public byte[] Im3 { get; set; }
        public byte[] Im4 { get; set; }
        public byte[] Im5 { get; set; }
        public byte[] Im6 { get; set; }
        public byte[] Im7 { get; set; }
        public byte[] Im8 { get; set; }
        public byte[] Im9 { get; set; }
        public byte[] Im10 { get; set; }
        public byte[] Im11 { get; set; }
        public byte[] Im12 { get; set; }
        public byte[] Im13 { get; set; }
        public byte[] Im14 { get; set; }
        public byte[] Im15 { get; set; }
        public byte[] Im16 { get; set; }
        public byte[] Im17 { get; set; }
        public byte[] Im18 { get; set; }
        public byte[] Im19 { get; set; }
        public byte[] Im20 { get; set; }
        public byte[] Im21 { get; set; }
        public byte[] Im22 { get; set; }
        public byte[] Im23 { get; set; }
        public byte[] Im24 { get; set; }
        public byte[] Im25 { get; set; }
        public byte[] Im26 { get; set; }
        public byte[] Im27 { get; set; }
        public byte[] Im28 { get; set; }
        public byte[] Im29 { get; set; }
        public byte[] Im30 { get; set; }
        public byte[] Im31 { get; set; }
        public byte[] Im32 { get; set; }
        public byte[] Im33 { get; set; }
        public byte[] Im34 { get; set; }
        public byte[] Im35 { get; set; }
        public byte[] Im36 { get; set; }
        public byte[] Im37 { get; set; }
        public byte[] Im38 { get; set; }
        public byte[] Im39 { get; set; }
        public byte[] Im40 { get; set; }
    }
}