namespace ControlPenales
{
    public enum enumMensajeTipo
    {
        DECOMISO = 11,
        CAMBIO_ESTANCIA = 83,
        CALENDARIZACION_TRASLADO=84,
        CANCELACION_TRASLADO=85,
        CALENDARIZACION_EXCARCELACION=86,
        CANCELACION_EXCARCELACION=87,
        AVISO_EXCARCELACION_AREA_MEDICA=88,
        MODIFICACION_EXCARCELACION=89,
        AVISO_CANCELACION_EXCARCELACION_AREA_MEDICA=90,  //MENSAJE PARA AVISAR QUE YA NO ES NECESARIO EL CERTIFICADO MEDICO
        AVISO_AUTORIZACION_DIRECCION_EXCARCELACION=91, //MENSAJE DEL O1 AL AUTORIZAR UNA EXCARCELACION JURIDICA
        PROGRAMACION_ESTUDIOS_PERSONALIDAD = 92,
        INCIDENCIA_REPROGRAMACIÓN_ATENCIÓN_MÉDICA = 94,
        DEFINIDA_FECHA_INICIO_PERSONALIDAD = 97,
        CANCELACION_ESTUDIO_PERSONALIDAD = 98,
        SOLICITUD_INTERCONSULTA_INTERNA=99,
        SOLICITUD_INTERCONSULTA_EXTERNA = 100,
        SANCION = 101,
        LIBERACION_DE_IMPUTADO=102,
        CANCELACION_EXCARCELACION_MEDICA=103, //AVISO DE CANCELACION DE UNA EXCARCELACION MEDICA
        NO_CAUSAS_PENALES_ACTIVAS=104,
        REAGENDA_SOLICITUD_INTERCONSULTA_EXTERNA=105,
        CANCELACION_SOLICITUD_INTERCONSULTA_INTERNA= 106,
        CANCELACION_SOLICITUD_INTERCONSULTA_EXTERNA = 107,
        MODIFICACION_EXCARCELACION_MEDICA = 108,
        AVISO_AUTORIZACION_DIRECCION_EXCARCELACION_MEDICA = 109, //MENSAJE DEL O1 AL AUTORIZAR UNA EXCARCELACION MEDICA
        AVISO_NOTIFICACION_AREA_MEDICA = 110,
        AVISO_RESPUESTA_TRABAJO_SOCIAL = 111,
        SOLICITUD_CANALIZACION=112,
        MODIFICACION_CANALIZACION=113,
        CANCELACION_CANALIZACION=114,
        TARJETA_INFORMATIVA_DECESO=115,
        TARJETA_INFORMATIVA_DECESO_ESTATAL=116,
        DETECCION_AREA_MEDICA_GRUPO_VULNERABLE=117
    }
}
