using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ControlPenales
{
    public enum enumDepartamentos
    {
        COORDINACION_TECNICA=1,
        JURIDICO=2,
        TRABAJO_SOCIAL=3,
        COMANDANCIA=4,
        DIRECCION_MEDICA=5,
        PSICOLOGICO=6,
        PSIQUIATRICO=7,
        CONSULTORIO_DENTAL_MATUTINO=8,
        TALLERES=9,
        DIRECCION=10,
        INFORMATICA=11,
        MEDICO_DE_GUARDIA=12,
        AREA_EDUCATIVA=13,
        CRIMINOLOGIA=14,
        SERVICIOS_GENERALES=15,
        IDENTIFICACION_CONTROL_DE_INGRESOS=16,
        COC_PLANTA_BAJA_MEDICO=17,
        CONSULTORIO_DENTAL_VESPERTINO=18,
        SUB_DIRECTORA_GENERAL=19,
        DIRECTORA_DE_EJECUCION_DE_SENTENCIAS=20,
        DIRECTORA_DE_PROGRAMAS=21,
        SUBSECRETARIO_DEL_SISTEMA_ESTATAL_PENITENCIARIO=22,
        SUBDIRECTOR_DEL_CERESO=23,
        DIRECTOR_GENERAL_DE_CENTROS=25,
        DIRECCION_GENERAL_DE_CENTROS=26,
        COORDINACION_ESTATAL_DE_PROG_DE_READAP_SOCIAL=27,
        COORDINACION_ESTATAL_DE_CRIMINOLOGIA=28,
        SECRETARIO_DE_SEGURIDAD_PUBLICA=29,
        COORDINADOR_JURIDICO_DE_LA_SUBSECRETARIA=30
    }
}
