//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_BiometricoService.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIOMETRICO_TIPO
    {
        public BIOMETRICO_TIPO()
        {
            this.PERSONA_BIOMETRICO = new HashSet<PERSONA_BIOMETRICO>();
            this.IMPUTADO_BIOMETRICO = new HashSet<IMPUTADO_BIOMETRICO>();
        }
    
        public short ID_TIPO_BIOMETRICO { get; set; }
        public string TIPO_BIOMETRICO { get; set; }
    
        public virtual ICollection<PERSONA_BIOMETRICO> PERSONA_BIOMETRICO { get; set; }
        public virtual ICollection<IMPUTADO_BIOMETRICO> IMPUTADO_BIOMETRICO { get; set; }
    }
}
