using SSP.Modelo;
using SSP.Servidor;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SSP.Controlador.Catalogo.Justicia
{
    public class cNotaMedicaDieta : EntityManagerServer<NOTA_MEDICA_DIETA>
    {
        /// <summary>
        /// Obtiene el historial de dietas de una hospitalizacion
        /// </summary>
        /// <param name="id_hospitalizacion">ID de la llave de la hospitalizacion</param>
        /// <param name="id_centro_ubi">ID_CENTRO_UBI de la llave de la hospitalizacion</param>
        /// <returns>IQueryable &lt;NOTA_MEDICA_DIETA&gt;</returns>
        public IQueryable<NOTA_MEDICA_DIETA> Obtener_Historial_Hospitalizacion(decimal id_hospitalizacion, short id_centro_ubi)
        {
            try
            {
                if (!Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi)))
                    if (!Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi))
                        if (!Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))))
                            if (!Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))))
                                //NO HAY NINGUNA DIETA
                                return null;
                            else
                                //DIETAS DE ESPECIALIDAD DE NOTA DE EVOLUCION
                                return Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1)));
                        else
                            if (!Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))))
                                //DIETAS DE ESPECIALIDAD DE NOTA DE INGRESO
                                return Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi))));
                            else
                                //DIETAS DE ESPECIALIDAD DE NOTA DE EVOLUCION Y DE ESPECIALIDAD DE NOTA DE INGRESO
                                return Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi))))
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))));
                    else
                        if (!Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))))
                            if (!Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))))
                                //DIETAS DE NOTA DE EVOLUCION
                                return Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi);
                            else
                                //DIETAS DE NOTA DE EVOLUCION,RECETA MEDICA DE ESPECIALIDAD DE NOTA DE EVOLUCION
                                return Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi)
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))));
                        else
                            if (!Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))))
                                //DIETAS DE NOTA DE EVOLUCION,RECETA MEDICA DE ESPECIALIDAD DE NOTA DE INGRESO
                                return Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi)
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))));
                            else
                                //DIETAS DE NOTA DE EVOLUCION,RECETA MEDICA DE ESPECIALIDAD DE NOTA DE EVOLUCION Y DE ESPECIALIDAD DE NOTA DE INGRESO
                                return Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi)
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))))
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))));
                else
                    if (!Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi))
                        if (!Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))))
                            if (!Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))))
                                //DIETA DE NOTA DE INGRESO
                                return Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi));
                            else
                                //DIETA DE NOTA DE INGRESO, DIETAS DE ESPECIALIDAD DE NOTA DE EVOLUCION
                                return Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))));
                        else
                            if (!Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))))
                                //DIETA DE NOTA DE INGRESO, DIETAS DE ESPECIALIDAD DE NOTA DE INGRESO
                                return Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))));
                            else
                                //DIETA DE NOTA DE INGRESO, DIETAS DE ESPECIALIDAD DE NOTA DE EVOLUCION Y DE ESPECIALIDAD DE NOTA DE INGRESO
                                return Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))))
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))));
                    else
                        if (!Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))))
                            if (!Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))))
                                //DIETA DE NOTA DE INGRESO, DIETAS DE NOTA DE EVOLUCION
                                return Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi));
                            else
                                //DIETA DE NOTA DE INGRESO, DIETAS DE NOTA DE EVOLUCION,RECETA MEDICA DE ESPECIALIDAD DE NOTA DE EVOLUCION
                                return Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))));
                        else
                            if (!Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))))
                                //DIETA DE NOTA DE INGRESO, DIETAS DE NOTA DE EVOLUCION,RECETA MEDICA DE ESPECIALIDAD DE NOTA DE INGRESO
                                return Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))));
                            else
                                //DIETA DE NOTA DE INGRESO, DIETAS DE NOTA DE EVOLUCION,RECETA MEDICA DE ESPECIALIDAD DE NOTA DE EVOLUCION Y DE ESPECIALIDAD DE NOTA DE INGRESO
                                return Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))))
                                    .Union(Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))));

                //queries
                //Dietas recetadas de la nota de ingreso
                //Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                //Dietas recetadas de las nota de evolucion
                //Context.NOTA_MEDICA_DIETA.Any(w => w.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi)
                //Dietas recetadas de especialidades que originan de la nota media de ingreso
                //Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi))))
                //Dietas recetadas de especialidades que originan de las notas medicas de evolucion
                //Context.NOTA_MEDICA_DIETA.Where(w => w.NOTA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2=>a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))); 
            }
            catch (Exception ex)
            {
                throw new ApplicationException(ex.Message + " " + (ex.InnerException != null ? ex.InnerException.InnerException.Message : ""));
            }
        }
    }
}
