using SSP.Modelo;
using SSP.Servidor;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SSP.Controlador.Catalogo.Justicia
{
    public class cRecetaMedicaDetalle:EntityManagerServer<RECETA_MEDICA_DETALLE>
    {
        /// <summary>
        /// Obtiene el historia de recetas de una hospitalizacion
        /// </summary>
        /// <param name="id_hospitalizacion">ID de la llave de la hospitalizacion</param>
        /// <param name="id_centro_ubi">ID_CENTRO_UBI de la llave de la hospitalizacion</param>
        /// <returns>IQueryable &lt;RECETA_MEDICA_DETALLE&gt;</returns>
        public IQueryable<RECETA_MEDICA_DETALLE> Obtener_Historial_Hospitalizacion(decimal id_hospitalizacion, short id_centro_ubi)
        {
            try
            {
                if (!Context.RECETA_MEDICA_DETALLE.Any(w => w.RECETA_MEDICA.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi)))
                    if (!Context.RECETA_MEDICA_DETALLE.Any(w => w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi))
                        if (!Context.RECETA_MEDICA_DETALLE.Any(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))))
                            if (!Context.RECETA_MEDICA_DETALLE.Any(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))))
                                //NO HAY NINGUNA RECETA MEDICA
                                return null;
                            else
                                //RECETA MEDICA DE ESPECIALIDAD DE NOTA DE EVOLUCION
                                return Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1)));
                        else
                            if (!Context.RECETA_MEDICA_DETALLE.Any(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.ATENCION_CITA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a2.ID_CENTRO_UBI == id_centro_ubi))))
                                //RECETA MEDICA DE ESPECIALIDAD DE NOTA DE INGRESO
                                return Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi))));
                            else
                                //RECETA MEDICA DE ESPECIALIDAD DE NOTA DE EVOLUCION Y DE ESPECIALIDAD DE NOTA DE INGRESO
                                return Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi))))
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))));
                    else
                        if (!Context.RECETA_MEDICA_DETALLE.Any(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))))
                            if (!Context.RECETA_MEDICA_DETALLE.Any(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))))
                                //RECETA MEDICA DE NOTA DE EVOLUCION
                                return Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi);
                            else
                                //RECETA MEDICA DE NOTA DE EVOLUCION,RECETA MEDICA DE ESPECIALIDAD DE NOTA DE EVOLUCION
                                return Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi)
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))));
                        else
                            if (!Context.RECETA_MEDICA_DETALLE.Any(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.ATENCION_CITA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a2.ID_CENTRO_UBI == id_centro_ubi))))
                                //RECETA MEDICA DE NOTA DE EVOLUCION,RECETA MEDICA DE ESPECIALIDAD DE NOTA DE INGRESO
                                return Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi)
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))));
                            else
                                //RECETA MEDICA DE NOTA DE EVOLUCION,RECETA MEDICA DE ESPECIALIDAD DE NOTA DE EVOLUCION Y DE ESPECIALIDAD DE NOTA DE INGRESO
                                return Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi)
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))))
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))));
                else
                    if (!Context.RECETA_MEDICA_DETALLE.Any(w => w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi))
                        if (!Context.RECETA_MEDICA_DETALLE.Any(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))))
                            if (!Context.RECETA_MEDICA_DETALLE.Any(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))))
                                //RECETA MEDICA DE NOTA DE INGRESO
                                return Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi));
                            else
                                //RECETA MEDICA DE NOTA DE INGRESO,RECETA MEDICA DE ESPECIALIDAD DE NOTA DE EVOLUCION
                                return Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))));
                        else
                            if (!Context.RECETA_MEDICA_DETALLE.Any(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))))
                                //RECETA MEDICA DE NOTA DE INGRESO,RECETA MEDICA DE ESPECIALIDAD DE NOTA DE INGRESO
                                return Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))));
                            else
                                //RECETA MEDICA DE NOTA DE INGRESO,RECETA MEDICA DE ESPECIALIDAD DE NOTA DE EVOLUCION Y DE ESPECIALIDAD DE NOTA DE INGRESO
                                return Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))))
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))));
                    else
                        if (!Context.RECETA_MEDICA_DETALLE.Any(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))))
                            if (!Context.RECETA_MEDICA_DETALLE.Any(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))))
                                //RECETA MEDICA DE NOTA DE INGRESO,RECETA MEDICA DE NOTA DE EVOLUCION
                                return Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi));
                            else
                                return
                                    //RECETA MEDICA DE NOTA DE INGRESO,RECETA MEDICA DE NOTA DE EVOLUCION,RECETA MEDICA DE ESPECIALIDAD DE NOTA DE EVOLUCION
                                    Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))));
                        else
                            if (!Context.RECETA_MEDICA_DETALLE.Any(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))))
                                //RECETA MEDICA DE NOTA DE INGRESO,RECETA MEDICA DE NOTA DE EVOLUCION,RECETA MEDICA DE ESPECIALIDAD DE NOTA DE INGRESO
                                return Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))));
                            else
                                return
                                    //RECETA MEDICA DE NOTA DE INGRESO,RECETA MEDICA DE NOTA DE EVOLUCION,RECETA MEDICA DE ESPECIALIDAD DE NOTA DE EVOLUCION Y DE ESPECIALIDAD DE NOTA DE INGRESO 
                                    Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi))
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi)))))
                                    .Union(Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2 => a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))));
                //queries
                //Receta medica de la nota de ingreso
                //Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.HOSPITALIZACION.Any(a => a.ID_HOSPITA == id_hospitalizacion && a.ID_CENTRO_UBI == id_centro_ubi))
                //Recetas medicas de las nota de evolucion
                //Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && w.RECETA_MEDICA.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi)
                //Recetas medicas de especialidades que originan de la nota media de ingreso
                //Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a => a.ESPECIALISTA_CITA.Any(a2 => a2.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.HOSPITALIZACION.Any(a3 => a3.ID_HOSPITA == id_hospitalizacion && a3.ID_CENTRO_UBI == id_centro_ubi))))
                //Recetas medicas de especialidades que originan de las notas medicas de evolucion
                //Context.RECETA_MEDICA_DETALLE.Where(w => w.RECETA_MEDICA.ATENCION_MEDICA.ATENCION_CITA.Any(a2=>a2.ESPECIALISTA_CITA.Any(a => a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_HOSPITA == id_hospitalizacion && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.NOTA_MEDICA.ATENCION_MEDICA.ID_CENTRO_UBI == id_centro_ubi && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.CANALIZACION.ID_ESTATUS_CAN == "A" && a.SOL_INTERCONSULTA_INTERNA.INTERCONSULTA_SOLICITUD.ID_INTER == 1))); 
            }
            catch (Exception ex)
            {
                throw new ApplicationException(ex.Message + " " + (ex.InnerException != null ? ex.InnerException.InnerException.Message : ""));
            }
            
        }
    }
}
