//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESAL.BiometricoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="enumTipoBiometrico", Namespace="http://schemas.datacontract.org/2004/07/WCF_BiometricoService.Helpers")]
    public enum enumTipoBiometrico : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FOTOGRAFIA_SALIDA = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FOTO_FRENTE_REGISTRO = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FOTO_DER_REGISTRO = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FOTO_IZQ_REGISTRO = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FOTO_FRENTE_SEGUIMIENTO = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FOTO_DER_SEGUIMIENTO = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FOTO_IZQ_SEGUIMIENTO = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PULGAR_DERECHO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INDICE_DERECHO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MEDIO_DERECHO = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANULAR_DERECHO = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MENIQUE_DERECHO = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PULGAR_IZQUIERDO = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INDICE_IZQUIERDO = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MEDIO_IZQUIERDO = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANULAR_IZQUIERDO = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MENIQUE_IZQUIERDO = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUATRO_DEDOS_MANO_DERECHA = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUATRO_DEDOS_MANO_IZQUIERDA = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOS_PULGARES_AMBAS_MANOS = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REGISTRO_VOZ = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLANTILLA_FACIAL = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLANTILLA_ADN = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLANTILLA_IRIS_OJO_DERECHO = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLANTILLA_IRIS_OJO_IZQUIERDO = 17,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="enumTipoFormato", Namespace="http://schemas.datacontract.org/2004/07/WCF_BiometricoService.Helpers")]
    public enum enumTipoFormato : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FMTO_WSQ = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FMTO_BMP = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FMTO_MNT = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FMTO_VUR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FMTO_JPG = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FMTO_WAV = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FMTO_WMV = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FMTO_MP3 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FMTO_DP = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IMPUTADO_BIOMETRICO", Namespace="http://schemas.datacontract.org/2004/07/WCF_BiometricoService.Modelo")]
    [System.SerializableAttribute()]
    public partial class IMPUTADO_BIOMETRICO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BIOMETRICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GESAL.BiometricoServiceReference.BIOMETRICO_TIPO BIOMETRICO_TIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> CALIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_ANIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_CENTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_FORMATOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_IMPUTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_TIPO_BIOMETRICOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BIOMETRICO {
            get {
                return this.BIOMETRICOField;
            }
            set {
                if ((object.ReferenceEquals(this.BIOMETRICOField, value) != true)) {
                    this.BIOMETRICOField = value;
                    this.RaisePropertyChanged("BIOMETRICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GESAL.BiometricoServiceReference.BIOMETRICO_TIPO BIOMETRICO_TIPO {
            get {
                return this.BIOMETRICO_TIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.BIOMETRICO_TIPOField, value) != true)) {
                    this.BIOMETRICO_TIPOField = value;
                    this.RaisePropertyChanged("BIOMETRICO_TIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> CALIDAD {
            get {
                return this.CALIDADField;
            }
            set {
                if ((this.CALIDADField.Equals(value) != true)) {
                    this.CALIDADField = value;
                    this.RaisePropertyChanged("CALIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_ANIO {
            get {
                return this.ID_ANIOField;
            }
            set {
                if ((this.ID_ANIOField.Equals(value) != true)) {
                    this.ID_ANIOField = value;
                    this.RaisePropertyChanged("ID_ANIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_CENTRO {
            get {
                return this.ID_CENTROField;
            }
            set {
                if ((this.ID_CENTROField.Equals(value) != true)) {
                    this.ID_CENTROField = value;
                    this.RaisePropertyChanged("ID_CENTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_FORMATO {
            get {
                return this.ID_FORMATOField;
            }
            set {
                if ((this.ID_FORMATOField.Equals(value) != true)) {
                    this.ID_FORMATOField = value;
                    this.RaisePropertyChanged("ID_FORMATO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_IMPUTADO {
            get {
                return this.ID_IMPUTADOField;
            }
            set {
                if ((this.ID_IMPUTADOField.Equals(value) != true)) {
                    this.ID_IMPUTADOField = value;
                    this.RaisePropertyChanged("ID_IMPUTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_TIPO_BIOMETRICO {
            get {
                return this.ID_TIPO_BIOMETRICOField;
            }
            set {
                if ((this.ID_TIPO_BIOMETRICOField.Equals(value) != true)) {
                    this.ID_TIPO_BIOMETRICOField = value;
                    this.RaisePropertyChanged("ID_TIPO_BIOMETRICO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BIOMETRICO_TIPO", Namespace="http://schemas.datacontract.org/2004/07/WCF_BiometricoService.Modelo")]
    [System.SerializableAttribute()]
    public partial class BIOMETRICO_TIPO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_TIPO_BIOMETRICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO[] IMPUTADO_BIOMETRICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GESAL.BiometricoServiceReference.PERSONA_BIOMETRICO[] PERSONA_BIOMETRICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_BIOMETRICOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_TIPO_BIOMETRICO {
            get {
                return this.ID_TIPO_BIOMETRICOField;
            }
            set {
                if ((this.ID_TIPO_BIOMETRICOField.Equals(value) != true)) {
                    this.ID_TIPO_BIOMETRICOField = value;
                    this.RaisePropertyChanged("ID_TIPO_BIOMETRICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO[] IMPUTADO_BIOMETRICO {
            get {
                return this.IMPUTADO_BIOMETRICOField;
            }
            set {
                if ((object.ReferenceEquals(this.IMPUTADO_BIOMETRICOField, value) != true)) {
                    this.IMPUTADO_BIOMETRICOField = value;
                    this.RaisePropertyChanged("IMPUTADO_BIOMETRICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GESAL.BiometricoServiceReference.PERSONA_BIOMETRICO[] PERSONA_BIOMETRICO {
            get {
                return this.PERSONA_BIOMETRICOField;
            }
            set {
                if ((object.ReferenceEquals(this.PERSONA_BIOMETRICOField, value) != true)) {
                    this.PERSONA_BIOMETRICOField = value;
                    this.RaisePropertyChanged("PERSONA_BIOMETRICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_BIOMETRICO {
            get {
                return this.TIPO_BIOMETRICOField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_BIOMETRICOField, value) != true)) {
                    this.TIPO_BIOMETRICOField = value;
                    this.RaisePropertyChanged("TIPO_BIOMETRICO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PERSONA_BIOMETRICO", Namespace="http://schemas.datacontract.org/2004/07/WCF_BiometricoService.Modelo")]
    [System.SerializableAttribute()]
    public partial class PERSONA_BIOMETRICO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BIOMETRICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GESAL.BiometricoServiceReference.BIOMETRICO_TIPO BIOMETRICO_TIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_FORMATOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_PERSONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_TIPO_BIOMETRICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NORIGINALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GESAL.BiometricoServiceReference.PERSONA PERSONAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BIOMETRICO {
            get {
                return this.BIOMETRICOField;
            }
            set {
                if ((object.ReferenceEquals(this.BIOMETRICOField, value) != true)) {
                    this.BIOMETRICOField = value;
                    this.RaisePropertyChanged("BIOMETRICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GESAL.BiometricoServiceReference.BIOMETRICO_TIPO BIOMETRICO_TIPO {
            get {
                return this.BIOMETRICO_TIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.BIOMETRICO_TIPOField, value) != true)) {
                    this.BIOMETRICO_TIPOField = value;
                    this.RaisePropertyChanged("BIOMETRICO_TIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_FORMATO {
            get {
                return this.ID_FORMATOField;
            }
            set {
                if ((this.ID_FORMATOField.Equals(value) != true)) {
                    this.ID_FORMATOField = value;
                    this.RaisePropertyChanged("ID_FORMATO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PERSONA {
            get {
                return this.ID_PERSONAField;
            }
            set {
                if ((this.ID_PERSONAField.Equals(value) != true)) {
                    this.ID_PERSONAField = value;
                    this.RaisePropertyChanged("ID_PERSONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_TIPO_BIOMETRICO {
            get {
                return this.ID_TIPO_BIOMETRICOField;
            }
            set {
                if ((this.ID_TIPO_BIOMETRICOField.Equals(value) != true)) {
                    this.ID_TIPO_BIOMETRICOField = value;
                    this.RaisePropertyChanged("ID_TIPO_BIOMETRICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NORIGINAL {
            get {
                return this.NORIGINALField;
            }
            set {
                if ((this.NORIGINALField.Equals(value) != true)) {
                    this.NORIGINALField = value;
                    this.RaisePropertyChanged("NORIGINAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GESAL.BiometricoServiceReference.PERSONA PERSONA {
            get {
                return this.PERSONAField;
            }
            set {
                if ((object.ReferenceEquals(this.PERSONAField, value) != true)) {
                    this.PERSONAField = value;
                    this.RaisePropertyChanged("PERSONA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PERSONA", Namespace="http://schemas.datacontract.org/2004/07/WCF_BiometricoService.Modelo")]
    [System.SerializableAttribute()]
    public partial class PERSONA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CORIGINALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CORREO_ELECTRONICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CURPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOMICILIO_CALLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DOMICILIO_CODIGO_POSTALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DOMICILIO_NUM_EXTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOMICILIO_NUM_INTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> ESTADO_CIVILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FEC_NACIMIENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_COLONIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> ID_ENTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> ID_ETNIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> ID_MUNICIPIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> ID_PAISField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_PERSONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> ID_TIPO_DISCAPACIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> ID_TIPO_PERSONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IFEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LUGAR_NACIMIENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MATERNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> NACIONALIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NORIGINALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PATERNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GESAL.BiometricoServiceReference.PERSONA_BIOMETRICO[] PERSONA_BIOMETRICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEXOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMATERNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SNOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SPATERNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELEFONOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELEFONO_MOVILField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORIGINAL {
            get {
                return this.CORIGINALField;
            }
            set {
                if ((object.ReferenceEquals(this.CORIGINALField, value) != true)) {
                    this.CORIGINALField = value;
                    this.RaisePropertyChanged("CORIGINAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO_ELECTRONICO {
            get {
                return this.CORREO_ELECTRONICOField;
            }
            set {
                if ((object.ReferenceEquals(this.CORREO_ELECTRONICOField, value) != true)) {
                    this.CORREO_ELECTRONICOField = value;
                    this.RaisePropertyChanged("CORREO_ELECTRONICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CURP {
            get {
                return this.CURPField;
            }
            set {
                if ((object.ReferenceEquals(this.CURPField, value) != true)) {
                    this.CURPField = value;
                    this.RaisePropertyChanged("CURP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOMICILIO_CALLE {
            get {
                return this.DOMICILIO_CALLEField;
            }
            set {
                if ((object.ReferenceEquals(this.DOMICILIO_CALLEField, value) != true)) {
                    this.DOMICILIO_CALLEField = value;
                    this.RaisePropertyChanged("DOMICILIO_CALLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DOMICILIO_CODIGO_POSTAL {
            get {
                return this.DOMICILIO_CODIGO_POSTALField;
            }
            set {
                if ((this.DOMICILIO_CODIGO_POSTALField.Equals(value) != true)) {
                    this.DOMICILIO_CODIGO_POSTALField = value;
                    this.RaisePropertyChanged("DOMICILIO_CODIGO_POSTAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DOMICILIO_NUM_EXT {
            get {
                return this.DOMICILIO_NUM_EXTField;
            }
            set {
                if ((this.DOMICILIO_NUM_EXTField.Equals(value) != true)) {
                    this.DOMICILIO_NUM_EXTField = value;
                    this.RaisePropertyChanged("DOMICILIO_NUM_EXT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOMICILIO_NUM_INT {
            get {
                return this.DOMICILIO_NUM_INTField;
            }
            set {
                if ((object.ReferenceEquals(this.DOMICILIO_NUM_INTField, value) != true)) {
                    this.DOMICILIO_NUM_INTField = value;
                    this.RaisePropertyChanged("DOMICILIO_NUM_INT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> ESTADO_CIVIL {
            get {
                return this.ESTADO_CIVILField;
            }
            set {
                if ((this.ESTADO_CIVILField.Equals(value) != true)) {
                    this.ESTADO_CIVILField = value;
                    this.RaisePropertyChanged("ESTADO_CIVIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FEC_NACIMIENTO {
            get {
                return this.FEC_NACIMIENTOField;
            }
            set {
                if ((this.FEC_NACIMIENTOField.Equals(value) != true)) {
                    this.FEC_NACIMIENTOField = value;
                    this.RaisePropertyChanged("FEC_NACIMIENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_COLONIA {
            get {
                return this.ID_COLONIAField;
            }
            set {
                if ((this.ID_COLONIAField.Equals(value) != true)) {
                    this.ID_COLONIAField = value;
                    this.RaisePropertyChanged("ID_COLONIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> ID_ENTIDAD {
            get {
                return this.ID_ENTIDADField;
            }
            set {
                if ((this.ID_ENTIDADField.Equals(value) != true)) {
                    this.ID_ENTIDADField = value;
                    this.RaisePropertyChanged("ID_ENTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> ID_ETNIA {
            get {
                return this.ID_ETNIAField;
            }
            set {
                if ((this.ID_ETNIAField.Equals(value) != true)) {
                    this.ID_ETNIAField = value;
                    this.RaisePropertyChanged("ID_ETNIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> ID_MUNICIPIO {
            get {
                return this.ID_MUNICIPIOField;
            }
            set {
                if ((this.ID_MUNICIPIOField.Equals(value) != true)) {
                    this.ID_MUNICIPIOField = value;
                    this.RaisePropertyChanged("ID_MUNICIPIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> ID_PAIS {
            get {
                return this.ID_PAISField;
            }
            set {
                if ((this.ID_PAISField.Equals(value) != true)) {
                    this.ID_PAISField = value;
                    this.RaisePropertyChanged("ID_PAIS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PERSONA {
            get {
                return this.ID_PERSONAField;
            }
            set {
                if ((this.ID_PERSONAField.Equals(value) != true)) {
                    this.ID_PERSONAField = value;
                    this.RaisePropertyChanged("ID_PERSONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> ID_TIPO_DISCAPACIDAD {
            get {
                return this.ID_TIPO_DISCAPACIDADField;
            }
            set {
                if ((this.ID_TIPO_DISCAPACIDADField.Equals(value) != true)) {
                    this.ID_TIPO_DISCAPACIDADField = value;
                    this.RaisePropertyChanged("ID_TIPO_DISCAPACIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> ID_TIPO_PERSONA {
            get {
                return this.ID_TIPO_PERSONAField;
            }
            set {
                if ((this.ID_TIPO_PERSONAField.Equals(value) != true)) {
                    this.ID_TIPO_PERSONAField = value;
                    this.RaisePropertyChanged("ID_TIPO_PERSONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IFE {
            get {
                return this.IFEField;
            }
            set {
                if ((object.ReferenceEquals(this.IFEField, value) != true)) {
                    this.IFEField = value;
                    this.RaisePropertyChanged("IFE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LUGAR_NACIMIENTO {
            get {
                return this.LUGAR_NACIMIENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.LUGAR_NACIMIENTOField, value) != true)) {
                    this.LUGAR_NACIMIENTOField = value;
                    this.RaisePropertyChanged("LUGAR_NACIMIENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MATERNO {
            get {
                return this.MATERNOField;
            }
            set {
                if ((object.ReferenceEquals(this.MATERNOField, value) != true)) {
                    this.MATERNOField = value;
                    this.RaisePropertyChanged("MATERNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> NACIONALIDAD {
            get {
                return this.NACIONALIDADField;
            }
            set {
                if ((this.NACIONALIDADField.Equals(value) != true)) {
                    this.NACIONALIDADField = value;
                    this.RaisePropertyChanged("NACIONALIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NORIGINAL {
            get {
                return this.NORIGINALField;
            }
            set {
                if ((this.NORIGINALField.Equals(value) != true)) {
                    this.NORIGINALField = value;
                    this.RaisePropertyChanged("NORIGINAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PATERNO {
            get {
                return this.PATERNOField;
            }
            set {
                if ((object.ReferenceEquals(this.PATERNOField, value) != true)) {
                    this.PATERNOField = value;
                    this.RaisePropertyChanged("PATERNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GESAL.BiometricoServiceReference.PERSONA_BIOMETRICO[] PERSONA_BIOMETRICO {
            get {
                return this.PERSONA_BIOMETRICOField;
            }
            set {
                if ((object.ReferenceEquals(this.PERSONA_BIOMETRICOField, value) != true)) {
                    this.PERSONA_BIOMETRICOField = value;
                    this.RaisePropertyChanged("PERSONA_BIOMETRICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEXO {
            get {
                return this.SEXOField;
            }
            set {
                if ((object.ReferenceEquals(this.SEXOField, value) != true)) {
                    this.SEXOField = value;
                    this.RaisePropertyChanged("SEXO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMATERNO {
            get {
                return this.SMATERNOField;
            }
            set {
                if ((object.ReferenceEquals(this.SMATERNOField, value) != true)) {
                    this.SMATERNOField = value;
                    this.RaisePropertyChanged("SMATERNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SNOMBRE {
            get {
                return this.SNOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.SNOMBREField, value) != true)) {
                    this.SNOMBREField = value;
                    this.RaisePropertyChanged("SNOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SPATERNO {
            get {
                return this.SPATERNOField;
            }
            set {
                if ((object.ReferenceEquals(this.SPATERNOField, value) != true)) {
                    this.SPATERNOField = value;
                    this.RaisePropertyChanged("SPATERNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEFONO {
            get {
                return this.TELEFONOField;
            }
            set {
                if ((object.ReferenceEquals(this.TELEFONOField, value) != true)) {
                    this.TELEFONOField = value;
                    this.RaisePropertyChanged("TELEFONO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEFONO_MOVIL {
            get {
                return this.TELEFONO_MOVILField;
            }
            set {
                if ((object.ReferenceEquals(this.TELEFONO_MOVILField, value) != true)) {
                    this.TELEFONO_MOVILField = value;
                    this.RaisePropertyChanged("TELEFONO_MOVIL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComparationRequest", Namespace="http://schemas.datacontract.org/2004/07/WCF_BiometricoService.Modelo.Entidades")]
    [System.SerializableAttribute()]
    public partial class ComparationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BIOMETRICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GESAL.BiometricoServiceReference.enumTipoBiometrico ID_TIPO_BIOMETRICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GESAL.BiometricoServiceReference.enumTipoFormato ID_TIPO_FORMATOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<GESAL.BiometricoServiceReference.enumTipoPersona> ID_TIPO_PERSONAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BIOMETRICO {
            get {
                return this.BIOMETRICOField;
            }
            set {
                if ((object.ReferenceEquals(this.BIOMETRICOField, value) != true)) {
                    this.BIOMETRICOField = value;
                    this.RaisePropertyChanged("BIOMETRICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GESAL.BiometricoServiceReference.enumTipoBiometrico ID_TIPO_BIOMETRICO {
            get {
                return this.ID_TIPO_BIOMETRICOField;
            }
            set {
                if ((this.ID_TIPO_BIOMETRICOField.Equals(value) != true)) {
                    this.ID_TIPO_BIOMETRICOField = value;
                    this.RaisePropertyChanged("ID_TIPO_BIOMETRICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GESAL.BiometricoServiceReference.enumTipoFormato ID_TIPO_FORMATO {
            get {
                return this.ID_TIPO_FORMATOField;
            }
            set {
                if ((this.ID_TIPO_FORMATOField.Equals(value) != true)) {
                    this.ID_TIPO_FORMATOField = value;
                    this.RaisePropertyChanged("ID_TIPO_FORMATO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<GESAL.BiometricoServiceReference.enumTipoPersona> ID_TIPO_PERSONA {
            get {
                return this.ID_TIPO_PERSONAField;
            }
            set {
                if ((this.ID_TIPO_PERSONAField.Equals(value) != true)) {
                    this.ID_TIPO_PERSONAField = value;
                    this.RaisePropertyChanged("ID_TIPO_PERSONA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="enumTipoPersona", Namespace="http://schemas.datacontract.org/2004/07/WCF_BiometricoService.Helpers")]
    public enum enumTipoPersona : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PERSONA_EMPLEADO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PERSONA_ABOGADO = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PERSONA_VISITA = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PERSONA_EXTERNA = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IMPUTADO = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompareResponseImputado", Namespace="http://schemas.datacontract.org/2004/07/WCF_BiometricoService.Modelo.Entidades")]
    [System.SerializableAttribute()]
    public partial class CompareResponseImputado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IdentifyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GESAL.BiometricoServiceReference.cHuellasImputado[] ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Identify {
            get {
                return this.IdentifyField;
            }
            set {
                if ((this.IdentifyField.Equals(value) != true)) {
                    this.IdentifyField = value;
                    this.RaisePropertyChanged("Identify");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GESAL.BiometricoServiceReference.cHuellasImputado[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cHuellasImputado", Namespace="http://schemas.datacontract.org/2004/07/WCF_BiometricoService.Modelo.Entidades")]
    [System.SerializableAttribute()]
    public partial class cHuellasImputado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_ANIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_CENTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_IMPUTADOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_ANIO {
            get {
                return this.ID_ANIOField;
            }
            set {
                if ((this.ID_ANIOField.Equals(value) != true)) {
                    this.ID_ANIOField = value;
                    this.RaisePropertyChanged("ID_ANIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_CENTRO {
            get {
                return this.ID_CENTROField;
            }
            set {
                if ((this.ID_CENTROField.Equals(value) != true)) {
                    this.ID_CENTROField = value;
                    this.RaisePropertyChanged("ID_CENTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_IMPUTADO {
            get {
                return this.ID_IMPUTADOField;
            }
            set {
                if ((this.ID_IMPUTADOField.Equals(value) != true)) {
                    this.ID_IMPUTADOField = value;
                    this.RaisePropertyChanged("ID_IMPUTADO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompareResponsePersona", Namespace="http://schemas.datacontract.org/2004/07/WCF_BiometricoService.Modelo.Entidades")]
    [System.SerializableAttribute()]
    public partial class CompareResponsePersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IdentifyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GESAL.BiometricoServiceReference.cHuellasPersona[] ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Identify {
            get {
                return this.IdentifyField;
            }
            set {
                if ((this.IdentifyField.Equals(value) != true)) {
                    this.IdentifyField = value;
                    this.RaisePropertyChanged("Identify");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GESAL.BiometricoServiceReference.cHuellasPersona[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cHuellasPersona", Namespace="http://schemas.datacontract.org/2004/07/WCF_BiometricoService.Modelo.Entidades")]
    [System.SerializableAttribute()]
    public partial class cHuellasPersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_PERSONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NORIGINALField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PERSONA {
            get {
                return this.ID_PERSONAField;
            }
            set {
                if ((this.ID_PERSONAField.Equals(value) != true)) {
                    this.ID_PERSONAField = value;
                    this.RaisePropertyChanged("ID_PERSONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NORIGINAL {
            get {
                return this.NORIGINALField;
            }
            set {
                if ((this.NORIGINALField.Equals(value) != true)) {
                    this.NORIGINALField = value;
                    this.RaisePropertyChanged("NORIGINAL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IMPUTADO_BIOMETRICO2", Namespace="http://schemas.datacontract.org/2004/07/WCF_BiometricoService.Modelo")]
    [System.SerializableAttribute()]
    public partial class IMPUTADO_BIOMETRICO2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BIOMETRICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> CALIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_ANIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_CENTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_FORMATOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_IMPUTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_TIPO_BIOMETRICOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BIOMETRICO {
            get {
                return this.BIOMETRICOField;
            }
            set {
                if ((object.ReferenceEquals(this.BIOMETRICOField, value) != true)) {
                    this.BIOMETRICOField = value;
                    this.RaisePropertyChanged("BIOMETRICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> CALIDAD {
            get {
                return this.CALIDADField;
            }
            set {
                if ((this.CALIDADField.Equals(value) != true)) {
                    this.CALIDADField = value;
                    this.RaisePropertyChanged("CALIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_ANIO {
            get {
                return this.ID_ANIOField;
            }
            set {
                if ((this.ID_ANIOField.Equals(value) != true)) {
                    this.ID_ANIOField = value;
                    this.RaisePropertyChanged("ID_ANIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_CENTRO {
            get {
                return this.ID_CENTROField;
            }
            set {
                if ((this.ID_CENTROField.Equals(value) != true)) {
                    this.ID_CENTROField = value;
                    this.RaisePropertyChanged("ID_CENTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_FORMATO {
            get {
                return this.ID_FORMATOField;
            }
            set {
                if ((this.ID_FORMATOField.Equals(value) != true)) {
                    this.ID_FORMATOField = value;
                    this.RaisePropertyChanged("ID_FORMATO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_IMPUTADO {
            get {
                return this.ID_IMPUTADOField;
            }
            set {
                if ((this.ID_IMPUTADOField.Equals(value) != true)) {
                    this.ID_IMPUTADOField = value;
                    this.RaisePropertyChanged("ID_IMPUTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_TIPO_BIOMETRICO {
            get {
                return this.ID_TIPO_BIOMETRICOField;
            }
            set {
                if ((this.ID_TIPO_BIOMETRICOField.Equals(value) != true)) {
                    this.ID_TIPO_BIOMETRICOField = value;
                    this.RaisePropertyChanged("ID_TIPO_BIOMETRICO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BiometricoServiceReference.IBiometricoService")]
    public interface IBiometricoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/GetData", ReplyAction="http://tempuri.org/IBiometricoService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/DescargarWSQ", ReplyAction="http://tempuri.org/IBiometricoService/DescargarWSQResponse")]
        byte[] DescargarWSQ(short ID_CENTRO, short ID_ANIO, int ID_IMPUTADO, GESAL.BiometricoServiceReference.enumTipoBiometrico Dedo, GESAL.BiometricoServiceReference.enumTipoFormato Formato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/InsertarHuellaImputado", ReplyAction="http://tempuri.org/IBiometricoService/InsertarHuellaImputadoResponse")]
        bool InsertarHuellaImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/InsertarHuellasImputado", ReplyAction="http://tempuri.org/IBiometricoService/InsertarHuellasImputadoResponse")]
        bool InsertarHuellasImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO[] Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/ActualizarHuellasImputado", ReplyAction="http://tempuri.org/IBiometricoService/ActualizarHuellasImputadoResponse")]
        bool ActualizarHuellasImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO[] Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/RollBackImputado", ReplyAction="http://tempuri.org/IBiometricoService/RollBackImputadoResponse")]
        bool RollBackImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/ExistenHuellasImputado", ReplyAction="http://tempuri.org/IBiometricoService/ExistenHuellasImputadoResponse")]
        bool ExistenHuellasImputado(GESAL.BiometricoServiceReference.ComparationRequest[] Huellas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/CompararHuellaImputado", ReplyAction="http://tempuri.org/IBiometricoService/CompararHuellaImputadoResponse")]
        GESAL.BiometricoServiceReference.CompareResponseImputado CompararHuellaImputado(GESAL.BiometricoServiceReference.ComparationRequest DataCompare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/InsertarHuellaPersona", ReplyAction="http://tempuri.org/IBiometricoService/InsertarHuellaPersonaResponse")]
        bool InsertarHuellaPersona(GESAL.BiometricoServiceReference.PERSONA_BIOMETRICO Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/InsertarHuellasPersona", ReplyAction="http://tempuri.org/IBiometricoService/InsertarHuellasPersonaResponse")]
        bool InsertarHuellasPersona(GESAL.BiometricoServiceReference.PERSONA_BIOMETRICO[] Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/ActualizarHuellasPersona", ReplyAction="http://tempuri.org/IBiometricoService/ActualizarHuellasPersonaResponse")]
        bool ActualizarHuellasPersona(GESAL.BiometricoServiceReference.PERSONA_BIOMETRICO[] Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/RollBackPersona", ReplyAction="http://tempuri.org/IBiometricoService/RollBackPersonaResponse")]
        bool RollBackPersona(GESAL.BiometricoServiceReference.PERSONA_BIOMETRICO Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/CompararHuellaPersona", ReplyAction="http://tempuri.org/IBiometricoService/CompararHuellaPersonaResponse")]
        GESAL.BiometricoServiceReference.CompareResponsePersona CompararHuellaPersona(GESAL.BiometricoServiceReference.ComparationRequest DataCompare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/PRUEBAInsertarHuellaImputado", ReplyAction="http://tempuri.org/IBiometricoService/PRUEBAInsertarHuellaImputadoResponse")]
        bool PRUEBAInsertarHuellaImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO2 Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/PRUEBAInsertarHuellasImputado", ReplyAction="http://tempuri.org/IBiometricoService/PRUEBAInsertarHuellasImputadoResponse")]
        bool PRUEBAInsertarHuellasImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO2[] Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/PRUEBAActualizarHuellasImputado", ReplyAction="http://tempuri.org/IBiometricoService/PRUEBAActualizarHuellasImputadoResponse")]
        bool PRUEBAActualizarHuellasImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO2[] Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/PRUEBARollBackImputado", ReplyAction="http://tempuri.org/IBiometricoService/PRUEBARollBackImputadoResponse")]
        bool PRUEBARollBackImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO2 Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/PRUEBAExistenHuellasImputado", ReplyAction="http://tempuri.org/IBiometricoService/PRUEBAExistenHuellasImputadoResponse")]
        bool PRUEBAExistenHuellasImputado(GESAL.BiometricoServiceReference.ComparationRequest[] Huellas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometricoService/PRUEBACompararHuellaImputado", ReplyAction="http://tempuri.org/IBiometricoService/PRUEBACompararHuellaImputadoResponse")]
        GESAL.BiometricoServiceReference.CompareResponseImputado PRUEBACompararHuellaImputado(GESAL.BiometricoServiceReference.ComparationRequest DataCompare);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBiometricoServiceChannel : GESAL.BiometricoServiceReference.IBiometricoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BiometricoServiceClient : System.ServiceModel.ClientBase<GESAL.BiometricoServiceReference.IBiometricoService>, GESAL.BiometricoServiceReference.IBiometricoService {
        
        public BiometricoServiceClient() {
        }
        
        public BiometricoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BiometricoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiometricoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiometricoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public byte[] DescargarWSQ(short ID_CENTRO, short ID_ANIO, int ID_IMPUTADO, GESAL.BiometricoServiceReference.enumTipoBiometrico Dedo, GESAL.BiometricoServiceReference.enumTipoFormato Formato) {
            return base.Channel.DescargarWSQ(ID_CENTRO, ID_ANIO, ID_IMPUTADO, Dedo, Formato);
        }
        
        public bool InsertarHuellaImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO Data) {
            return base.Channel.InsertarHuellaImputado(Data);
        }
        
        public bool InsertarHuellasImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO[] Data) {
            return base.Channel.InsertarHuellasImputado(Data);
        }
        
        public bool ActualizarHuellasImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO[] Data) {
            return base.Channel.ActualizarHuellasImputado(Data);
        }
        
        public bool RollBackImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO Data) {
            return base.Channel.RollBackImputado(Data);
        }
        
        public bool ExistenHuellasImputado(GESAL.BiometricoServiceReference.ComparationRequest[] Huellas) {
            return base.Channel.ExistenHuellasImputado(Huellas);
        }
        
        public GESAL.BiometricoServiceReference.CompareResponseImputado CompararHuellaImputado(GESAL.BiometricoServiceReference.ComparationRequest DataCompare) {
            return base.Channel.CompararHuellaImputado(DataCompare);
        }
        
        public bool InsertarHuellaPersona(GESAL.BiometricoServiceReference.PERSONA_BIOMETRICO Data) {
            return base.Channel.InsertarHuellaPersona(Data);
        }
        
        public bool InsertarHuellasPersona(GESAL.BiometricoServiceReference.PERSONA_BIOMETRICO[] Data) {
            return base.Channel.InsertarHuellasPersona(Data);
        }
        
        public bool ActualizarHuellasPersona(GESAL.BiometricoServiceReference.PERSONA_BIOMETRICO[] Data) {
            return base.Channel.ActualizarHuellasPersona(Data);
        }
        
        public bool RollBackPersona(GESAL.BiometricoServiceReference.PERSONA_BIOMETRICO Data) {
            return base.Channel.RollBackPersona(Data);
        }
        
        public GESAL.BiometricoServiceReference.CompareResponsePersona CompararHuellaPersona(GESAL.BiometricoServiceReference.ComparationRequest DataCompare) {
            return base.Channel.CompararHuellaPersona(DataCompare);
        }
        
        public bool PRUEBAInsertarHuellaImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO2 Data) {
            return base.Channel.PRUEBAInsertarHuellaImputado(Data);
        }
        
        public bool PRUEBAInsertarHuellasImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO2[] Data) {
            return base.Channel.PRUEBAInsertarHuellasImputado(Data);
        }
        
        public bool PRUEBAActualizarHuellasImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO2[] Data) {
            return base.Channel.PRUEBAActualizarHuellasImputado(Data);
        }
        
        public bool PRUEBARollBackImputado(GESAL.BiometricoServiceReference.IMPUTADO_BIOMETRICO2 Data) {
            return base.Channel.PRUEBARollBackImputado(Data);
        }
        
        public bool PRUEBAExistenHuellasImputado(GESAL.BiometricoServiceReference.ComparationRequest[] Huellas) {
            return base.Channel.PRUEBAExistenHuellasImputado(Huellas);
        }
        
        public GESAL.BiometricoServiceReference.CompareResponseImputado PRUEBACompararHuellaImputado(GESAL.BiometricoServiceReference.ComparationRequest DataCompare) {
            return base.Channel.PRUEBACompararHuellaImputado(DataCompare);
        }
    }
}
