namespace Biometrico.Shared
{
    public enum enumTipoBiometrico
    {
        FOTOGRAFIA_SALIDA = 1,
        
        FOTO_FRENTE_REGISTRO = 2,
        FOTO_DER_REGISTRO = 3,
        FOTO_IZQ_REGISTRO = 4,

        FOTO_FRENTE_SEGUIMIENTO = 5,
        FOTO_DER_SEGUIMIENTO = 6,
        FOTO_IZQ_SEGUIMIENTO = 7,

        PULGAR_DERECHO = 11,
        INDICE_DERECHO = 12,
        MEDIO_DERECHO = 13,
        ANULAR_DERECHO = 14,
        MENIQUE_DERECHO = 15,
        PULGAR_IZQUIERDO = 16,
        INDICE_IZQUIERDO = 17,
        MEDIO_IZQUIERDO = 18,
        ANULAR_IZQUIERDO = 19,
        MENIQUE_IZQUIERDO = 20,

        PULGAR_DERECHO_WSQ = 21,
        INDICE_DERECHO_WSQ = 22,
        MEDIO_DERECHO_WSQ = 23,
        ANULAR_DERECHO_WSQ = 24,
        MENIQUE_DERECHO_WSQ = 25,
        PULGAR_IZQUIERDO_WSQ = 26,
        INDICE_IZQUIERDO_WSQ = 27,
        MEDIO_IZQUIERDO_WSQ = 28,
        ANULAR_IZQUIERDO_WSQ = 29,
        MENIQUE_IZQUIERDO_WSQ = 30,
    }
}
