//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPenales.MenoresHuellasService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenoresHuellasService.dpersonSoap")]
    public interface dpersonSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Valida_equipo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Valida_equipo(string cereso, string opip, string opmac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cat_bio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable cat_bio(string cereso);
        
        // CODEGEN: Parameter 'capResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/requestEnrroll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ControlPenales.MenoresHuellasService.requestEnrrollResponse requestEnrroll(ControlPenales.MenoresHuellasService.requestEnrrollRequest request);
        
        // CODEGEN: Parameter 'capResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/requesSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ControlPenales.MenoresHuellasService.requesSearchResponse requesSearch(ControlPenales.MenoresHuellasService.requesSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/requestEnrrollSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable requestEnrrollSearch(string cereso, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeneraXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GeneraXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeneraXMLInd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GeneraXMLInd(string prefijo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetHuella", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SetHuella(string _pprefijo, string _pnum_visita, string _pano, string _pfolio, string _pbiometrico, string _phuella, string _numabogado, string _registro, string centro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCadena", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCadena(string _prefijo, string _numVisita, string _ano, string _folio, string _log, string _numabogado, string _registro, string centro);
        
        // CODEGEN: Parameter '_huella' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Compara", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ControlPenales.MenoresHuellasService.ComparaResponse Compara(ControlPenales.MenoresHuellasService.ComparaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="requestEnrroll", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class requestEnrrollRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cereso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int biometrico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] capResult;
        
        public requestEnrrollRequest() {
        }
        
        public requestEnrrollRequest(string cereso, string login, int biometrico, byte[] capResult) {
            this.cereso = cereso;
            this.login = login;
            this.biometrico = biometrico;
            this.capResult = capResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="requestEnrrollResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class requestEnrrollResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string requestEnrrollResult;
        
        public requestEnrrollResponse() {
        }
        
        public requestEnrrollResponse(string requestEnrrollResult) {
            this.requestEnrrollResult = requestEnrrollResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="requesSearch", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class requesSearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cereso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] capResult;
        
        public requesSearchRequest() {
        }
        
        public requesSearchRequest(string cereso, byte[] capResult) {
            this.cereso = cereso;
            this.capResult = capResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="requesSearchResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class requesSearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string requesSearchResult;
        
        public requesSearchResponse() {
        }
        
        public requesSearchResponse(string requesSearchResult) {
            this.requesSearchResult = requesSearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Compara", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ComparaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] _huella;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string _prefijo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string centro;
        
        public ComparaRequest() {
        }
        
        public ComparaRequest(byte[] _huella, string _prefijo, string centro) {
            this._huella = _huella;
            this._prefijo = _prefijo;
            this.centro = centro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ComparaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ComparaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ComparaResult;
        
        public ComparaResponse() {
        }
        
        public ComparaResponse(string ComparaResult) {
            this.ComparaResult = ComparaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface dpersonSoapChannel : ControlPenales.MenoresHuellasService.dpersonSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class dpersonSoapClient : System.ServiceModel.ClientBase<ControlPenales.MenoresHuellasService.dpersonSoap>, ControlPenales.MenoresHuellasService.dpersonSoap {
        
        public dpersonSoapClient() {
        }
        
        public dpersonSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public dpersonSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public dpersonSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public dpersonSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Valida_equipo(string cereso, string opip, string opmac) {
            return base.Channel.Valida_equipo(cereso, opip, opmac);
        }
        
        public System.Data.DataTable cat_bio(string cereso) {
            return base.Channel.cat_bio(cereso);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ControlPenales.MenoresHuellasService.requestEnrrollResponse ControlPenales.MenoresHuellasService.dpersonSoap.requestEnrroll(ControlPenales.MenoresHuellasService.requestEnrrollRequest request) {
            return base.Channel.requestEnrroll(request);
        }
        
        public string requestEnrroll(string cereso, string login, int biometrico, byte[] capResult) {
            ControlPenales.MenoresHuellasService.requestEnrrollRequest inValue = new ControlPenales.MenoresHuellasService.requestEnrrollRequest();
            inValue.cereso = cereso;
            inValue.login = login;
            inValue.biometrico = biometrico;
            inValue.capResult = capResult;
            ControlPenales.MenoresHuellasService.requestEnrrollResponse retVal = ((ControlPenales.MenoresHuellasService.dpersonSoap)(this)).requestEnrroll(inValue);
            return retVal.requestEnrrollResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ControlPenales.MenoresHuellasService.requesSearchResponse ControlPenales.MenoresHuellasService.dpersonSoap.requesSearch(ControlPenales.MenoresHuellasService.requesSearchRequest request) {
            return base.Channel.requesSearch(request);
        }
        
        public string requesSearch(string cereso, byte[] capResult) {
            ControlPenales.MenoresHuellasService.requesSearchRequest inValue = new ControlPenales.MenoresHuellasService.requesSearchRequest();
            inValue.cereso = cereso;
            inValue.capResult = capResult;
            ControlPenales.MenoresHuellasService.requesSearchResponse retVal = ((ControlPenales.MenoresHuellasService.dpersonSoap)(this)).requesSearch(inValue);
            return retVal.requesSearchResult;
        }
        
        public System.Data.DataTable requestEnrrollSearch(string cereso, string usuario) {
            return base.Channel.requestEnrrollSearch(cereso, usuario);
        }
        
        public void GeneraXML() {
            base.Channel.GeneraXML();
        }
        
        public void GeneraXMLInd(string prefijo) {
            base.Channel.GeneraXMLInd(prefijo);
        }
        
        public void SetHuella(string _pprefijo, string _pnum_visita, string _pano, string _pfolio, string _pbiometrico, string _phuella, string _numabogado, string _registro, string centro) {
            base.Channel.SetHuella(_pprefijo, _pnum_visita, _pano, _pfolio, _pbiometrico, _phuella, _numabogado, _registro, centro);
        }
        
        public string GetCadena(string _prefijo, string _numVisita, string _ano, string _folio, string _log, string _numabogado, string _registro, string centro) {
            return base.Channel.GetCadena(_prefijo, _numVisita, _ano, _folio, _log, _numabogado, _registro, centro);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ControlPenales.MenoresHuellasService.ComparaResponse ControlPenales.MenoresHuellasService.dpersonSoap.Compara(ControlPenales.MenoresHuellasService.ComparaRequest request) {
            return base.Channel.Compara(request);
        }
        
        public string Compara(byte[] _huella, string _prefijo, string centro) {
            ControlPenales.MenoresHuellasService.ComparaRequest inValue = new ControlPenales.MenoresHuellasService.ComparaRequest();
            inValue._huella = _huella;
            inValue._prefijo = _prefijo;
            inValue.centro = centro;
            ControlPenales.MenoresHuellasService.ComparaResponse retVal = ((ControlPenales.MenoresHuellasService.dpersonSoap)(this)).Compara(inValue);
            return retVal.ComparaResult;
        }
    }
}
