//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABOGADO_CAUSA_PENAL
    {
        public ABOGADO_CAUSA_PENAL()
        {
            this.ABOGADO_CP_DOCTO = new HashSet<ABOGADO_CP_DOCTO>();
        }
    
        public int ID_ABOGADO { get; set; }
        public string ID_ABOGADO_TITULO { get; set; }
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_CAUSA_PENAL { get; set; }
        public Nullable<System.DateTime> CAPTURA_FEC { get; set; }
        public Nullable<short> ID_ESTATUS_VISITA { get; set; }
        public int ID_ABOGADO_TITULAR { get; set; }
    
        public virtual ABOGADO_INGRESO ABOGADO_INGRESO { get; set; }
        public virtual ESTATUS_VISITA ESTATUS_VISITA { get; set; }
        public virtual ICollection<ABOGADO_CP_DOCTO> ABOGADO_CP_DOCTO { get; set; }
        public virtual CAUSA_PENAL CAUSA_PENAL { get; set; }
    }
}
