//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDAD
    {
        public ACTIVIDAD()
        {
            this.GRUPO_PARTICIPANTE = new HashSet<GRUPO_PARTICIPANTE>();
            this.PFC_VI_GRUPO = new HashSet<PFC_VI_GRUPO>();
            this.ACTIVIDAD_EJE = new HashSet<ACTIVIDAD_EJE>();
            this.GRUPO = new HashSet<GRUPO>();
            this.PFC_IV_PROGRAMA = new HashSet<PFC_IV_PROGRAMA>();
            this.PFC_VIII_ACTIVIDAD_LABORAL = new HashSet<PFC_VIII_ACTIVIDAD_LABORAL>();
            this.PFC_VII_ACTIVIDAD = new HashSet<PFC_VII_ACTIVIDAD>();
        }
    
        public short ID_TIPO_PROGRAMA { get; set; }
        public short ID_ACTIVIDAD { get; set; }
        public string DESCR { get; set; }
        public string OBJETIVO { get; set; }
        public Nullable<short> ESTATUS { get; set; }
        public Nullable<short> ESTAPA { get; set; }
        public Nullable<short> OCUPANTE_MAX { get; set; }
        public Nullable<short> OCUPANTE_MIN { get; set; }
        public Nullable<short> PRIORIDAD { get; set; }
        public Nullable<short> ORDEN { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual TIPO_PROGRAMA TIPO_PROGRAMA { get; set; }
        public virtual ICollection<GRUPO_PARTICIPANTE> GRUPO_PARTICIPANTE { get; set; }
        public virtual ICollection<PFC_VI_GRUPO> PFC_VI_GRUPO { get; set; }
        public virtual ICollection<ACTIVIDAD_EJE> ACTIVIDAD_EJE { get; set; }
        public virtual ICollection<GRUPO> GRUPO { get; set; }
        public virtual ICollection<PFC_IV_PROGRAMA> PFC_IV_PROGRAMA { get; set; }
        public virtual ICollection<PFC_VIII_ACTIVIDAD_LABORAL> PFC_VIII_ACTIVIDAD_LABORAL { get; set; }
        public virtual ICollection<PFC_VII_ACTIVIDAD> PFC_VII_ACTIVIDAD { get; set; }
    }
}
