//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADUANA
    {
        public ADUANA()
        {
            this.ADUANA_ACOMPANANTE = new HashSet<ADUANA_ACOMPANANTE>();
            this.PERSONA_PERTENENCIA = new HashSet<PERSONA_PERTENENCIA>();
            this.ADUANA_INGRESO = new HashSet<ADUANA_INGRESO>();
        }
    
        public int ID_ADUANA { get; set; }
        public short ID_CENTRO { get; set; }
        public int ID_PERSONA { get; set; }
        public Nullable<short> ID_AREA { get; set; }
        public Nullable<short> ID_TIPO_PERSONA { get; set; }
        public Nullable<System.DateTime> ENTRADA_FEC { get; set; }
        public Nullable<System.DateTime> SALIDA_FEC { get; set; }
        public string ASUNTO { get; set; }
        public string OBSERV { get; set; }
        public string INSTITUCION { get; set; }
        public Nullable<short> NUM_LOCKER { get; set; }
        public string DEPARTAMENTO { get; set; }
        public Nullable<short> ID_PUESTO { get; set; }
        public string ID_USUARIO { get; set; }
    
        public virtual ICollection<ADUANA_ACOMPANANTE> ADUANA_ACOMPANANTE { get; set; }
        public virtual AREA AREA { get; set; }
        public virtual CENTRO CENTRO { get; set; }
        public virtual PUESTO PUESTO { get; set; }
        public virtual TIPO_PERSONA TIPO_PERSONA { get; set; }
        public virtual ICollection<PERSONA_PERTENENCIA> PERSONA_PERTENENCIA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual ICollection<ADUANA_INGRESO> ADUANA_INGRESO { get; set; }
    }
}
