//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADUANA_INGRESO_CP
    {
        public int ID_ADUANA { get; set; }
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_CAUSA_PENAL { get; set; }
        public Nullable<System.DateTime> ENTRADA_FEC { get; set; }
    
        public virtual CAUSA_PENAL CAUSA_PENAL { get; set; }
        public virtual ADUANA_INGRESO ADUANA_INGRESO { get; set; }
    }
}
