//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADUANA_INGRESO
    {
        public ADUANA_INGRESO()
        {
            this.ADUANA_INGRESO_CP = new HashSet<ADUANA_INGRESO_CP>();
        }
    
        public int ID_ADUANA { get; set; }
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public Nullable<System.DateTime> ENTRADA_FEC { get; set; }
        public string ADMINISTRATIVO { get; set; }
        public string INTIMA { get; set; }
        public string CAUSA_PENAL { get; set; }
        public string INTERNO_NOTIFICADO { get; set; }
        public Nullable<int> ID_PERSONA { get; set; }
        public Nullable<short> ID_CONSEC { get; set; }
    
        public virtual ADUANA ADUANA { get; set; }
        public virtual ICollection<ADUANA_INGRESO_CP> ADUANA_INGRESO_CP { get; set; }
        public virtual VISITANTE_INGRESO_PASE VISITANTE_INGRESO_PASE { get; set; }
        public virtual INGRESO INGRESO { get; set; }
    }
}
