//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDA_ACTIVIDAD_LIBERTAD
    {
        public AGENDA_ACTIVIDAD_LIBERTAD()
        {
            this.AGENDA_ACT_LIB_DETALLE = new HashSet<AGENDA_ACT_LIB_DETALLE>();
            this.AGENDA_LIBERTAD_DOCUMENTO = new HashSet<AGENDA_LIBERTAD_DOCUMENTO>();
        }
    
        public decimal ID_AGENDA_ACTIVIDAD_LIBERTAD { get; set; }
        public Nullable<short> ID_CENTRO { get; set; }
        public Nullable<short> ID_ANIO { get; set; }
        public Nullable<int> ID_IMPUTADO { get; set; }
        public Nullable<short> ID_PROCESO_LIBERTAD { get; set; }
        public Nullable<decimal> ID_ESTATUS { get; set; }
        public Nullable<decimal> ID_UNIDAD_RECEPTORA { get; set; }
        public Nullable<decimal> ID_PROGRAMA_LIBERTAD { get; set; }
        public Nullable<decimal> ID_ACTIVIDAD_PROGRAMA { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FINAL { get; set; }
        public string REMUNERADA { get; set; }
        public string FIRMA_INICIO { get; set; }
        public string FIRMA_FINAL { get; set; }
    
        public virtual ICollection<AGENDA_ACT_LIB_DETALLE> AGENDA_ACT_LIB_DETALLE { get; set; }
        public virtual AGENDA_ACTIVIDAD_ESTATUS AGENDA_ACTIVIDAD_ESTATUS { get; set; }
        public virtual UNIDAD_RECEPTORA UNIDAD_RECEPTORA { get; set; }
        public virtual ACTIVIDAD_PROGRAMA ACTIVIDAD_PROGRAMA { get; set; }
        public virtual ICollection<AGENDA_LIBERTAD_DOCUMENTO> AGENDA_LIBERTAD_DOCUMENTO { get; set; }
        public virtual PROCESO_LIBERTAD PROCESO_LIBERTAD { get; set; }
    }
}
