//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMPARO_DIRECTO_SENTENCIA
    {
        public AMPARO_DIRECTO_SENTENCIA()
        {
            this.AMPARO_DIRECTO = new HashSet<AMPARO_DIRECTO>();
        }
    
        public short ID_SEN_AMP_RESULTADO { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<AMPARO_DIRECTO> AMPARO_DIRECTO { get; set; }
    }
}
