//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMPARO_INDIRECTO_TIPOS
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_AMPARO_INDIRECTO { get; set; }
        public short ID_AMP_IND_TIPO { get; set; }
        public Nullable<short> ID_SEN_AMP_RESULTADO { get; set; }
    
        public virtual AMPARO_INDIRECTO AMPARO_INDIRECTO { get; set; }
        public virtual AMPARO_INDIRECTO_SENTENCIA AMPARO_INDIRECTO_SENTENCIA { get; set; }
        public virtual AMPARO_INDIRECTO_TIPO AMPARO_INDIRECTO_TIPO { get; set; }
    }
}
