//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANATOMIA_TOPOGRAFICA
    {
        public ANATOMIA_TOPOGRAFICA()
        {
            this.SENAS_PARTICULARES = new HashSet<SENAS_PARTICULARES>();
            this.LESION = new HashSet<LESION>();
            this.HOJA_ENFERMERIA_ULCERA = new HashSet<HOJA_ENFERMERIA_ULCERA>();
        }
    
        public short ID_REGION { get; set; }
        public string DESCR { get; set; }
        public string LADO { get; set; }
        public string LATERAL { get; set; }
    
        public virtual ICollection<SENAS_PARTICULARES> SENAS_PARTICULARES { get; set; }
        public virtual ICollection<LESION> LESION { get; set; }
        public virtual ICollection<HOJA_ENFERMERIA_ULCERA> HOJA_ENFERMERIA_ULCERA { get; set; }
    }
}
