//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class AREA_TECNICA
    {
        public AREA_TECNICA()
        {
            this.PFF_ACTA_DETERMINO = new HashSet<PFF_ACTA_DETERMINO>();
            this.DEPARTAMENTO_AREA_TECNICA = new HashSet<DEPARTAMENTO_AREA_TECNICA>();
            this.ATENCION_SOLICITUD = new HashSet<ATENCION_SOLICITUD>();
        }
    
        public short ID_TECNICA { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<PFF_ACTA_DETERMINO> PFF_ACTA_DETERMINO { get; set; }
        public virtual ICollection<DEPARTAMENTO_AREA_TECNICA> DEPARTAMENTO_AREA_TECNICA { get; set; }
        public virtual ICollection<ATENCION_SOLICITUD> ATENCION_SOLICITUD { get; set; }
    }
}
