//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATENCION_SERVICIO
    {
        public ATENCION_SERVICIO()
        {
            this.ATENCION_CITA = new HashSet<ATENCION_CITA>();
            this.ATENCION_MEDICA = new HashSet<ATENCION_MEDICA>();
            this.TV_CITA_MEDICA = new HashSet<TV_CITA_MEDICA>();
        }
    
        public short ID_TIPO_SERVICIO { get; set; }
        public short ID_TIPO_ATENCION { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ATENCION_TIPO ATENCION_TIPO { get; set; }
        public virtual ICollection<ATENCION_CITA> ATENCION_CITA { get; set; }
        public virtual ICollection<ATENCION_MEDICA> ATENCION_MEDICA { get; set; }
        public virtual ICollection<TV_CITA_MEDICA> TV_CITA_MEDICA { get; set; }
    }
}
