//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMA_HOSPITAL
    {
        public CAMA_HOSPITAL()
        {
            this.HOSPITALIZACION = new HashSet<HOSPITALIZACION>();
        }
    
        public short ID_CAMA_HOSPITAL { get; set; }
        public short ID_CENTRO { get; set; }
        public string DESCR { get; set; }
        public string ID_USUARIO { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
    
        public virtual CENTRO CENTRO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<HOSPITALIZACION> HOSPITALIZACION { get; set; }
    }
}
