//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATETER_TIPO
    {
        public CATETER_TIPO()
        {
            this.HOJA_ENFERMERIA_CATETER = new HashSet<HOJA_ENFERMERIA_CATETER>();
        }
    
        public decimal ID_CATETER { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<HOJA_ENFERMERIA_CATETER> HOJA_ENFERMERIA_CATETER { get; set; }
    }
}
