//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUSA_PENAL
    {
        public CAUSA_PENAL()
        {
            this.ABOGADO_CAUSA_PENAL = new HashSet<ABOGADO_CAUSA_PENAL>();
            this.ADUANA_INGRESO_CP = new HashSet<ADUANA_INGRESO_CP>();
            this.AMPARO_INDIRECTO = new HashSet<AMPARO_INDIRECTO>();
            this.CAUSA_PENAL_DELITO = new HashSet<CAUSA_PENAL_DELITO>();
            this.CAUSA_PENAL_DOCTO = new HashSet<CAUSA_PENAL_DOCTO>();
            this.COPARTICIPE = new HashSet<COPARTICIPE>();
            this.LIBERACION = new HashSet<LIBERACION>();
            this.SENTENCIA = new HashSet<SENTENCIA>();
            this.AMPARO_DIRECTO = new HashSet<AMPARO_DIRECTO>();
            this.AMPARO_INCIDENTE = new HashSet<AMPARO_INCIDENTE>();
            this.RECURSO = new HashSet<RECURSO>();
            this.EXCARCELACION_DESTINO = new HashSet<EXCARCELACION_DESTINO>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_CAUSA_PENAL { get; set; }
        public Nullable<short> AP_ANIO { get; set; }
        public Nullable<int> AP_FOLIO { get; set; }
        public string AP_FORANEA { get; set; }
        public Nullable<System.DateTime> AP_FEC_INICIO { get; set; }
        public Nullable<System.DateTime> AP_FEC_CONSIGNACION { get; set; }
        public Nullable<short> CP_ANIO { get; set; }
        public Nullable<int> CP_FOLIO { get; set; }
        public string CP_BIS { get; set; }
        public string CP_FORANEO { get; set; }
        public Nullable<short> CP_TIPO_ORDEN { get; set; }
        public Nullable<short> CP_PAIS_JUZGADO { get; set; }
        public Nullable<short> CP_ESTADO_JUZGADO { get; set; }
        public Nullable<short> CP_MUNICIPIO_JUZGADO { get; set; }
        public string CP_FUERO { get; set; }
        public Nullable<short> CP_JUZGADO { get; set; }
        public Nullable<System.DateTime> CP_FEC_RADICACION { get; set; }
        public string CP_AMPLIACION { get; set; }
        public Nullable<System.DateTime> CP_FEC_VENCIMIENTO_TERMINO { get; set; }
        public Nullable<short> CP_TERMINO { get; set; }
        public Nullable<short> ID_AGENCIA { get; set; }
        public Nullable<short> ID_ENTIDAD { get; set; }
        public Nullable<short> ID_MUNICIPIO { get; set; }
        public Nullable<short> ID_ESTATUS_CP { get; set; }
        public string OBSERV { get; set; }
        public Nullable<System.DateTime> BAJA_FEC { get; set; }
        public Nullable<short> ID_MOTIVO_BAJA { get; set; }
        public Nullable<short> ID_AUTO_BAJA { get; set; }
    
        public virtual ICollection<ABOGADO_CAUSA_PENAL> ABOGADO_CAUSA_PENAL { get; set; }
        public virtual ICollection<ADUANA_INGRESO_CP> ADUANA_INGRESO_CP { get; set; }
        public virtual AGENCIA AGENCIA { get; set; }
        public virtual ICollection<AMPARO_INDIRECTO> AMPARO_INDIRECTO { get; set; }
        public virtual CAUSA_PENAL_ESTATUS CAUSA_PENAL_ESTATUS { get; set; }
        public virtual ENTIDAD ENTIDAD { get; set; }
        public virtual JUZGADO JUZGADO { get; set; }
        public virtual MUNICIPIO MUNICIPIO { get; set; }
        public virtual PAIS_NACIONALIDAD PAIS_NACIONALIDAD { get; set; }
        public virtual ICollection<CAUSA_PENAL_DELITO> CAUSA_PENAL_DELITO { get; set; }
        public virtual ICollection<CAUSA_PENAL_DOCTO> CAUSA_PENAL_DOCTO { get; set; }
        public virtual TERMINO TERMINO { get; set; }
        public virtual TIPO_ORDEN TIPO_ORDEN { get; set; }
        public virtual ICollection<COPARTICIPE> COPARTICIPE { get; set; }
        public virtual ICollection<LIBERACION> LIBERACION { get; set; }
        public virtual NUC NUC { get; set; }
        public virtual ICollection<SENTENCIA> SENTENCIA { get; set; }
        public virtual ICollection<AMPARO_DIRECTO> AMPARO_DIRECTO { get; set; }
        public virtual ICollection<AMPARO_INCIDENTE> AMPARO_INCIDENTE { get; set; }
        public virtual ICollection<RECURSO> RECURSO { get; set; }
        public virtual INGRESO INGRESO { get; set; }
        public virtual ICollection<EXCARCELACION_DESTINO> EXCARCELACION_DESTINO { get; set; }
    }
}
