//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTRO
    {
        public CENTRO()
        {
            this.ABOGADO_DOCUMENTO = new HashSet<ABOGADO_DOCUMENTO>();
            this.ALMACEN = new HashSet<ALMACEN>();
            this.CENTRO_DEPARTAMENTO = new HashSet<CENTRO_DEPARTAMENTO>();
            this.GRUPO_PARTICIPANTE = new HashSet<GRUPO_PARTICIPANTE>();
            this.PERSONA_NIP = new HashSet<PERSONA_NIP>();
            this.PROGRAMA = new HashSet<PROGRAMA>();
            this.EDIFICIO = new HashSet<EDIFICIO>();
            this.CATALOGO_EQUIPOS = new HashSet<CATALOGO_EQUIPOS>();
            this.VISITA_APELLIDO = new HashSet<VISITA_APELLIDO>();
            this.EXCARCELACION_TRANSITO = new HashSet<EXCARCELACION_TRANSITO>();
            this.EVENTO = new HashSet<EVENTO>();
            this.EVENTO1 = new HashSet<EVENTO>();
            this.ADUANA = new HashSet<ADUANA>();
            this.MENSAJE = new HashSet<MENSAJE>();
            this.PFF_ACTA_CONSEJO_TECNICO = new HashSet<PFF_ACTA_CONSEJO_TECNICO>();
            this.EMPLEADO = new HashSet<EMPLEADO>();
            this.PROCESO_USUARIO = new HashSet<PROCESO_USUARIO>();
            this.USUARIO_ROL = new HashSet<USUARIO_ROL>();
            this.PERSONA_EXTERNO = new HashSet<PERSONA_EXTERNO>();
            this.VISITA_EXTERNA = new HashSet<VISITA_EXTERNA>();
            this.CAMA_HOSPITAL = new HashSet<CAMA_HOSPITAL>();
            this.ATENCION_SOLICITUD = new HashSet<ATENCION_SOLICITUD>();
            this.SOL_INTERCONSULTA_INTERNA = new HashSet<SOL_INTERCONSULTA_INTERNA>();
            this.NOTIFICACION_TS = new HashSet<NOTIFICACION_TS>();
            this.ESPECIALISTA = new HashSet<ESPECIALISTA>();
            this.INGRESO = new HashSet<INGRESO>();
            this.INGRESO1 = new HashSet<INGRESO>();
            this.IMPUTADO = new HashSet<IMPUTADO>();
            this.TRASLADO = new HashSet<TRASLADO>();
            this.TRASLADO1 = new HashSet<TRASLADO>();
            this.TRASLADO2 = new HashSet<TRASLADO>();
            this.INCIDENCIAS_CATETER = new HashSet<INCIDENCIAS_CATETER>();
            this.INCIDENCIAS_SONDA_GAS = new HashSet<INCIDENCIAS_SONDA_GAS>();
            this.TV_CANALIZACION = new HashSet<TV_CANALIZACION>();
            this.TV_CITA_MEDICA = new HashSet<TV_CITA_MEDICA>();
            this.TV_SOL_INTERCONSULTA_INTERNA = new HashSet<TV_SOL_INTERCONSULTA_INTERNA>();
            this.TV_INTERCONSULTA_SOLICITUD = new HashSet<TV_INTERCONSULTA_SOLICITUD>();
        }
    
        public short ID_CENTRO { get; set; }
        public Nullable<short> ID_TIPO_CENTRO { get; set; }
        public Nullable<short> ID_ENTIDAD { get; set; }
        public Nullable<short> ID_MUNICIPIO { get; set; }
        public string DESCR { get; set; }
        public string CALLE { get; set; }
        public Nullable<int> NUM_EXT { get; set; }
        public string NUM_INT { get; set; }
        public string COLONIA { get; set; }
        public Nullable<int> CP { get; set; }
        public Nullable<long> TELEFONO { get; set; }
        public Nullable<long> FAX { get; set; }
        public string DIRECTOR { get; set; }
        public Nullable<int> ID_EMISOR { get; set; }
        public Nullable<int> CONS_ANUAL { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<ABOGADO_DOCUMENTO> ABOGADO_DOCUMENTO { get; set; }
        public virtual ICollection<ALMACEN> ALMACEN { get; set; }
        public virtual ICollection<CENTRO_DEPARTAMENTO> CENTRO_DEPARTAMENTO { get; set; }
        public virtual EMISOR EMISOR { get; set; }
        public virtual ICollection<GRUPO_PARTICIPANTE> GRUPO_PARTICIPANTE { get; set; }
        public virtual ICollection<PERSONA_NIP> PERSONA_NIP { get; set; }
        public virtual ICollection<PROGRAMA> PROGRAMA { get; set; }
        public virtual MUNICIPIO MUNICIPIO { get; set; }
        public virtual ICollection<EDIFICIO> EDIFICIO { get; set; }
        public virtual ICollection<CATALOGO_EQUIPOS> CATALOGO_EQUIPOS { get; set; }
        public virtual ICollection<VISITA_APELLIDO> VISITA_APELLIDO { get; set; }
        public virtual ICollection<EXCARCELACION_TRANSITO> EXCARCELACION_TRANSITO { get; set; }
        public virtual ICollection<EVENTO> EVENTO { get; set; }
        public virtual ICollection<EVENTO> EVENTO1 { get; set; }
        public virtual ICollection<ADUANA> ADUANA { get; set; }
        public virtual ICollection<MENSAJE> MENSAJE { get; set; }
        public virtual ICollection<PFF_ACTA_CONSEJO_TECNICO> PFF_ACTA_CONSEJO_TECNICO { get; set; }
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
        public virtual ICollection<PROCESO_USUARIO> PROCESO_USUARIO { get; set; }
        public virtual ICollection<USUARIO_ROL> USUARIO_ROL { get; set; }
        public virtual ICollection<PERSONA_EXTERNO> PERSONA_EXTERNO { get; set; }
        public virtual ICollection<VISITA_EXTERNA> VISITA_EXTERNA { get; set; }
        public virtual ICollection<CAMA_HOSPITAL> CAMA_HOSPITAL { get; set; }
        public virtual ICollection<ATENCION_SOLICITUD> ATENCION_SOLICITUD { get; set; }
        public virtual ICollection<SOL_INTERCONSULTA_INTERNA> SOL_INTERCONSULTA_INTERNA { get; set; }
        public virtual ICollection<NOTIFICACION_TS> NOTIFICACION_TS { get; set; }
        public virtual ICollection<ESPECIALISTA> ESPECIALISTA { get; set; }
        public virtual ICollection<INGRESO> INGRESO { get; set; }
        public virtual ICollection<INGRESO> INGRESO1 { get; set; }
        public virtual ICollection<IMPUTADO> IMPUTADO { get; set; }
        public virtual ICollection<TRASLADO> TRASLADO { get; set; }
        public virtual ICollection<TRASLADO> TRASLADO1 { get; set; }
        public virtual ICollection<TRASLADO> TRASLADO2 { get; set; }
        public virtual ICollection<INCIDENCIAS_CATETER> INCIDENCIAS_CATETER { get; set; }
        public virtual ICollection<INCIDENCIAS_SONDA_GAS> INCIDENCIAS_SONDA_GAS { get; set; }
        public virtual ICollection<TV_CANALIZACION> TV_CANALIZACION { get; set; }
        public virtual ICollection<TV_CITA_MEDICA> TV_CITA_MEDICA { get; set; }
        public virtual ICollection<TV_SOL_INTERCONSULTA_INTERNA> TV_SOL_INTERCONSULTA_INTERNA { get; set; }
        public virtual ICollection<TV_INTERCONSULTA_SOLICITUD> TV_INTERCONSULTA_SOLICITUD { get; set; }
    }
}
