//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTRO_DEPARTAMENTO
    {
        public CENTRO_DEPARTAMENTO()
        {
            this.GRUPO = new HashSet<GRUPO>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_DEPARTAMENTO { get; set; }
        public Nullable<int> ID_RESPONSABLE { get; set; }
    
        public virtual CENTRO CENTRO { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        public virtual ICollection<GRUPO> GRUPO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
