//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECOMISO_OBJETO
    {
        public DECOMISO_OBJETO()
        {
            this.DECOMISO_IMAGEN = new HashSet<DECOMISO_IMAGEN>();
        }
    
        public int ID_DECOMISO { get; set; }
        public short ID_OBJETO_TIPO { get; set; }
        public short ID_CONSEC { get; set; }
        public string DESCR { get; set; }
        public Nullable<short> CANTIDAD { get; set; }
        public string COMENTARIO { get; set; }
        public string SERIE { get; set; }
        public Nullable<short> ID_TIPO_DROGA { get; set; }
        public Nullable<short> ID_UNIDAD_MEDIDA { get; set; }
        public Nullable<short> DOSIS { get; set; }
        public Nullable<short> ENVOLTORIOS { get; set; }
        public Nullable<short> ID_COMPANIA { get; set; }
        public string TELEFONO { get; set; }
        public string IMEI { get; set; }
        public string SIM_SERIE { get; set; }
        public string CAPACIDAD { get; set; }
        public Nullable<short> ID_MODELO { get; set; }
        public Nullable<short> ID_FABRICANTE { get; set; }
    
        public virtual ICollection<DECOMISO_IMAGEN> DECOMISO_IMAGEN { get; set; }
        public virtual DECOMISO_MODELO DECOMISO_MODELO { get; set; }
        public virtual DROGA DROGA { get; set; }
        public virtual DECOMISO DECOMISO { get; set; }
        public virtual DROGA_UNIDAD_MEDIDA DROGA_UNIDAD_MEDIDA { get; set; }
        public virtual COMPANIA COMPANIA { get; set; }
        public virtual OBJETO_TIPO OBJETO_TIPO { get; set; }
    }
}
