//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECOMISO_FABRICANTE
    {
        public DECOMISO_FABRICANTE()
        {
            this.DECOMISO_MODELO = new HashSet<DECOMISO_MODELO>();
        }
    
        public short ID_FABRICANTE { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<short> ID_OBJETO_TIPO { get; set; }
    
        public virtual ICollection<DECOMISO_MODELO> DECOMISO_MODELO { get; set; }
        public virtual OBJETO_TIPO OBJETO_TIPO { get; set; }
    }
}
