//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELITO_TITULO
    {
        public DELITO_TITULO()
        {
            this.DELITO_GRUPO = new HashSet<DELITO_GRUPO>();
        }
    
        public string ID_FUERO { get; set; }
        public short ID_TITULO { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<DELITO_GRUPO> DELITO_GRUPO { get; set; }
        public virtual FUERO FUERO { get; set; }
    }
}
