//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTO_ACCESO
    {
        public short ID_DEPARTAMENTO { get; set; }
        public string ID_USUARIO { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
    }
}
