//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DROGA_UNIDAD_MEDIDA
    {
        public DROGA_UNIDAD_MEDIDA()
        {
            this.DECOMISO_OBJETO = new HashSet<DECOMISO_OBJETO>();
        }
    
        public short ID_UNIDAD_MEDIDA { get; set; }
        public string DESCR { get; set; }
        public string ABREVIATURA { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<DECOMISO_OBJETO> DECOMISO_OBJETO { get; set; }
    }
}
