//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMI
    {
        public EMI()
        {
            this.EMI_ACTIVIDAD = new HashSet<EMI_ACTIVIDAD>();
            this.EMI_ANTECEDENTE_FAMILIAR_DROGA = new HashSet<EMI_ANTECEDENTE_FAMILIAR_DROGA>();
            this.EMI_GRUPO_FAMILIAR = new HashSet<EMI_GRUPO_FAMILIAR>();
            this.EMI_INGRESO_ANTERIOR = new HashSet<EMI_INGRESO_ANTERIOR>();
            this.EMI_SANCION_DISCIPLINARIA = new HashSet<EMI_SANCION_DISCIPLINARIA>();
            this.EMI_SENAS_PARTICULARES = new HashSet<EMI_SENAS_PARTICULARES>();
            this.EMI_ULTIMOS_EMPLEOS = new HashSet<EMI_ULTIMOS_EMPLEOS>();
            this.EMI_USO_DROGA = new HashSet<EMI_USO_DROGA>();
            this.EMI_ANTECEDENTE_FAM_CON_DEL = new HashSet<EMI_ANTECEDENTE_FAM_CON_DEL>();
        }
    
        public int ID_EMI { get; set; }
        public short ID_EMI_CONS { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<System.DateTime> FEC_CAPTURA { get; set; }
    
        public virtual ICollection<EMI_ACTIVIDAD> EMI_ACTIVIDAD { get; set; }
        public virtual ICollection<EMI_ANTECEDENTE_FAMILIAR_DROGA> EMI_ANTECEDENTE_FAMILIAR_DROGA { get; set; }
        public virtual EMI_CLAS_CRIMINOLOGICA EMI_CLAS_CRIMINOLOGICA { get; set; }
        public virtual EMI_ENFERMEDAD EMI_ENFERMEDAD { get; set; }
        public virtual EMI_FACTOR_CRIMINODIAGNOSTICO EMI_FACTOR_CRIMINODIAGNOSTICO { get; set; }
        public virtual EMI_FACTORES_SOCIO_FAMILIARES EMI_FACTORES_SOCIO_FAMILIARES { get; set; }
        public virtual EMI_FICHA_IDENTIFICACION EMI_FICHA_IDENTIFICACION { get; set; }
        public virtual ICollection<EMI_GRUPO_FAMILIAR> EMI_GRUPO_FAMILIAR { get; set; }
        public virtual EMI_HPS EMI_HPS { get; set; }
        public virtual ICollection<EMI_INGRESO_ANTERIOR> EMI_INGRESO_ANTERIOR { get; set; }
        public virtual EMI_INGRESO EMI_INGRESO { get; set; }
        public virtual ICollection<EMI_SANCION_DISCIPLINARIA> EMI_SANCION_DISCIPLINARIA { get; set; }
        public virtual ICollection<EMI_SENAS_PARTICULARES> EMI_SENAS_PARTICULARES { get; set; }
        public virtual EMI_SITUACION_JURIDICA EMI_SITUACION_JURIDICA { get; set; }
        public virtual EMI_TATUAJE EMI_TATUAJE { get; set; }
        public virtual ICollection<EMI_ULTIMOS_EMPLEOS> EMI_ULTIMOS_EMPLEOS { get; set; }
        public virtual ICollection<EMI_USO_DROGA> EMI_USO_DROGA { get; set; }
        public virtual ICollection<EMI_ANTECEDENTE_FAM_CON_DEL> EMI_ANTECEDENTE_FAM_CON_DEL { get; set; }
        public virtual EMI_IMPUTADO EMI_IMPUTADO { get; set; }
    }
}
