//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMI_GRUPO_FAMILIAR
    {
        public int ID_EMI { get; set; }
        public short ID_EMI_CONS { get; set; }
        public short ID_CONS { get; set; }
        public string NOMBRE { get; set; }
        public string PATERNO { get; set; }
        public string MATERNO { get; set; }
        public string DOMICILIO { get; set; }
        public Nullable<short> EDAD { get; set; }
        public string VIVE_C_EL { get; set; }
        public Nullable<short> ID_OCUPACION { get; set; }
        public Nullable<short> ID_RELACION { get; set; }
        public Nullable<short> ID_ESTADO_CIVIL { get; set; }
        public Nullable<short> GRUPO { get; set; }
        public Nullable<short> ID_CENTRO { get; set; }
        public Nullable<short> ID_ANIO { get; set; }
        public Nullable<int> ID_IMPUTADO { get; set; }
        public Nullable<short> ID_INGRESO { get; set; }
        public Nullable<short> ID_VISITA { get; set; }
        public Nullable<System.DateTime> NACIMIENTO_FEC { get; set; }
    
        public virtual ESTADO_CIVIL ESTADO_CIVIL { get; set; }
        public virtual OCUPACION OCUPACION { get; set; }
        public virtual EMI EMI { get; set; }
        public virtual TIPO_REFERENCIA TIPO_REFERENCIA { get; set; }
    }
}
