//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMI_ENFERMEDAD
    {
        public int ID_EMI { get; set; }
        public short ID_EMI_CONS { get; set; }
        public string DESCR_ENFERMEDAD { get; set; }
        public string DISCAPACIDAD { get; set; }
        public Nullable<short> ID_TIPO_DISCAPACIDAD { get; set; }
        public string DESCR_DISCAPACIDAD { get; set; }
        public string ENFERMO_MENTAL { get; set; }
        public string DESCR_ENFERMO_MENTAL { get; set; }
        public string VIH_HEPATITIS { get; set; }
        public string EN_TRATAMIENTO_FARMACO { get; set; }
        public string DIAGNOSTICO_FORMAL { get; set; }
        public string APFISICA_INTEGRO { get; set; }
        public string APFISICA_LIMPIO { get; set; }
        public string APFISICA_CONFORMADO { get; set; }
        public string APFISICA_ALINADO { get; set; }
    
        public virtual EMI EMI { get; set; }
        public virtual TIPO_DISCAPACIDAD TIPO_DISCAPACIDAD { get; set; }
    }
}
