//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMI_ACTIVIDAD
    {
        public int ID_EMI { get; set; }
        public short ID_EMI_CONS { get; set; }
        public short ID_CONSEC { get; set; }
        public short ID_EMI_ACTIVIDAD { get; set; }
        public Nullable<short> ANO_ACTIVIDADES { get; set; }
        public string DESCRIPCION_ACTIVIDADES { get; set; }
        public string DURACION_ACTIVIDADES { get; set; }
        public Nullable<short> ESTATUS_ACTIVIDADES { get; set; }
        public Nullable<short> PROGRAMA_TERMINADO { get; set; }
    
        public virtual EMI_TIPO_ACTIVIDAD EMI_TIPO_ACTIVIDAD { get; set; }
        public virtual EMI_ESTATUS_PROGRAMA EMI_ESTATUS_PROGRAMA { get; set; }
        public virtual EMI EMI { get; set; }
    }
}
