//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMI_FACTOR_NIVEL
    {
        public EMI_FACTOR_NIVEL()
        {
            this.EMI_FACTOR_CRIMINODIAGNOSTICO = new HashSet<EMI_FACTOR_CRIMINODIAGNOSTICO>();
            this.EMI_FACTOR_CRIMINODIAGNOSTICO1 = new HashSet<EMI_FACTOR_CRIMINODIAGNOSTICO>();
            this.EMI_FACTOR_CRIMINODIAGNOSTICO2 = new HashSet<EMI_FACTOR_CRIMINODIAGNOSTICO>();
            this.EMI_FACTOR_CRIMINODIAGNOSTICO3 = new HashSet<EMI_FACTOR_CRIMINODIAGNOSTICO>();
            this.EMI_FACTOR_CRIMINODIAGNOSTICO4 = new HashSet<EMI_FACTOR_CRIMINODIAGNOSTICO>();
            this.EMI_FACTOR_CRIMINODIAGNOSTICO5 = new HashSet<EMI_FACTOR_CRIMINODIAGNOSTICO>();
            this.EMI_FACTOR_CRIMINODIAGNOSTICO6 = new HashSet<EMI_FACTOR_CRIMINODIAGNOSTICO>();
            this.EMI_FACTOR_CRIMINODIAGNOSTICO7 = new HashSet<EMI_FACTOR_CRIMINODIAGNOSTICO>();
            this.EMI_FACTOR_CRIMINODIAGNOSTICO8 = new HashSet<EMI_FACTOR_CRIMINODIAGNOSTICO>();
            this.EMI_FACTOR_CRIMINODIAGNOSTICO9 = new HashSet<EMI_FACTOR_CRIMINODIAGNOSTICO>();
        }
    
        public short ID_NIVEL { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<EMI_FACTOR_CRIMINODIAGNOSTICO> EMI_FACTOR_CRIMINODIAGNOSTICO { get; set; }
        public virtual ICollection<EMI_FACTOR_CRIMINODIAGNOSTICO> EMI_FACTOR_CRIMINODIAGNOSTICO1 { get; set; }
        public virtual ICollection<EMI_FACTOR_CRIMINODIAGNOSTICO> EMI_FACTOR_CRIMINODIAGNOSTICO2 { get; set; }
        public virtual ICollection<EMI_FACTOR_CRIMINODIAGNOSTICO> EMI_FACTOR_CRIMINODIAGNOSTICO3 { get; set; }
        public virtual ICollection<EMI_FACTOR_CRIMINODIAGNOSTICO> EMI_FACTOR_CRIMINODIAGNOSTICO4 { get; set; }
        public virtual ICollection<EMI_FACTOR_CRIMINODIAGNOSTICO> EMI_FACTOR_CRIMINODIAGNOSTICO5 { get; set; }
        public virtual ICollection<EMI_FACTOR_CRIMINODIAGNOSTICO> EMI_FACTOR_CRIMINODIAGNOSTICO6 { get; set; }
        public virtual ICollection<EMI_FACTOR_CRIMINODIAGNOSTICO> EMI_FACTOR_CRIMINODIAGNOSTICO7 { get; set; }
        public virtual ICollection<EMI_FACTOR_CRIMINODIAGNOSTICO> EMI_FACTOR_CRIMINODIAGNOSTICO8 { get; set; }
        public virtual ICollection<EMI_FACTOR_CRIMINODIAGNOSTICO> EMI_FACTOR_CRIMINODIAGNOSTICO9 { get; set; }
    }
}
