//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMI_FACTOR_CRIMINODIAGNOSTICO
    {
        public int ID_EMI { get; set; }
        public short ID_EMI_CONS { get; set; }
        public short EGOCENTRISMO { get; set; }
        public short AGRESIVIDAD { get; set; }
        public short INDIFERENCIA_AFECTIVA { get; set; }
        public short LABILIDAD_AFECTIVA { get; set; }
        public short ADAPTABILIDAD_SOCIAL { get; set; }
        public short LIDERAZGO { get; set; }
        public short CAPACIDAD_CRIMINAL { get; set; }
        public short INDICE_ESTADO_PELIGROSO { get; set; }
        public short PRONOSTICO_INTRA_INST { get; set; }
        public short UBICACION_CLASIF_CRIM { get; set; }
        public Nullable<short> TOLERANCIA_A_LA_FRUSTRACION { get; set; }
        public Nullable<short> CONTROL_DE_IMPULSOS { get; set; }
        public string DICTAMEN { get; set; }
    
        public virtual EMI_FACTOR_RESULTADO EMI_FACTOR_RESULTADO { get; set; }
        public virtual EMI_FACTOR_UBICACION EMI_FACTOR_UBICACION { get; set; }
        public virtual EMI_FACTOR_NIVEL EMI_FACTOR_NIVEL { get; set; }
        public virtual EMI_FACTOR_NIVEL EMI_FACTOR_NIVEL1 { get; set; }
        public virtual EMI_FACTOR_NIVEL EMI_FACTOR_NIVEL2 { get; set; }
        public virtual EMI_FACTOR_NIVEL EMI_FACTOR_NIVEL3 { get; set; }
        public virtual EMI_FACTOR_NIVEL EMI_FACTOR_NIVEL4 { get; set; }
        public virtual EMI_FACTOR_NIVEL EMI_FACTOR_NIVEL5 { get; set; }
        public virtual EMI_FACTOR_NIVEL EMI_FACTOR_NIVEL6 { get; set; }
        public virtual EMI_FACTOR_NIVEL EMI_FACTOR_NIVEL7 { get; set; }
        public virtual EMI_FACTOR_NIVEL EMI_FACTOR_NIVEL8 { get; set; }
        public virtual EMI_FACTOR_NIVEL EMI_FACTOR_NIVEL9 { get; set; }
        public virtual EMI EMI { get; set; }
    }
}
