//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMI_INGRESO_ANTERIOR
    {
        public int ID_EMI { get; set; }
        public short ID_EMI_CONS { get; set; }
        public short ID_TIPO { get; set; }
        public short ID_CONSEC { get; set; }
        public Nullable<int> ID_EMISOR { get; set; }
        public string PERIODO_RECLUSION { get; set; }
        public string SANCIONES { get; set; }
        public string ID_FUERO { get; set; }
        public Nullable<long> ID_DELITO { get; set; }
        public Nullable<short> ID_CENTRO { get; set; }
        public Nullable<short> ID_ANIO { get; set; }
        public Nullable<decimal> ID_IMPUTADO { get; set; }
        public Nullable<short> ID_INGRESO { get; set; }
        public string DELITO { get; set; }
    
        public virtual EMISOR EMISOR { get; set; }
        public virtual DELITO DELITO1 { get; set; }
        public virtual EMI EMI { get; set; }
    }
}
