//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public EMPLEADO()
        {
            this.USUARIO = new HashSet<USUARIO>();
            this.MEDIDA_DOCUMENTO = new HashSet<MEDIDA_DOCUMENTO>();
            this.MEDIDA_PRESENTACION = new HashSet<MEDIDA_PRESENTACION>();
            this.HOSPITALIZACION = new HashSet<HOSPITALIZACION>();
            this.HOSPITALIZACION1 = new HashSet<HOSPITALIZACION>();
            this.NOTA_DEFUNCION = new HashSet<NOTA_DEFUNCION>();
        }
    
        public int ID_EMPLEADO { get; set; }
        public Nullable<short> ID_TIPO_EMPLEADO { get; set; }
        public Nullable<short> ID_CENTRO { get; set; }
        public string NUMERO_EMPLEADO { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
        public string OBSERV { get; set; }
        public string CEDULA { get; set; }
        public Nullable<short> ID_DEPARTAMENTO { get; set; }
    
        public virtual CENTRO CENTRO { get; set; }
        public virtual TIPO_EMPLEADO TIPO_EMPLEADO { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual ICollection<MEDIDA_DOCUMENTO> MEDIDA_DOCUMENTO { get; set; }
        public virtual ICollection<MEDIDA_PRESENTACION> MEDIDA_PRESENTACION { get; set; }
        public virtual ICollection<HOSPITALIZACION> HOSPITALIZACION { get; set; }
        public virtual ICollection<HOSPITALIZACION> HOSPITALIZACION1 { get; set; }
        public virtual ICollection<NOTA_DEFUNCION> NOTA_DEFUNCION { get; set; }
    }
}
