//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDAD
    {
        public ENTIDAD()
        {
            this.IMPUTADO_PADRES = new HashSet<IMPUTADO_PADRES>();
            this.VISITA_AUTORIZADA = new HashSet<VISITA_AUTORIZADA>();
            this.MUNICIPIO = new HashSet<MUNICIPIO>();
            this.AGENCIA = new HashSet<AGENCIA>();
            this.EVENTO = new HashSet<EVENTO>();
            this.EVENTO1 = new HashSet<EVENTO>();
            this.CAUSA_PENAL = new HashSet<CAUSA_PENAL>();
            this.PERSONA = new HashSet<PERSONA>();
            this.PRS_VISITA_DOMICILIARIA = new HashSet<PRS_VISITA_DOMICILIARIA>();
        }
    
        public short ID_ENTIDAD { get; set; }
        public Nullable<short> ID_PAIS_NAC { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<IMPUTADO_PADRES> IMPUTADO_PADRES { get; set; }
        public virtual ICollection<VISITA_AUTORIZADA> VISITA_AUTORIZADA { get; set; }
        public virtual PAIS_NACIONALIDAD PAIS_NACIONALIDAD { get; set; }
        public virtual ICollection<MUNICIPIO> MUNICIPIO { get; set; }
        public virtual ICollection<AGENCIA> AGENCIA { get; set; }
        public virtual ICollection<EVENTO> EVENTO { get; set; }
        public virtual ICollection<EVENTO> EVENTO1 { get; set; }
        public virtual ICollection<CAUSA_PENAL> CAUSA_PENAL { get; set; }
        public virtual ICollection<PERSONA> PERSONA { get; set; }
        public virtual ICollection<PRS_VISITA_DOMICILIARIA> PRS_VISITA_DOMICILIARIA { get; set; }
    }
}
