//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO_AREA
    {
        public string IP { get; set; }
        public string MAC_ADDRESS { get; set; }
        public short ID_AREA { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
    
        public virtual AREA AREA { get; set; }
        public virtual CATALOGO_EQUIPOS CATALOGO_EQUIPOS { get; set; }
    }
}
