//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCOLARIDAD
    {
        public ESCOLARIDAD()
        {
            this.PRS_NUCLEO_FAMILIAR = new HashSet<PRS_NUCLEO_FAMILIAR>();
            this.PFF_TRABAJO_SOCIAL = new HashSet<PFF_TRABAJO_SOCIAL>();
            this.PFF_TRABAJO_SOCIAL1 = new HashSet<PFF_TRABAJO_SOCIAL>();
            this.PFF_ACTIVIDAD = new HashSet<PFF_ACTIVIDAD>();
            this.INGRESO = new HashSet<INGRESO>();
            this.PROCESO_LIBERTAD = new HashSet<PROCESO_LIBERTAD>();
        }
    
        public short ID_ESCOLARIDAD { get; set; }
        public string DESCR { get; set; }
        public Nullable<short> PM { get; set; }
        public Nullable<short> ID_VIEJO { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<PRS_NUCLEO_FAMILIAR> PRS_NUCLEO_FAMILIAR { get; set; }
        public virtual ICollection<PFF_TRABAJO_SOCIAL> PFF_TRABAJO_SOCIAL { get; set; }
        public virtual ICollection<PFF_TRABAJO_SOCIAL> PFF_TRABAJO_SOCIAL1 { get; set; }
        public virtual ICollection<PFF_ACTIVIDAD> PFF_ACTIVIDAD { get; set; }
        public virtual ICollection<INGRESO> INGRESO { get; set; }
        public virtual ICollection<PROCESO_LIBERTAD> PROCESO_LIBERTAD { get; set; }
    }
}
