//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        public EVENTO()
        {
            this.EVENTO_INGRESO = new HashSet<EVENTO_INGRESO>();
            this.EVENTO_INF_TECNICA = new HashSet<EVENTO_INF_TECNICA>();
            this.EVENTO_PROGRAMA = new HashSet<EVENTO_PROGRAMA>();
            this.EVENTO_PRESIDIUM = new HashSet<EVENTO_PRESIDIUM>();
        }
    
        public int ID_EVENTO { get; set; }
        public Nullable<short> ID_EVENTO_TIPO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<short> ID_CENTRO { get; set; }
        public Nullable<short> ID_ENTIDAD { get; set; }
        public Nullable<short> ID_MUNICIPIO { get; set; }
        public Nullable<short> ID_IMPACTO { get; set; }
        public Nullable<short> ID_VESTIMENTA { get; set; }
        public string LUGAR { get; set; }
        public Nullable<short> HOR_DURACION { get; set; }
        public Nullable<short> MIN_DURACION { get; set; }
        public Nullable<System.DateTime> HORA_INVITACION { get; set; }
        public Nullable<System.DateTime> HORA_ARRIBO { get; set; }
        public string TELEFONO { get; set; }
        public string PROMOVENTE { get; set; }
        public string PERFIL_ASISTENTES { get; set; }
        public string OBJETIVO { get; set; }
        public string COMITE { get; set; }
        public string OBSERV { get; set; }
        public string MAESTRO { get; set; }
        public string MEDIOS { get; set; }
        public string OBJETIVO_GENERAL { get; set; }
        public string LUGAR_DIRECCION { get; set; }
        public Nullable<short> LUGAR_ENTIDAD { get; set; }
        public Nullable<short> LUGAR_MUNICIPIO { get; set; }
        public Nullable<short> ID_ESTATUS { get; set; }
        public Nullable<System.DateTime> EVENTO_FEC { get; set; }
        public Nullable<short> CENTRO_REGISTRA { get; set; }
        public Nullable<int> ID_PERSONA_RESPONSABLE { get; set; }
        public Nullable<short> ID_AREA { get; set; }
        public Nullable<System.DateTime> HORA_FIN { get; set; }
    
        public virtual AREA AREA { get; set; }
        public virtual CENTRO CENTRO { get; set; }
        public virtual CENTRO CENTRO1 { get; set; }
        public virtual ENTIDAD ENTIDAD { get; set; }
        public virtual ENTIDAD ENTIDAD1 { get; set; }
        public virtual ICollection<EVENTO_INGRESO> EVENTO_INGRESO { get; set; }
        public virtual ICollection<EVENTO_INF_TECNICA> EVENTO_INF_TECNICA { get; set; }
        public virtual ICollection<EVENTO_PROGRAMA> EVENTO_PROGRAMA { get; set; }
        public virtual ICollection<EVENTO_PRESIDIUM> EVENTO_PRESIDIUM { get; set; }
        public virtual EVENTO_ESTATUS EVENTO_ESTATUS { get; set; }
        public virtual EVENTO_IMPACTO EVENTO_IMPACTO { get; set; }
        public virtual EVENTO_TIPO EVENTO_TIPO { get; set; }
        public virtual EVENTO_VESTIMENTA EVENTO_VESTIMENTA { get; set; }
        public virtual MUNICIPIO MUNICIPIO { get; set; }
        public virtual MUNICIPIO MUNICIPIO1 { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
