//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCARCELACION_TRANSITO_TDOCTO
    {
        public EXCARCELACION_TRANSITO_TDOCTO()
        {
            this.EXCARCELACION_TRANSITO_DOCTO = new HashSet<EXCARCELACION_TRANSITO_DOCTO>();
        }
    
        public short ID_TIPO_DOC { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<EXCARCELACION_TRANSITO_DOCTO> EXCARCELACION_TRANSITO_DOCTO { get; set; }
    }
}
