//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCARCELACION_TRANSITO_DOCTO
    {
        public int ID_CONSEC { get; set; }
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public Nullable<short> ID_TIPO_DOC { get; set; }
        public byte[] DOCUMENTO { get; set; }
    
        public virtual EXCARCELACION_TRANSITO EXCARCELACION_TRANSITO { get; set; }
        public virtual EXCARCELACION_TRANSITO_TDOCTO EXCARCELACION_TRANSITO_TDOCTO { get; set; }
    }
}
