//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCARCELACION_TRANSITO
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public int ID_CONSEC { get; set; }
        public Nullable<short> ID_CENTRO_UBICACION { get; set; }
        public Nullable<System.DateTime> ENTRADA_FEC { get; set; }
        public Nullable<System.DateTime> SALIDA_FEC { get; set; }
    
        public virtual CENTRO CENTRO { get; set; }
        public virtual EXCARCELACION_TRANSITO_DOCTO EXCARCELACION_TRANSITO_DOCTO { get; set; }
        public virtual EXCARCELACION EXCARCELACION { get; set; }
    }
}
