//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAMILIAR_RESPONSABLE
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public int ID_PERSONA { get; set; }
        public Nullable<short> ID_TIPO_REFERENCIA { get; set; }
    
        public virtual TIPO_REFERENCIA TIPO_REFERENCIA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual IMPUTADO IMPUTADO { get; set; }
    }
}
