//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUERO
    {
        public FUERO()
        {
            this.DELITO_TITULO = new HashSet<DELITO_TITULO>();
        }
    
        public string ID_FUERO { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<DELITO_TITULO> DELITO_TITULO { get; set; }
    }
}
