//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO_PARTICIPANTE
    {
        public GRUPO_PARTICIPANTE()
        {
            this.GRUPO_PARTICIPANTE_EMPALMADO = new HashSet<GRUPO_PARTICIPANTE_EMPALMADO>();
            this.NOTA_TECNICA = new HashSet<NOTA_TECNICA>();
            this.GRUPO_ASISTENCIA = new HashSet<GRUPO_ASISTENCIA>();
            this.GRUPO_PARTICIPANTE_CANCELADO = new HashSet<GRUPO_PARTICIPANTE_CANCELADO>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_TIPO_PROGRAMA { get; set; }
        public short ID_ACTIVIDAD { get; set; }
        public short ID_CONSEC { get; set; }
        public Nullable<short> ID_GRUPO { get; set; }
        public Nullable<short> ING_ID_CENTRO { get; set; }
        public Nullable<short> ING_ID_ANIO { get; set; }
        public Nullable<int> ING_ID_IMPUTADO { get; set; }
        public Nullable<short> ING_ID_INGRESO { get; set; }
        public Nullable<System.DateTime> FEC_REGISTRO { get; set; }
        public Nullable<short> ESTATUS { get; set; }
        public Nullable<short> EJE { get; set; }
    
        public virtual ICollection<GRUPO_PARTICIPANTE_EMPALMADO> GRUPO_PARTICIPANTE_EMPALMADO { get; set; }
        public virtual ICollection<NOTA_TECNICA> NOTA_TECNICA { get; set; }
        public virtual GRUPO_PARTICIPANTE_ESTATUS GRUPO_PARTICIPANTE_ESTATUS { get; set; }
        public virtual EJE EJE1 { get; set; }
        public virtual CENTRO CENTRO { get; set; }
        public virtual ICollection<GRUPO_ASISTENCIA> GRUPO_ASISTENCIA { get; set; }
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
        public virtual ICollection<GRUPO_PARTICIPANTE_CANCELADO> GRUPO_PARTICIPANTE_CANCELADO { get; set; }
        public virtual GRUPO GRUPO { get; set; }
        public virtual INGRESO INGRESO { get; set; }
    }
}
