//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO_HORARIO
    {
        public GRUPO_HORARIO()
        {
            this.GRUPO_ASISTENCIA = new HashSet<GRUPO_ASISTENCIA>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_TIPO_PROGRAMA { get; set; }
        public short ID_ACTIVIDAD { get; set; }
        public short ID_GRUPO { get; set; }
        public short ID_GRUPO_HORARIO { get; set; }
        public Nullable<short> ID_AREA { get; set; }
        public Nullable<System.DateTime> HORA_INICIO { get; set; }
        public Nullable<System.DateTime> HORA_TERMINO { get; set; }
        public Nullable<short> ESTATUS { get; set; }
    
        public virtual AREA AREA { get; set; }
        public virtual GRUPO GRUPO { get; set; }
        public virtual ICollection<GRUPO_ASISTENCIA> GRUPO_ASISTENCIA { get; set; }
        public virtual GRUPO_HORARIO_ESTATUS GRUPO_HORARIO_ESTATUS { get; set; }
    }
}
