//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICO_DOCUMENTOS
    {
        public long ID_HISTORICO_DOC { get; set; }
        public short ID_UBI_CENTRO { get; set; }
        public Nullable<short> ID_CENTRO { get; set; }
        public Nullable<short> ID_ANIO { get; set; }
        public Nullable<int> ID_IMPUTADO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string DESCR { get; set; }
        public byte[] DOCUMENTO { get; set; }
        public Nullable<short> ID_DEPARTAMENTO { get; set; }
        public Nullable<short> ID_FORMATO { get; set; }
        public Nullable<short> ID_TIPO_DOCUMENTO { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        public virtual FORMATO_DOCUMENTO FORMATO_DOCUMENTO { get; set; }
        public virtual IMPUTADO IMPUTADO { get; set; }
        public virtual TIPO_DOCUMENTO_HISTORICO TIPO_DOCUMENTO_HISTORICO { get; set; }
    }
}
