//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIA_CLINICA_DENTAL_DOCUME
    {
        public decimal ID_HCDDOCTO { get; set; }
        public Nullable<short> ID_CENTRO { get; set; }
        public Nullable<short> ID_ANIO { get; set; }
        public Nullable<int> ID_IMPUTADO { get; set; }
        public Nullable<short> ID_INGRESO { get; set; }
        public Nullable<short> ID_CONSEC { get; set; }
        public Nullable<int> ID_DOCTO { get; set; }
        public byte[] DOCUMENTO { get; set; }
    
        public virtual HC_DOCUMENTO_TIPO HC_DOCUMENTO_TIPO { get; set; }
        public virtual HISTORIA_CLINICA_DENTAL HISTORIA_CLINICA_DENTAL { get; set; }
    }
}
