//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOJA_ENFERMERIA_CATETER
    {
        public HOJA_ENFERMERIA_CATETER()
        {
            this.HOJA_ENFERMERIA_CATETER1 = new HashSet<HOJA_ENFERMERIA_CATETER>();
            this.INCIDENCIAS_CATETER = new HashSet<INCIDENCIAS_CATETER>();
        }
    
        public decimal ID_HOJAENFCAT { get; set; }
        public short ID_CENTRO_UBI { get; set; }
        public Nullable<decimal> ID_HOJAENF { get; set; }
        public Nullable<decimal> ID_HOSPITA { get; set; }
        public Nullable<decimal> ID_CATETER { get; set; }
        public Nullable<decimal> ID_REGISTRO_INICIAL { get; set; }
        public string ID_USUARIO { get; set; }
        public Nullable<System.DateTime> INSTALACION_FEC { get; set; }
        public Nullable<System.DateTime> VENCIMIENTO_FEC { get; set; }
        public string DATOS_INFECCION { get; set; }
        public string MOTIVO_RETIRO { get; set; }
        public string RETIRO { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
        public Nullable<System.DateTime> FECHA_RETIRO { get; set; }
    
        public virtual CATETER_TIPO CATETER_TIPO { get; set; }
        public virtual HOJA_ENFERMERIA HOJA_ENFERMERIA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<HOJA_ENFERMERIA_CATETER> HOJA_ENFERMERIA_CATETER1 { get; set; }
        public virtual HOJA_ENFERMERIA_CATETER HOJA_ENFERMERIA_CATETER2 { get; set; }
        public virtual ICollection<INCIDENCIAS_CATETER> INCIDENCIAS_CATETER { get; set; }
    }
}
