//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOJA_ENFERMERIA_SOLUCION
    {
        public short ID_CENTRO_UBI { get; set; }
        public decimal ID_HOJAENFSOL { get; set; }
        public decimal ID_HOJAENF { get; set; }
        public decimal ID_HOSPITA { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<short> ID_PRESENTACION_MEDICAMENTO { get; set; }
        public Nullable<decimal> ID_LIQTURNO_INICIO { get; set; }
        public string TERMINO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
    
        public virtual LIQUIDO_TURNO LIQUIDO_TURNO { get; set; }
        public virtual PRESENTACION_MEDICAMENTO PRESENTACION_MEDICAMENTO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual HOJA_ENFERMERIA HOJA_ENFERMERIA { get; set; }
    }
}
