//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSPITAL
    {
        public HOSPITAL()
        {
            this.HOJA_REFERENCIA_MEDICA = new HashSet<HOJA_REFERENCIA_MEDICA>();
            this.TV_HOJA_REFERENCIA_MEDICA = new HashSet<TV_HOJA_REFERENCIA_MEDICA>();
        }
    
        public short ID_HOSPITAL { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<HOJA_REFERENCIA_MEDICA> HOJA_REFERENCIA_MEDICA { get; set; }
        public virtual ICollection<TV_HOJA_REFERENCIA_MEDICA> TV_HOJA_REFERENCIA_MEDICA { get; set; }
    }
}
