//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPUTADO_FORMATO
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public string ID_IMPUTADO_FORMATO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string ACTIVIDAD { get; set; }
        public Nullable<short> ID_TIPO_DOCUMENTO { get; set; }
        public string ULTIMA_MODIFICACION { get; set; }
    
        public virtual IMPUTADO_FORMATO_DETALLE IMPUTADO_FORMATO_DETALLE { get; set; }
        public virtual IMPUTADO IMPUTADO { get; set; }
    }
}
