//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPUTADO_PANDILLA
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_PANDILLA { get; set; }
        public Nullable<System.DateTime> FEC_ALTA { get; set; }
        public Nullable<System.DateTime> FEC_BAJA { get; set; }
        public string NOTAS { get; set; }
    
        public virtual PANDILLA PANDILLA { get; set; }
        public virtual IMPUTADO IMPUTADO { get; set; }
    }
}
