//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPUTADO_FORMATO_DETALLE
    {
        public short ID_CENTRO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_ANIO { get; set; }
        public string ID_IMPUTADO_FORMATO { get; set; }
        public string ID_IMPUTADO_FORMATO_DETALLE { get; set; }
        public string ID_DEPARTAMENTO { get; set; }
        public string ID_FORMATO { get; set; }
        public string IMPRESO { get; set; }
    
        public virtual FORMATO FORMATO { get; set; }
        public virtual IMPUTADO_FORMATO IMPUTADO_FORMATO { get; set; }
    }
}
