//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPUTADO_TIPO_DOCUMENTO
    {
        public IMPUTADO_TIPO_DOCUMENTO()
        {
            this.IMPUTADO_DOCUMENTO = new HashSet<IMPUTADO_DOCUMENTO>();
            this.AGENDA_LIBERTAD_DOCUMENTO = new HashSet<AGENDA_LIBERTAD_DOCUMENTO>();
        }
    
        public short ID_IM_TIPO_DOCTO { get; set; }
        public string DESCR { get; set; }
        public Nullable<short> ID_FORMATO { get; set; }
        public byte[] DOCUMENTO { get; set; }
    
        public virtual FORMATO_DOCUMENTO FORMATO_DOCUMENTO { get; set; }
        public virtual ICollection<IMPUTADO_DOCUMENTO> IMPUTADO_DOCUMENTO { get; set; }
        public virtual ICollection<AGENDA_LIBERTAD_DOCUMENTO> AGENDA_LIBERTAD_DOCUMENTO { get; set; }
    }
}
