//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENCIAS_SONDA_GAS
    {
        public int ID_INC_SONDA_GAS { get; set; }
        public short ID_CENTRO_UBI { get; set; }
        public decimal ID_SONDAGAS { get; set; }
        public Nullable<short> ID_ACMOTIVO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string ID_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
    
        public virtual ATENCION_CITA_IN_MOTIVO ATENCION_CITA_IN_MOTIVO { get; set; }
        public virtual CENTRO CENTRO { get; set; }
        public virtual HOJA_ENFERMERIA_SONDA_GASOGAS HOJA_ENFERMERIA_SONDA_GASOGAS { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
