//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRESO_PERTENENCIA
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public Nullable<System.DateTime> ING_FECHA { get; set; }
        public string ING_RESPONSABLE { get; set; }
        public string ING_PER_AUTORIZADAS { get; set; }
        public byte[] ING_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> EGR_FECHA { get; set; }
        public string EGR_RESPONSABLE { get; set; }
        public string EGR_PER_AUTORIZADAS { get; set; }
        public byte[] EGR_DOCUMENTO { get; set; }
    
        public virtual INGRESO INGRESO { get; set; }
    }
}
