//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERCONSULTA_NIVEL_PRIORIDAD
    {
        public INTERCONSULTA_NIVEL_PRIORIDAD()
        {
            this.CANALIZACION_ESPECIALIDAD = new HashSet<CANALIZACION_ESPECIALIDAD>();
            this.CANALIZACION_SERV_AUX = new HashSet<CANALIZACION_SERV_AUX>();
            this.TV_CANALIZACION_ESPECIALIDAD = new HashSet<TV_CANALIZACION_ESPECIALIDAD>();
            this.INTERCONSULTA_SOLICITUD = new HashSet<INTERCONSULTA_SOLICITUD>();
            this.TV_CANALIZACION_SERV_AUX = new HashSet<TV_CANALIZACION_SERV_AUX>();
            this.TV_INTERCONSULTA_SOLICITUD = new HashSet<TV_INTERCONSULTA_SOLICITUD>();
        }
    
        public short ID_INIVEL { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<CANALIZACION_ESPECIALIDAD> CANALIZACION_ESPECIALIDAD { get; set; }
        public virtual ICollection<CANALIZACION_SERV_AUX> CANALIZACION_SERV_AUX { get; set; }
        public virtual ICollection<TV_CANALIZACION_ESPECIALIDAD> TV_CANALIZACION_ESPECIALIDAD { get; set; }
        public virtual ICollection<INTERCONSULTA_SOLICITUD> INTERCONSULTA_SOLICITUD { get; set; }
        public virtual ICollection<TV_CANALIZACION_SERV_AUX> TV_CANALIZACION_SERV_AUX { get; set; }
        public virtual ICollection<TV_INTERCONSULTA_SOLICITUD> TV_INTERCONSULTA_SOLICITUD { get; set; }
    }
}
