//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERCONSULTA_SOLICITUD
    {
        public INTERCONSULTA_SOLICITUD()
        {
            this.EXCARCELACION_DESTINO = new HashSet<EXCARCELACION_DESTINO>();
            this.HOJA_REFERENCIA_MEDICA = new HashSet<HOJA_REFERENCIA_MEDICA>();
            this.SERVICIO_AUX_INTERCONSULTA = new HashSet<SERVICIO_AUX_INTERCONSULTA>();
            this.SOL_INTERCONSULTA_INTERNA = new HashSet<SOL_INTERCONSULTA_INTERNA>();
        }
    
        public int ID_INTERSOL { get; set; }
        public Nullable<int> ID_NOTA_MEDICA { get; set; }
        public Nullable<short> ID_INIVEL { get; set; }
        public Nullable<short> ID_INTER { get; set; }
        public Nullable<short> ID_INTERAT { get; set; }
        public Nullable<short> ID_ESPECIALIDAD { get; set; }
        public string ID_USUARIO { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
        public string OFICIO_EXC { get; set; }
        public short ID_CENTRO_UBI { get; set; }
    
        public virtual CANALIZACION CANALIZACION { get; set; }
        public virtual ESPECIALIDAD ESPECIALIDAD { get; set; }
        public virtual ICollection<EXCARCELACION_DESTINO> EXCARCELACION_DESTINO { get; set; }
        public virtual ICollection<HOJA_REFERENCIA_MEDICA> HOJA_REFERENCIA_MEDICA { get; set; }
        public virtual INTERCONSULTA_ATENCION_TIPO INTERCONSULTA_ATENCION_TIPO { get; set; }
        public virtual INTERCONSULTA_NIVEL_PRIORIDAD INTERCONSULTA_NIVEL_PRIORIDAD { get; set; }
        public virtual INTERCONSULTA_SOL_ESTATUS INTERCONSULTA_SOL_ESTATUS { get; set; }
        public virtual INTERCONSULTA_TIPO INTERCONSULTA_TIPO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<SERVICIO_AUX_INTERCONSULTA> SERVICIO_AUX_INTERCONSULTA { get; set; }
        public virtual ICollection<SOL_INTERCONSULTA_INTERNA> SOL_INTERCONSULTA_INTERNA { get; set; }
    }
}
