//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERCONSULTA_SOL_ESTATUS
    {
        public INTERCONSULTA_SOL_ESTATUS()
        {
            this.INTERCONSULTA_SOLICITUD = new HashSet<INTERCONSULTA_SOLICITUD>();
        }
    
        public string ID_IN_SOL_ESTATUS { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<INTERCONSULTA_SOLICITUD> INTERCONSULTA_SOLICITUD { get; set; }
    }
}
