//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class JUZGADO
    {
        public JUZGADO()
        {
            this.AMPARO_INDIRECTO = new HashSet<AMPARO_INDIRECTO>();
            this.AMPARO_INDIRECTO1 = new HashSet<AMPARO_INDIRECTO>();
            this.ABOGADO = new HashSet<ABOGADO>();
            this.CAUSA_PENAL = new HashSet<CAUSA_PENAL>();
            this.AMPARO_DIRECTO = new HashSet<AMPARO_DIRECTO>();
            this.AMPARO_DIRECTO1 = new HashSet<AMPARO_DIRECTO>();
            this.AMPARO_DIRECTO2 = new HashSet<AMPARO_DIRECTO>();
            this.AMPARO_DIRECTO3 = new HashSet<AMPARO_DIRECTO>();
            this.AMPARO_INCIDENTE = new HashSet<AMPARO_INCIDENTE>();
            this.RECURSO = new HashSet<RECURSO>();
            this.EXCARCELACION_DESTINO = new HashSet<EXCARCELACION_DESTINO>();
        }
    
        public short ID_JUZGADO { get; set; }
        public string ID_FUERO { get; set; }
        public Nullable<short> ID_PAIS { get; set; }
        public Nullable<short> ID_ENTIDAD { get; set; }
        public Nullable<short> ID_MUNICIPIO { get; set; }
        public Nullable<short> ID_TIPO_JUZGADO { get; set; }
        public string DESCR { get; set; }
        public string DOMICILIO { get; set; }
        public string TRIBUNAL { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<AMPARO_INDIRECTO> AMPARO_INDIRECTO { get; set; }
        public virtual ICollection<AMPARO_INDIRECTO> AMPARO_INDIRECTO1 { get; set; }
        public virtual MUNICIPIO MUNICIPIO { get; set; }
        public virtual PAIS_NACIONALIDAD PAIS_NACIONALIDAD { get; set; }
        public virtual TIPO_JUZGADO TIPO_JUZGADO { get; set; }
        public virtual ICollection<ABOGADO> ABOGADO { get; set; }
        public virtual ICollection<CAUSA_PENAL> CAUSA_PENAL { get; set; }
        public virtual ICollection<AMPARO_DIRECTO> AMPARO_DIRECTO { get; set; }
        public virtual ICollection<AMPARO_DIRECTO> AMPARO_DIRECTO1 { get; set; }
        public virtual ICollection<AMPARO_DIRECTO> AMPARO_DIRECTO2 { get; set; }
        public virtual ICollection<AMPARO_DIRECTO> AMPARO_DIRECTO3 { get; set; }
        public virtual ICollection<AMPARO_INCIDENTE> AMPARO_INCIDENTE { get; set; }
        public virtual ICollection<RECURSO> RECURSO { get; set; }
        public virtual ICollection<EXCARCELACION_DESTINO> EXCARCELACION_DESTINO { get; set; }
    }
}
