//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class LESION
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_LESION { get; set; }
        public int ID_ATENCION_MEDICA { get; set; }
        public Nullable<short> ID_REGION { get; set; }
        public string DESCR { get; set; }
        public short ID_CENTRO_UBI { get; set; }
    
        public virtual ANATOMIA_TOPOGRAFICA ANATOMIA_TOPOGRAFICA { get; set; }
        public virtual CERTIFICADO_MEDICO CERTIFICADO_MEDICO { get; set; }
    }
}
