//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBERACION_MOTIVO
    {
        public LIBERACION_MOTIVO()
        {
            this.LIBERACION = new HashSet<LIBERACION>();
        }
    
        public short ID_LIBERACION_MOTIVO { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<LIBERACION> LIBERACION { get; set; }
    }
}
