//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBERACION
    {
        public LIBERACION()
        {
            this.NOTA_EGRESO = new HashSet<NOTA_EGRESO>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_LIBERACION { get; set; }
        public System.DateTime LIBERACION_FEC { get; set; }
        public string LIBERACION_OFICIO { get; set; }
        public Nullable<short> ID_LIBERACION_AUTORIDAD { get; set; }
        public Nullable<short> ID_LIBERACION_MOTIVO { get; set; }
        public string LIBERADO { get; set; }
        public string INCIDENTE_BIOMETRICO { get; set; }
        public Nullable<short> ID_CAUSA_PENAL { get; set; }
        public Nullable<int> CP_FOLIO { get; set; }
        public Nullable<short> CP_ANIO { get; set; }
    
        public virtual LIBERACION_AUTORIDAD LIBERACION_AUTORIDAD { get; set; }
        public virtual LIBERACION_MOTIVO LIBERACION_MOTIVO { get; set; }
        public virtual CAUSA_PENAL CAUSA_PENAL { get; set; }
        public virtual INGRESO INGRESO { get; set; }
        public virtual ICollection<NOTA_EGRESO> NOTA_EGRESO { get; set; }
    }
}
