//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBERADO
    {
        public LIBERADO()
        {
            this.LIBERADO_SUSTANCIA = new HashSet<LIBERADO_SUSTANCIA>();
            this.LIBERADO_VIVE = new HashSet<LIBERADO_VIVE>();
            this.LIBERADO_MEDIDA_JUDICIAL = new HashSet<LIBERADO_MEDIDA_JUDICIAL>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public Nullable<short> ID_OCUPACION { get; set; }
        public string OCUPACION_LUGAR { get; set; }
        public string LUGAR_FRECUENTA { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
        public string PAM_NOMBRE { get; set; }
        public string PAM_DOMICILIO { get; set; }
        public string PAM_TEL_CELULAR { get; set; }
        public string PAM_TEL_FIJO { get; set; }
        public string PAM_TIEMPO_CONOCE { get; set; }
        public Nullable<short> PAM_ID_TIPO_REFERENCIA { get; set; }
        public string ACTITUD_GENERAL { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual ICollection<LIBERADO_SUSTANCIA> LIBERADO_SUSTANCIA { get; set; }
        public virtual ICollection<LIBERADO_VIVE> LIBERADO_VIVE { get; set; }
        public virtual OCUPACION OCUPACION { get; set; }
        public virtual TIPO_REFERENCIA TIPO_REFERENCIA { get; set; }
        public virtual ICollection<LIBERADO_MEDIDA_JUDICIAL> LIBERADO_MEDIDA_JUDICIAL { get; set; }
        public virtual IMPUTADO IMPUTADO { get; set; }
    }
}
