//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBERADO_MEDIDA_JUDICIAL
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_CONSEC { get; set; }
        public Nullable<System.DateTime> ENTREVISTA_FEC { get; set; }
        public Nullable<short> ENTREVISTA_EXP_ANIO { get; set; }
        public Nullable<int> ENTREVISTA_EXP_FOLIO { get; set; }
        public string ENTREVISTA_OFICIO { get; set; }
        public string ACT_EVA_RIESGOS { get; set; }
        public string ACT_EVA_ENTREVISTA { get; set; }
        public string ACT_EVA_OP_TECNICA { get; set; }
        public string ACT_EVA_OTRA { get; set; }
        public string RES_MC { get; set; }
        public string RES_SPP { get; set; }
        public string RES_PROV_P { get; set; }
        public string RES_NUC { get; set; }
        public string RES_CP { get; set; }
        public string DELITOS { get; set; }
        public string RECLASIFICADO { get; set; }
        public string MEDIDA_JUDICIAL { get; set; }
        public string PERIOCIDAD { get; set; }
        public Nullable<System.DateTime> APARTIR { get; set; }
        public string DURACION { get; set; }
        public string DEFENSOR_PUBLICO { get; set; }
        public string DEFENSOR_PRIVADO_NOM { get; set; }
        public string DEFENSOR_PRIVADO_TEL { get; set; }
        public Nullable<short> ID_PROCESO_LIBERTAD { get; set; }
    
        public virtual LIBERADO LIBERADO { get; set; }
        public virtual PROCESO_LIBERTAD PROCESO_LIBERTAD { get; set; }
    }
}
