//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIQUIDO
    {
        public LIQUIDO()
        {
            this.LIQUIDO_HOJA_CTRL_DETALLE = new HashSet<LIQUIDO_HOJA_CTRL_DETALLE>();
            this.HOJA_CONTROL_ENFERMERIA = new HashSet<HOJA_CONTROL_ENFERMERIA>();
        }
    
        public decimal ID_LIQ { get; set; }
        public string ID_LIQTIPO { get; set; }
        public string DESCR { get; set; }
        public Nullable<short> ID_LIQ_FORMATO { get; set; }
    
        public virtual ICollection<LIQUIDO_HOJA_CTRL_DETALLE> LIQUIDO_HOJA_CTRL_DETALLE { get; set; }
        public virtual LIQUIDO_FORMATO LIQUIDO_FORMATO { get; set; }
        public virtual LIQUIDO_TIPO LIQUIDO_TIPO { get; set; }
        public virtual ICollection<HOJA_CONTROL_ENFERMERIA> HOJA_CONTROL_ENFERMERIA { get; set; }
    }
}
