//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIQUIDO_FORMATO
    {
        public LIQUIDO_FORMATO()
        {
            this.LIQUIDO = new HashSet<LIQUIDO>();
        }
    
        public short ID_LIQ_FORMATO { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<LIQUIDO> LIQUIDO { get; set; }
    }
}
