//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIQUIDO_HORA
    {
        public LIQUIDO_HORA()
        {
            this.LIQUIDO_HOJA_CTRL = new HashSet<LIQUIDO_HOJA_CTRL>();
            this.HOJA_CONTROL_ENFERMERIA = new HashSet<HOJA_CONTROL_ENFERMERIA>();
        }
    
        public decimal ID_LIQHORA { get; set; }
        public Nullable<decimal> ID_LIQTURNO { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<LIQUIDO_HOJA_CTRL> LIQUIDO_HOJA_CTRL { get; set; }
        public virtual LIQUIDO_TURNO LIQUIDO_TURNO { get; set; }
        public virtual ICollection<HOJA_CONTROL_ENFERMERIA> HOJA_CONTROL_ENFERMERIA { get; set; }
    }
}
