//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCALIDAD
    {
        public short ID_ENTIDAD { get; set; }
        public short ID_MUNICIPIO { get; set; }
        public short ID_LOCALIDAD { get; set; }
        public string DESCR { get; set; }
        public string ZONA { get; set; }
    
        public virtual MUNICIPIO MUNICIPIO { get; set; }
    }
}
