//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDIDA_LUGAR
    {
        public MEDIDA_LUGAR()
        {
            this.MEDIDA_PRESENTACION = new HashSet<MEDIDA_PRESENTACION>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_PROCESO_LIBERTAD { get; set; }
        public short ID_MEDIDA_LIBERADO { get; set; }
        public short ID_MEDIDA_LUGAR { get; set; }
        public string CALLE { get; set; }
        public Nullable<short> NO_EXTERNO { get; set; }
        public string NO_INTERNO { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public Nullable<short> ID_GIRO { get; set; }
        public string COLONIA { get; set; }
        public Nullable<short> PAIS { get; set; }
        public Nullable<short> ID_ENTIDAD { get; set; }
        public Nullable<short> ID_MUNICIPIO { get; set; }
        public string PERTENECE { get; set; }
    
        public virtual GIRO GIRO { get; set; }
        public virtual MEDIDA_LIBERTAD MEDIDA_LIBERTAD { get; set; }
        public virtual MUNICIPIO MUNICIPIO { get; set; }
        public virtual ICollection<MEDIDA_PRESENTACION> MEDIDA_PRESENTACION { get; set; }
    }
}
