//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDIDA_PERSONA
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_PROCESO_LIBERTAD { get; set; }
        public short ID_MEDIDA_LIBERADO { get; set; }
        public short ID_PERSONA { get; set; }
        public Nullable<short> ID_PARTICUARIDAD { get; set; }
        public string PATERNO { get; set; }
        public string MATERNO { get; set; }
        public string NOMBRE { get; set; }
        public string ALIAS { get; set; }
        public Nullable<short> ID_TIPO_REFERENCIA { get; set; }
        public Nullable<short> ID_PARTICULARIDAD { get; set; }
    
        public virtual PARTICULARIDAD PARTICULARIDAD { get; set; }
        public virtual TIPO_REFERENCIA TIPO_REFERENCIA { get; set; }
        public virtual MEDIDA_LIBERTAD MEDIDA_LIBERTAD { get; set; }
    }
}
