//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDIDA
    {
        public MEDIDA()
        {
            this.MEDIDA_LIBERTAD = new HashSet<MEDIDA_LIBERTAD>();
        }
    
        public short ID_MEDIDA { get; set; }
        public short ID_TIPO_MEDIDA { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual MEDIDA_TIPO MEDIDA_TIPO { get; set; }
        public virtual ICollection<MEDIDA_LIBERTAD> MEDIDA_LIBERTAD { get; set; }
    }
}
