//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENSAJE_ROL
    {
        public short ID_MEN_TIPO { get; set; }
        public short ID_ROL { get; set; }
        public string DESCR { get; set; }
    
        public virtual MENSAJE_TIPO MENSAJE_TIPO { get; set; }
        public virtual SISTEMA_ROL SISTEMA_ROL { get; set; }
    }
}
