//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODALIDAD_DELITO
    {
        public MODALIDAD_DELITO()
        {
            this.CAUSA_PENAL_DELITO = new HashSet<CAUSA_PENAL_DELITO>();
            this.RECURSO_DELITO = new HashSet<RECURSO_DELITO>();
            this.SENTENCIA_DELITO = new HashSet<SENTENCIA_DELITO>();
        }
    
        public string ID_FUERO { get; set; }
        public long ID_DELITO { get; set; }
        public short ID_MODALIDAD { get; set; }
        public string DESCR { get; set; }
        public Nullable<short> PM { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<CAUSA_PENAL_DELITO> CAUSA_PENAL_DELITO { get; set; }
        public virtual DELITO DELITO { get; set; }
        public virtual ICollection<RECURSO_DELITO> RECURSO_DELITO { get; set; }
        public virtual ICollection<SENTENCIA_DELITO> SENTENCIA_DELITO { get; set; }
    }
}
