//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_EGRESO
    {
        public decimal ID_HOSPITA { get; set; }
        public short ID_CENTRO_UBI { get; set; }
        public Nullable<decimal> ID_MOEGMED { get; set; }
        public Nullable<int> ID_ATENCION_MEDICA { get; set; }
        public Nullable<int> ID_CONSEC { get; set; }
        public Nullable<short> ID_CENTRO { get; set; }
        public Nullable<short> ID_ANIO { get; set; }
        public Nullable<int> ID_IMPUTADO { get; set; }
        public Nullable<short> ID_INGRESO { get; set; }
        public Nullable<short> ID_LIBERACION { get; set; }
        public Nullable<decimal> DIAS_ESTANCIA { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public string USUARIO_REGISTRO { get; set; }
        public string RESUMEN_EVOLUCION { get; set; }
    
        public virtual HOSPITALIZACION HOSPITALIZACION { get; set; }
        public virtual LIBERACION LIBERACION { get; set; }
        public virtual MOTIVO_EGRESO_MEDICO MOTIVO_EGRESO_MEDICO { get; set; }
        public virtual NOTA_MEDICA NOTA_MEDICA { get; set; }
        public virtual EXCARCELACION EXCARCELACION { get; set; }
    }
}
