//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_MEDICA_ENFERMEDAD
    {
        public int ID_ATENCION_MEDICA { get; set; }
        public int ID_ENFERMEDAD { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
        public short ID_CENTRO_UBI { get; set; }
    
        public virtual ENFERMEDAD ENFERMEDAD { get; set; }
        public virtual NOTA_MEDICA NOTA_MEDICA { get; set; }
    }
}
