//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_POST_OPERATOR
    {
        public int ID_ATENCION_MEDICA { get; set; }
        public Nullable<int> ID_RESPONSABLE { get; set; }
        public string OPERACION_PLANEADA { get; set; }
        public string OPERACION_REALIZAD { get; set; }
        public string DIAGNOSTICO_POST_O { get; set; }
        public string DESCR_TECNICA_QUIR { get; set; }
        public string HALLASZGOS_TRANSOP { get; set; }
        public string REPORTE_GASAS_COMP { get; set; }
        public string INCIDENTES { get; set; }
        public string ACCIDENTES { get; set; }
        public string CUANTIFICACION_SAN { get; set; }
        public string RESULTADOS { get; set; }
        public string ESTADO_POST_QUIRUR { get; set; }
        public string PLAN_TRATAMIENTO_P { get; set; }
        public string ENVIO_EXAMEN_MACRO { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
        public short ID_CENTRO_UBI { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual ATENCION_MEDICA ATENCION_MEDICA { get; set; }
    }
}
