//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_MEDICA
    {
        public NOTA_MEDICA()
        {
            this.HOSPITALIZACION = new HashSet<HOSPITALIZACION>();
            this.NOTA_MEDICA_ENFERMEDAD = new HashSet<NOTA_MEDICA_ENFERMEDAD>();
            this.RECETA_MEDICA = new HashSet<RECETA_MEDICA>();
            this.RECETA_MEDICA_DETALLE = new HashSet<RECETA_MEDICA_DETALLE>();
            this.NOTA_MEDICA_DIETA = new HashSet<NOTA_MEDICA_DIETA>();
            this.NOTA_EGRESO = new HashSet<NOTA_EGRESO>();
        }
    
        public int ID_ATENCION_MEDICA { get; set; }
        public Nullable<int> ID_RESPONSABLE { get; set; }
        public string RESUMEN_INTERROGAT { get; set; }
        public string EXPLORACION_FISICA { get; set; }
        public string RESULTADO_SERV_AUX { get; set; }
        public string RESULTADO_SERV_TRA { get; set; }
        public string DIAGNOSTICO { get; set; }
        public string PLAN_ESTUDIO_TRATA { get; set; }
        public string FIRMO_CONFORMIDAD { get; set; }
        public Nullable<short> ID_PRONOSTICO { get; set; }
        public string OCUPA_INTERCONSULTA { get; set; }
        public string OCUPA_HOSPITALIZACION { get; set; }
        public short ID_CENTRO_UBI { get; set; }
    
        public virtual CANALIZACION CANALIZACION { get; set; }
        public virtual ICollection<HOSPITALIZACION> HOSPITALIZACION { get; set; }
        public virtual ICollection<NOTA_MEDICA_ENFERMEDAD> NOTA_MEDICA_ENFERMEDAD { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual PRONOSTICO PRONOSTICO { get; set; }
        public virtual ATENCION_MEDICA ATENCION_MEDICA { get; set; }
        public virtual NOTA_EVOLUCION NOTA_EVOLUCION { get; set; }
        public virtual ICollection<RECETA_MEDICA> RECETA_MEDICA { get; set; }
        public virtual ICollection<RECETA_MEDICA_DETALLE> RECETA_MEDICA_DETALLE { get; set; }
        public virtual ICollection<NOTA_MEDICA_DIETA> NOTA_MEDICA_DIETA { get; set; }
        public virtual ICollection<NOTA_EGRESO> NOTA_EGRESO { get; set; }
    }
}
