//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_REFERENCIA_TR
    {
        public int ID_ATENCION_MEDICA { get; set; }
        public Nullable<int> ID_MEDICO_RECIBE { get; set; }
        public string MOTIVO_ENVIO { get; set; }
        public string ESTABLECIMIENTO_EN { get; set; }
        public string ESTABLECIMIENTO_RE { get; set; }
        public string REGISTRO_FEC { get; set; }
        public short ID_CENTRO_UBI { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual ATENCION_MEDICA ATENCION_MEDICA { get; set; }
    }
}
