//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETO_TIPO
    {
        public OBJETO_TIPO()
        {
            this.COMPANIA = new HashSet<COMPANIA>();
            this.DECOMISO_FABRICANTE = new HashSet<DECOMISO_FABRICANTE>();
            this.DECOMISO_OBJETO = new HashSet<DECOMISO_OBJETO>();
            this.INGRESO_PERTENENCIA_DET = new HashSet<INGRESO_PERTENENCIA_DET>();
            this.PERSONA_PERTENENCIA = new HashSet<PERSONA_PERTENENCIA>();
        }
    
        public short ID_OBJETO_TIPO { get; set; }
        public string DESCR { get; set; }
        public Nullable<short> CONFIGURACION { get; set; }
        public string ESTATUS { get; set; }
        public string PERMITIDO { get; set; }
    
        public virtual ICollection<COMPANIA> COMPANIA { get; set; }
        public virtual ICollection<DECOMISO_FABRICANTE> DECOMISO_FABRICANTE { get; set; }
        public virtual ICollection<DECOMISO_OBJETO> DECOMISO_OBJETO { get; set; }
        public virtual ICollection<INGRESO_PERTENENCIA_DET> INGRESO_PERTENENCIA_DET { get; set; }
        public virtual ICollection<PERSONA_PERTENENCIA> PERSONA_PERTENENCIA { get; set; }
    }
}
