//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODONTOGRAMA_INICIAL
    {
        public decimal ID_CONSECUTIVO { get; set; }
        public Nullable<short> ID_POSICION { get; set; }
        public Nullable<short> ID_TIPO_ODO { get; set; }
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_CONSEC { get; set; }
        public Nullable<int> ID_ENFERMEDAD { get; set; }
        public Nullable<short> ID_NOMENCLATURA { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
        public Nullable<decimal> ID_SIMBOLO { get; set; }
    
        public virtual DENTAL_NOMENCLATURA DENTAL_NOMENCLATURA { get; set; }
        public virtual ENFERMEDAD ENFERMEDAD { get; set; }
        public virtual HISTORIA_CLINICA_DENTAL HISTORIA_CLINICA_DENTAL { get; set; }
        public virtual ODONTOGRAMA ODONTOGRAMA { get; set; }
        public virtual ODONTOGRAMA_TIPO ODONTOGRAMA_TIPO { get; set; }
        public virtual ODONTOGRAMA_SIMBOLOGIA ODONTOGRAMA_SIMBOLOGIA { get; set; }
    }
}
