//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODONTOGRAMA_SIMBOLOGIA
    {
        public ODONTOGRAMA_SIMBOLOGIA()
        {
            this.ODONTOGRAMA_INICIAL = new HashSet<ODONTOGRAMA_INICIAL>();
        }
    
        public decimal ID_SIMBOLO { get; set; }
        public Nullable<short> ID_NOMENCLATURA { get; set; }
        public Nullable<int> ID_ENFERMEDAD { get; set; }
        public byte[] IMAGEN { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual DENTAL_NOMENCLATURA DENTAL_NOMENCLATURA { get; set; }
        public virtual ENFERMEDAD ENFERMEDAD { get; set; }
        public virtual ICollection<ODONTOGRAMA_INICIAL> ODONTOGRAMA_INICIAL { get; set; }
    }
}
