//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATOLOGICO_CAT
    {
        public PATOLOGICO_CAT()
        {
            this.HISTORIA_CLINICA_PATOLOGICOS = new HashSet<HISTORIA_CLINICA_PATOLOGICOS>();
            this.SECTOR_CLASIFICACION = new HashSet<SECTOR_CLASIFICACION>();
        }
    
        public int ID_PATOLOGICO { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<short> PUEDE_CURARSE { get; set; }
    
        public virtual ICollection<HISTORIA_CLINICA_PATOLOGICOS> HISTORIA_CLINICA_PATOLOGICOS { get; set; }
        public virtual ICollection<SECTOR_CLASIFICACION> SECTOR_CLASIFICACION { get; set; }
    }
}
