//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA_PERTENENCIA
    {
        public int ID_ADUANA { get; set; }
        public int ID_PERSONA { get; set; }
        public short ID_CENTRO { get; set; }
        public int ID_CONSEC { get; set; }
        public short ID_PERT_SEC { get; set; }
        public short ID_OBJETO_TIPO { get; set; }
        public string INGRESA_OBJETO { get; set; }
        public string UBICACION { get; set; }
        public string AUTORIZA_INGRESO { get; set; }
    
        public virtual ADUANA ADUANA { get; set; }
        public virtual OBJETO_TIPO OBJETO_TIPO { get; set; }
    }
}
