//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONALIDAD_DETALLE
    {
        public PERSONALIDAD_DETALLE()
        {
            this.PERSONALIDAD_DETALLE_DIAS = new HashSet<PERSONALIDAD_DETALLE_DIAS>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_ESTUDIO { get; set; }
        public int ID_DETALLE { get; set; }
        public Nullable<short> ID_TIPO { get; set; }
        public Nullable<short> ID_ESTATUS { get; set; }
        public Nullable<System.DateTime> SOLICITUD_FEC { get; set; }
        public Nullable<System.DateTime> INICIO_FEC { get; set; }
        public Nullable<System.DateTime> TERMINO_FEC { get; set; }
        public byte[] ESTUDIO { get; set; }
        public string TIPO_MEDIA { get; set; }
        public string RESULTADO { get; set; }
        public Nullable<short> DIAS_BONIFICADOS { get; set; }
        public Nullable<short> ID_AREA { get; set; }
    
        public virtual AREA AREA { get; set; }
        public virtual PERSONALIDAD PERSONALIDAD { get; set; }
        public virtual PERSONALIDAD_TIPO_ESTUDIO PERSONALIDAD_TIPO_ESTUDIO { get; set; }
        public virtual PERSONALIDAD_ESTATUS PERSONALIDAD_ESTATUS { get; set; }
        public virtual ICollection<PERSONALIDAD_DETALLE_DIAS> PERSONALIDAD_DETALLE_DIAS { get; set; }
    }
}
