//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public PERSONA()
        {
            this.ADUANA = new HashSet<ADUANA>();
            this.ADUANA_ACOMPANANTE = new HashSet<ADUANA_ACOMPANANTE>();
            this.CENTRO_DEPARTAMENTO = new HashSet<CENTRO_DEPARTAMENTO>();
            this.CORRESPONDENCIA = new HashSet<CORRESPONDENCIA>();
            this.CORRESPONDENCIA1 = new HashSet<CORRESPONDENCIA>();
            this.DECOMISO_PERSONA = new HashSet<DECOMISO_PERSONA>();
            this.EVENTO = new HashSet<EVENTO>();
            this.FAMILIAR_RESPONSABLE = new HashSet<FAMILIAR_RESPONSABLE>();
            this.GRUPO = new HashSet<GRUPO>();
            this.HISTORIA_CLINICA = new HashSet<HISTORIA_CLINICA>();
            this.INGRESO_UBICACION = new HashSet<INGRESO_UBICACION>();
            this.PERSONA_NIP = new HashSet<PERSONA_NIP>();
            this.PERSONA_BIOMETRICO = new HashSet<PERSONA_BIOMETRICO>();
            this.TRASPASO = new HashSet<TRASPASO>();
            this.TRASPASO1 = new HashSet<TRASPASO>();
            this.TRASPASO2 = new HashSet<TRASPASO>();
            this.VISITA_AUTORIZADA = new HashSet<VISITA_AUTORIZADA>();
            this.NOTA_INTERCONSULTA = new HashSet<NOTA_INTERCONSULTA>();
            this.NOTA_MEDICA = new HashSet<NOTA_MEDICA>();
            this.NOTA_POST_OPERATOR = new HashSet<NOTA_POST_OPERATOR>();
            this.NOTA_PRE_ANESTECIC = new HashSet<NOTA_PRE_ANESTECIC>();
            this.NOTA_PRE_OPERATORI = new HashSet<NOTA_PRE_OPERATORI>();
            this.NOTA_REFERENCIA_TR = new HashSet<NOTA_REFERENCIA_TR>();
            this.NOTA_SIGNOS_VITALES = new HashSet<NOTA_SIGNOS_VITALES>();
            this.ATENCION_CITA = new HashSet<ATENCION_CITA>();
            this.ESPECIALISTA = new HashSet<ESPECIALISTA>();
        }
    
        public int ID_PERSONA { get; set; }
        public Nullable<short> ID_TIPO_PERSONA { get; set; }
        public string PATERNO { get; set; }
        public string MATERNO { get; set; }
        public string NOMBRE { get; set; }
        public string SEXO { get; set; }
        public string DOMICILIO_CALLE { get; set; }
        public Nullable<int> DOMICILIO_NUM_EXT { get; set; }
        public string DOMICILIO_NUM_INT { get; set; }
        public Nullable<int> ID_COLONIA { get; set; }
        public Nullable<short> ID_MUNICIPIO { get; set; }
        public Nullable<short> ID_ENTIDAD { get; set; }
        public Nullable<short> ID_PAIS { get; set; }
        public Nullable<int> DOMICILIO_CODIGO_POSTAL { get; set; }
        public string CURP { get; set; }
        public string RFC { get; set; }
        public Nullable<System.DateTime> FEC_NACIMIENTO { get; set; }
        public string LUGAR_NACIMIENTO { get; set; }
        public Nullable<short> NACIONALIDAD { get; set; }
        public Nullable<short> ESTADO_CIVIL { get; set; }
        public string TELEFONO { get; set; }
        public string TELEFONO_MOVIL { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public Nullable<short> ID_ETNIA { get; set; }
        public string IFE { get; set; }
        public Nullable<short> ID_TIPO_DISCAPACIDAD { get; set; }
        public Nullable<int> NORIGINAL { get; set; }
        public string CORIGINAL { get; set; }
        public string SPATERNO { get; set; }
        public string SMATERNO { get; set; }
        public string SNOMBRE { get; set; }
        public string NOTA_TECNICA { get; set; }
    
        public virtual ABOGADO ABOGADO { get; set; }
        public virtual ICollection<ADUANA> ADUANA { get; set; }
        public virtual ICollection<ADUANA_ACOMPANANTE> ADUANA_ACOMPANANTE { get; set; }
        public virtual ICollection<CENTRO_DEPARTAMENTO> CENTRO_DEPARTAMENTO { get; set; }
        public virtual COLONIA COLONIA { get; set; }
        public virtual ICollection<CORRESPONDENCIA> CORRESPONDENCIA { get; set; }
        public virtual ICollection<CORRESPONDENCIA> CORRESPONDENCIA1 { get; set; }
        public virtual ICollection<DECOMISO_PERSONA> DECOMISO_PERSONA { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ENTIDAD ENTIDAD { get; set; }
        public virtual ESTADO_CIVIL ESTADO_CIVIL1 { get; set; }
        public virtual ETNIA ETNIA { get; set; }
        public virtual ICollection<EVENTO> EVENTO { get; set; }
        public virtual ICollection<FAMILIAR_RESPONSABLE> FAMILIAR_RESPONSABLE { get; set; }
        public virtual ICollection<GRUPO> GRUPO { get; set; }
        public virtual ICollection<HISTORIA_CLINICA> HISTORIA_CLINICA { get; set; }
        public virtual ICollection<INGRESO_UBICACION> INGRESO_UBICACION { get; set; }
        public virtual MUNICIPIO MUNICIPIO { get; set; }
        public virtual PAIS_NACIONALIDAD PAIS_NACIONALIDAD { get; set; }
        public virtual PAIS_NACIONALIDAD PAIS_NACIONALIDAD1 { get; set; }
        public virtual ICollection<PERSONA_NIP> PERSONA_NIP { get; set; }
        public virtual ICollection<PERSONA_BIOMETRICO> PERSONA_BIOMETRICO { get; set; }
        public virtual TIPO_DISCAPACIDAD TIPO_DISCAPACIDAD { get; set; }
        public virtual TIPO_PERSONA TIPO_PERSONA { get; set; }
        public virtual ICollection<TRASPASO> TRASPASO { get; set; }
        public virtual ICollection<TRASPASO> TRASPASO1 { get; set; }
        public virtual ICollection<TRASPASO> TRASPASO2 { get; set; }
        public virtual ICollection<VISITA_AUTORIZADA> VISITA_AUTORIZADA { get; set; }
        public virtual VISITANTE VISITANTE { get; set; }
        public virtual PERSONA_EXTERNO PERSONA_EXTERNO { get; set; }
        public virtual ICollection<NOTA_INTERCONSULTA> NOTA_INTERCONSULTA { get; set; }
        public virtual ICollection<NOTA_MEDICA> NOTA_MEDICA { get; set; }
        public virtual ICollection<NOTA_POST_OPERATOR> NOTA_POST_OPERATOR { get; set; }
        public virtual ICollection<NOTA_PRE_ANESTECIC> NOTA_PRE_ANESTECIC { get; set; }
        public virtual ICollection<NOTA_PRE_OPERATORI> NOTA_PRE_OPERATORI { get; set; }
        public virtual ICollection<NOTA_REFERENCIA_TR> NOTA_REFERENCIA_TR { get; set; }
        public virtual ICollection<NOTA_SIGNOS_VITALES> NOTA_SIGNOS_VITALES { get; set; }
        public virtual ICollection<ATENCION_CITA> ATENCION_CITA { get; set; }
        public virtual ICollection<ESPECIALISTA> ESPECIALISTA { get; set; }
    }
}
