//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA_BIOMETRICO
    {
        public int ID_PERSONA { get; set; }
        public short ID_TIPO_BIOMETRICO { get; set; }
        public byte[] BIOMETRICO { get; set; }
        public Nullable<int> NORIGINAL { get; set; }
        public short ID_FORMATO { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual BIOMETRICO_TIPO BIOMETRICO_TIPO { get; set; }
    }
}
