//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFC_VIII_CAPACITACION
    {
        public PFC_VIII_CAPACITACION()
        {
            this.PFC_VIII_ACTIVIDAD_LABORAL = new HashSet<PFC_VIII_ACTIVIDAD_LABORAL>();
        }
    
        public short ID_CAPACITACION { get; set; }
        public string TIPO { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<PFC_VIII_ACTIVIDAD_LABORAL> PFC_VIII_ACTIVIDAD_LABORAL { get; set; }
    }
}
