//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFC_V_CRIMINODIAGNOSTICO
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_ESTUDIO { get; set; }
        public string P1_VERSION_DELITO { get; set; }
        public string P1_DROGADO { get; set; }
        public Nullable<short> P1_ALCOHOL { get; set; }
        public Nullable<short> P1_DROGRA_ILEGAL { get; set; }
        public Nullable<short> P1_OTRA { get; set; }
        public string P2_CRIMINOGENESIS { get; set; }
        public string P3_CONDUCTA_ANTISOCIAL { get; set; }
        public Nullable<short> P4_CLASIFICACION_CRIMINOLOGICA { get; set; }
        public string P5_INTIMIDACION { get; set; }
        public string P5_PORQUE { get; set; }
        public Nullable<short> P6_CAPACIDAD_CRIMINAL { get; set; }
        public Nullable<short> P6A_EGOCENTRICO { get; set; }
        public Nullable<short> P6B_LIABILIDAD_EFECTIVA { get; set; }
        public Nullable<short> P6C_AGRESIVIDAD { get; set; }
        public Nullable<short> P6D_INDIFERENCIA_AFECTIVA { get; set; }
        public Nullable<short> P7_ADAPTACION_SOCIAL { get; set; }
        public Nullable<short> P8_INDICE_PELIGROSIDAD { get; set; }
        public Nullable<short> P9_PRONOSTICO_REINCIDENCIA { get; set; }
        public Nullable<short> P10_DICTAMEN_REINSERCION { get; set; }
        public string P10_MOTIVACION_DICTAMEN { get; set; }
        public string P11_PROGRAMAS_REMITIRSE { get; set; }
        public string P12_TRATAMIENTO_EXTRAMUROS { get; set; }
        public string P12_CUAL { get; set; }
        public Nullable<System.DateTime> ESTUDIO_FEC { get; set; }
        public string COORDINADOR { get; set; }
        public string ELABORO { get; set; }
    
        public virtual PERSONALIDAD_FUERO_COMUN PERSONALIDAD_FUERO_COMUN { get; set; }
        public virtual PFC_V_CAPACIDAD PFC_V_CAPACIDAD { get; set; }
        public virtual PFC_V_CAPACIDAD PFC_V_CAPACIDAD1 { get; set; }
        public virtual PFC_V_CAPACIDAD PFC_V_CAPACIDAD2 { get; set; }
        public virtual PFC_V_CAPACIDAD PFC_V_CAPACIDAD3 { get; set; }
        public virtual PFC_V_CAPACIDAD PFC_V_CAPACIDAD4 { get; set; }
        public virtual PFC_V_CAPACIDAD PFC_V_CAPACIDAD5 { get; set; }
        public virtual PFC_V_CAPACIDAD PFC_V_CAPACIDAD6 { get; set; }
        public virtual PFC_V_CRIMINOLOGICA PFC_V_CRIMINOLOGICA { get; set; }
        public virtual PFC_V_PELIGROSIDAD PFC_V_PELIGROSIDAD { get; set; }
    }
}
