//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFC_VII_ESCOLARIDAD_ANTERIOR
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_ESTUDIO { get; set; }
        public short ID_GRADO { get; set; }
        public string CONCLUIDA { get; set; }
        public string RENDIMIENTO { get; set; }
        public string INTERES { get; set; }
        public string OBSERVACION { get; set; }
        public short ID_CONSEC { get; set; }
    
        public virtual EDUCACION_GRADO EDUCACION_GRADO { get; set; }
        public virtual PFC_VII_EDUCATIVO PFC_VII_EDUCATIVO { get; set; }
    }
}
