//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFC_IX_SEGURIDAD
    {
        public PFC_IX_SEGURIDAD()
        {
            this.PFC_IX_CORRECTIVO = new HashSet<PFC_IX_CORRECTIVO>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_ESTUDIO { get; set; }
        public string P1_CONDUCTA_CENTRO { get; set; }
        public string P2_CONDUCTA_AUTORIDAD { get; set; }
        public Nullable<short> P3_CONDUCTA_GENERAL { get; set; }
        public Nullable<short> P4_RELACION_COMPANEROS { get; set; }
        public string P5_CORRECTIVOS { get; set; }
        public string P6_OPINION_CONDUCTA { get; set; }
        public string P7_DICTAMEN { get; set; }
        public string P8_MOTIVACION { get; set; }
        public Nullable<System.DateTime> ESTUDIO_FEC { get; set; }
        public string COMANDANTE { get; set; }
        public string ELABORO { get; set; }
    
        public virtual PERSONALIDAD_FUERO_COMUN PERSONALIDAD_FUERO_COMUN { get; set; }
        public virtual ICollection<PFC_IX_CORRECTIVO> PFC_IX_CORRECTIVO { get; set; }
    }
}
