//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFC_II_MEDICO
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_ESTUDIO { get; set; }
        public string P2_HEREDO_FAMILIARES { get; set; }
        public string P3_ANTPER_NOPATO { get; set; }
        public string P31_CONSUMO_TOXICO { get; set; }
        public string P32_TATUAJES_CICATRICES { get; set; }
        public string P4_PATOLOGICOS { get; set; }
        public string P5_PADECIMIENTOS { get; set; }
        public string P6_EXPLORACION_FISICA { get; set; }
        public string SIGNOS_TA { get; set; }
        public string SIGNOS_RESPIRACION { get; set; }
        public string SIGNOS_TEMPERATURA { get; set; }
        public string SIGNOS_PESO { get; set; }
        public string SIGNOS_PULSO { get; set; }
        public string SIGNOS_ESTATURA { get; set; }
        public string P7_IMPRESION_DIAGNOSTICA { get; set; }
        public Nullable<short> P8_DICTAMEN_MEDICO { get; set; }
        public Nullable<System.DateTime> ESTUDIO_FEC { get; set; }
        public string COORDINADOR { get; set; }
        public string ELABORO { get; set; }
    
        public virtual PERSONALIDAD_FUERO_COMUN PERSONALIDAD_FUERO_COMUN { get; set; }
    }
}
