//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFC_IX_CORRECTIVO
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_ESTUDIO { get; set; }
        public short ID_CORRECTIVO { get; set; }
        public string MOTIVO { get; set; }
        public Nullable<System.DateTime> CORRECTIVO_FEC { get; set; }
        public string SANCION { get; set; }
    
        public virtual PFC_IX_SEGURIDAD PFC_IX_SEGURIDAD { get; set; }
    }
}
