//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFC_IV_PROGRAMA
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_ESTUDIO { get; set; }
        public short ID_ACTIVIDAD { get; set; }
        public short ID_TIPO_PROGRAMA { get; set; }
        public short ID_CONSEC { get; set; }
        public string DURACION { get; set; }
        public string CONCLUYO { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
        public virtual PFC_IV_PSICOLOGICO PFC_IV_PSICOLOGICO { get; set; }
        public virtual TIPO_PROGRAMA TIPO_PROGRAMA { get; set; }
    }
}
