//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFF_ACTA_CONSEJO_TECNICO
    {
        public PFF_ACTA_CONSEJO_TECNICO()
        {
            this.PFF_ACTA_DETERMINO = new HashSet<PFF_ACTA_DETERMINO>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_ESTUDIO { get; set; }
        public string EXPEDIENTE { get; set; }
        public Nullable<System.DateTime> SESION_FEC { get; set; }
        public Nullable<short> CEN_ID_CENTRO { get; set; }
        public string SUSCRITO_DIRECTOR_CRS { get; set; }
        public string PRESENTE_ACTUACION { get; set; }
        public string APROBADO_APLAZADO { get; set; }
        public string APROBADO_POR { get; set; }
        public string TRAMITE { get; set; }
        public string LUGAR { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string DIRECTOR { get; set; }
    
        public virtual CENTRO CENTRO { get; set; }
        public virtual ICollection<PFF_ACTA_DETERMINO> PFF_ACTA_DETERMINO { get; set; }
        public virtual PERSONALIDAD_FUERO_FEDERAL PERSONALIDAD_FUERO_FEDERAL { get; set; }
    }
}
