//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFF_ESTUDIO_MEDICO
    {
        public PFF_ESTUDIO_MEDICO()
        {
            this.PFF_SUSTANCIA_TOXICA = new HashSet<PFF_SUSTANCIA_TOXICA>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_ESTUDIO { get; set; }
        public string NOMBRE { get; set; }
        public string ALIAS { get; set; }
        public Nullable<short> EDAD { get; set; }
        public string EDO_CIVIL { get; set; }
        public string ORIGINARIO_DE { get; set; }
        public Nullable<short> OCUPACION_ANT { get; set; }
        public Nullable<short> OCUPACION_ACT { get; set; }
        public string DELITO { get; set; }
        public string SENTENCIA { get; set; }
        public string ANTE_HEREDO_FAM { get; set; }
        public string ANTE_PERSONAL_NO_PATOLOGICOS { get; set; }
        public string ANTE_PATOLOGICOS { get; set; }
        public string ASIST_FARMACODEPENDENCIA { get; set; }
        public string ASIST_AA { get; set; }
        public string ASIST_OTROS { get; set; }
        public string ASIST_OTROS_ESPECIF { get; set; }
        public string PADECIMIENTO_ACTUAL { get; set; }
        public string INTERROGATORIO_APARATOS { get; set; }
        public string EXP_FIS_CABEZA_CUELLO { get; set; }
        public string EXP_FIS_TORAX { get; set; }
        public string EXP_FIS_ABDOMEN { get; set; }
        public string EXP_FIS_GENITALES { get; set; }
        public string EXP_FIS_EXTREMIDADES { get; set; }
        public string TA { get; set; }
        public string TEMPERATURA { get; set; }
        public string PULSO { get; set; }
        public string RESPIRACION { get; set; }
        public string ESTATURA { get; set; }
        public string DIAGNOSTICO { get; set; }
        public string RESULTADOS_OBTENIDOS { get; set; }
        public string CONCLUSION { get; set; }
        public string LUGAR { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string DIRECTOR_CENTRO { get; set; }
        public string MEDICO { get; set; }
        public string TATUAJES { get; set; }
    
        public virtual OCUPACION OCUPACION { get; set; }
        public virtual OCUPACION OCUPACION1 { get; set; }
        public virtual PERSONALIDAD_FUERO_FEDERAL PERSONALIDAD_FUERO_FEDERAL { get; set; }
        public virtual ICollection<PFF_SUSTANCIA_TOXICA> PFF_SUSTANCIA_TOXICA { get; set; }
    }
}
