//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROC_ATENCION_MEDICA
    {
        public PROC_ATENCION_MEDICA()
        {
            this.PROC_ATENCION_MEDICA_PROG = new HashSet<PROC_ATENCION_MEDICA_PROG>();
        }
    
        public int ID_ATENCION_MEDICA { get; set; }
        public short ID_PROCMED { get; set; }
        public string ID_USUARIO { get; set; }
        public string OBSERV { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
        public short ID_CENTRO_UBI { get; set; }
    
        public virtual PROC_MED PROC_MED { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<PROC_ATENCION_MEDICA_PROG> PROC_ATENCION_MEDICA_PROG { get; set; }
        public virtual ATENCION_MEDICA ATENCION_MEDICA { get; set; }
    }
}
