//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROC_MED
    {
        public PROC_MED()
        {
            this.PROC_MATERIAL = new HashSet<PROC_MATERIAL>();
            this.PROC_ATENCION_MEDICA = new HashSet<PROC_ATENCION_MEDICA>();
            this.TV_PROC_ATENCION_MEDICA_PROG = new HashSet<TV_PROC_ATENCION_MEDICA_PROG>();
        }
    
        public short ID_PROCMED { get; set; }
        public Nullable<short> ID_PROCMED_SUBTIPO { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<PROC_MATERIAL> PROC_MATERIAL { get; set; }
        public virtual PROC_MED_SUBTIPO PROC_MED_SUBTIPO { get; set; }
        public virtual ICollection<PROC_ATENCION_MEDICA> PROC_ATENCION_MEDICA { get; set; }
        public virtual ICollection<TV_PROC_ATENCION_MEDICA_PROG> TV_PROC_ATENCION_MEDICA_PROG { get; set; }
    }
}
