//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROC_ATENCION_MEDICA_PROG
    {
        public PROC_ATENCION_MEDICA_PROG()
        {
            this.PROC_ATENCION_MEDICA_PROG_INCI = new HashSet<PROC_ATENCION_MEDICA_PROG_INCI>();
            this.PROC_MEDICO_PROG_DET = new HashSet<PROC_MEDICO_PROG_DET>();
        }
    
        public int ID_AM_PROG { get; set; }
        public Nullable<int> ID_CITA { get; set; }
        public string ID_USUARIO_ASIGNADO { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<System.DateTime> REALIZACION_FEC { get; set; }
        public int ID_ATENCION_MEDICA { get; set; }
        public short ID_PROCMED { get; set; }
        public short ID_CENTRO_UBI { get; set; }
        public Nullable<short> ID_CENTRO_CITA { get; set; }
    
        public virtual ATENCION_CITA ATENCION_CITA { get; set; }
        public virtual PROC_ATENCION_MEDICA PROC_ATENCION_MEDICA { get; set; }
        public virtual ICollection<PROC_ATENCION_MEDICA_PROG_INCI> PROC_ATENCION_MEDICA_PROG_INCI { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<PROC_MEDICO_PROG_DET> PROC_MEDICO_PROG_DET { get; set; }
    }
}
