//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_PRESENTACION_MED
    {
        public int ID_PRODUCTO { get; set; }
        public short ID_PRESENTACION_MEDICAMENTO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public string ID_USUARIO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual PRESENTACION_MEDICAMENTO PRESENTACION_MEDICAMENTO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
