//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.ALMACEN_INVENTARIO = new HashSet<ALMACEN_INVENTARIO>();
            this.CALENDARIZAR_ENTREGA_PRODUCTO = new HashSet<CALENDARIZAR_ENTREGA_PRODUCTO>();
            this.HOJA_ENFERMERIA_SOLUCION = new HashSet<HOJA_ENFERMERIA_SOLUCION>();
            this.INCIDENCIA_PRODUCTO = new HashSet<INCIDENCIA_PRODUCTO>();
            this.MOVIMIENTO_PRODUCTO = new HashSet<MOVIMIENTO_PRODUCTO>();
            this.ORDEN_COMPRA_DETALLE = new HashSet<ORDEN_COMPRA_DETALLE>();
            this.PROC_MATERIAL = new HashSet<PROC_MATERIAL>();
            this.PROC_MEDICO_PROG_DET = new HashSet<PROC_MEDICO_PROG_DET>();
            this.PRODUCTO_PRESENTACION_MED = new HashSet<PRODUCTO_PRESENTACION_MED>();
            this.PRODUCTO_PRESENTACION = new HashSet<PRODUCTO_PRESENTACION>();
            this.RECETA_MEDICA_DETALLE = new HashSet<RECETA_MEDICA_DETALLE>();
            this.REQUISICION_PRODUCTO = new HashSet<REQUISICION_PRODUCTO>();
            this.REQUISICION_CENTRO_PRODUCTO = new HashSet<REQUISICION_CENTRO_PRODUCTO>();
            this.TRASPASO_PRODUCTO = new HashSet<TRASPASO_PRODUCTO>();
        }
    
        public int ID_PRODUCTO { get; set; }
        public Nullable<int> ID_UNIDAD_MEDIDA { get; set; }
        public Nullable<int> ID_CATEGORIA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PRECIO_COMPRA { get; set; }
        public Nullable<decimal> PRECIO_VENTA { get; set; }
        public string CODIGO_BARRAS { get; set; }
        public string PERIODO_COMPRA { get; set; }
        public Nullable<int> CANTIDAD_MINIMA { get; set; }
        public Nullable<int> CANTIDAD_MAXIMA { get; set; }
        public string GENERACION_CODIGO { get; set; }
        public string ACTIVO { get; set; }
        public Nullable<short> PROD_PORCENTAJE { get; set; }
        public Nullable<decimal> PROD_VENTA_REAL { get; set; }
        public Nullable<decimal> UTILIDAD { get; set; }
        public string ES_UT { get; set; }
        public string PRESENTACION { get; set; }
        public string ES_IVA { get; set; }
        public string ES_RED { get; set; }
        public string ES_AO { get; set; }
        public string ES_DT { get; set; }
        public Nullable<int> ID_SUBCATEGORIA { get; set; }
        public Nullable<short> ID_FORMA_FARM { get; set; }
    
        public virtual ICollection<ALMACEN_INVENTARIO> ALMACEN_INVENTARIO { get; set; }
        public virtual ICollection<CALENDARIZAR_ENTREGA_PRODUCTO> CALENDARIZAR_ENTREGA_PRODUCTO { get; set; }
        public virtual FORMA_FARMACEUTICA FORMA_FARMACEUTICA { get; set; }
        public virtual ICollection<HOJA_ENFERMERIA_SOLUCION> HOJA_ENFERMERIA_SOLUCION { get; set; }
        public virtual ICollection<INCIDENCIA_PRODUCTO> INCIDENCIA_PRODUCTO { get; set; }
        public virtual ICollection<MOVIMIENTO_PRODUCTO> MOVIMIENTO_PRODUCTO { get; set; }
        public virtual ICollection<ORDEN_COMPRA_DETALLE> ORDEN_COMPRA_DETALLE { get; set; }
        public virtual ICollection<PROC_MATERIAL> PROC_MATERIAL { get; set; }
        public virtual ICollection<PROC_MEDICO_PROG_DET> PROC_MEDICO_PROG_DET { get; set; }
        public virtual ICollection<PRODUCTO_PRESENTACION_MED> PRODUCTO_PRESENTACION_MED { get; set; }
        public virtual PRODUCTO_CATEGORIA PRODUCTO_CATEGORIA { get; set; }
        public virtual PRODUCTO_IMAGEN PRODUCTO_IMAGEN { get; set; }
        public virtual ICollection<PRODUCTO_PRESENTACION> PRODUCTO_PRESENTACION { get; set; }
        public virtual PRODUCTO_UNIDAD_MEDIDA PRODUCTO_UNIDAD_MEDIDA { get; set; }
        public virtual PRODUCTO_SUBCATEGORIA PRODUCTO_SUBCATEGORIA { get; set; }
        public virtual ICollection<RECETA_MEDICA_DETALLE> RECETA_MEDICA_DETALLE { get; set; }
        public virtual ICollection<REQUISICION_PRODUCTO> REQUISICION_PRODUCTO { get; set; }
        public virtual ICollection<REQUISICION_CENTRO_PRODUCTO> REQUISICION_CENTRO_PRODUCTO { get; set; }
        public virtual ICollection<TRASPASO_PRODUCTO> TRASPASO_PRODUCTO { get; set; }
    }
}
