//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_UNIDAD_MEDIDA
    {
        public PRODUCTO_UNIDAD_MEDIDA()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public int ID_UNIDAD_MEDIDA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCR { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
