//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMA_HISTORICO
    {
        public int ID_TRASLADO { get; set; }
        public short ID_CENTRO { get; set; }
        public string EJE { get; set; }
        public string REGISTRO { get; set; }
        public string PROGRAMA { get; set; }
        public string ACTIVIDAD { get; set; }
        public string ELIGE { get; set; }
        public string ESTATUS { get; set; }
        public string APROBADO { get; set; }
        public string NOTA { get; set; }
        public string ASISTENCIA { get; set; }
    
        public virtual TRASLADO TRASLADO { get; set; }
    }
}
