//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRONOSTICO
    {
        public PRONOSTICO()
        {
            this.NOTA_MEDICA = new HashSet<NOTA_MEDICA>();
        }
    
        public short ID_PRONOSTICO { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<NOTA_MEDICA> NOTA_MEDICA { get; set; }
    }
}
