//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRS_FICHA_IDEN
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_FOLIO { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
        public string DIAS_TRABAJO { get; set; }
        public string II_ACTITUD_GENERAL { get; set; }
        public string III_DELITO { get; set; }
        public string III_MEDIDA_CAUTELAR { get; set; }
        public string IV_OBSERVACIONES { get; set; }
        public string PROMOTOR_LABORAL { get; set; }
    
        public virtual IMPUTADO IMPUTADO { get; set; }
    }
}
