//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRS_VISITA_DOMICILIARIA
    {
        public PRS_VISITA_DOMICILIARIA()
        {
            this.PRS_VISITA_FOTOGRAFIA = new HashSet<PRS_VISITA_FOTOGRAFIA>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_FOLIO { get; set; }
        public string MEDIDA_CAUTELAR { get; set; }
        public string IIMOTIVO_VISITA { get; set; }
        public string III12_NOMBRE_ENTREVISTADO { get; set; }
        public string III13_EDAD { get; set; }
        public Nullable<short> III14_PARENTESCO { get; set; }
        public string III15_TIEMPO_CONOCERSE { get; set; }
        public string III17_TELEFONO { get; set; }
        public Nullable<short> III19_MUNICIPIO { get; set; }
        public Nullable<short> III18_ENTIDAD_FEDERATIVA { get; set; }
        public string III20_RELACION_SENTENCIADO { get; set; }
        public string IV_OBSERVACIONES { get; set; }
        public string ANEXO1_NOMBRE { get; set; }
        public string ANEXO1_TELEFONO { get; set; }
        public string ANEXO1_DIRECCION { get; set; }
        public string LUGAR { get; set; }
        public Nullable<System.DateTime> FECHA_VISITA { get; set; }
        public string HORA_VISITA { get; set; }
        public string III16_CALLE { get; set; }
        public string III16_NUM_INTERIOR { get; set; }
        public string III16_NUM_EXTERIOR { get; set; }
        public Nullable<short> ID_PROCESO_LIBERTAD { get; set; }
    
        public virtual ENTIDAD ENTIDAD { get; set; }
        public virtual MUNICIPIO MUNICIPIO { get; set; }
        public virtual ICollection<PRS_VISITA_FOTOGRAFIA> PRS_VISITA_FOTOGRAFIA { get; set; }
        public virtual TIPO_REFERENCIA TIPO_REFERENCIA { get; set; }
        public virtual IMPUTADO IMPUTADO { get; set; }
        public virtual PROCESO_LIBERTAD PROCESO_LIBERTAD { get; set; }
    }
}
