//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRS_DROGA
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_FOLIO { get; set; }
        public short ID_DROGA { get; set; }
        public Nullable<short> ID_FRECUENCIA { get; set; }
        public Nullable<System.DateTime> INICIO_CONSUMO { get; set; }
    
        public virtual DROGA DROGA { get; set; }
        public virtual DROGA_FRECUENCIA DROGA_FRECUENCIA { get; set; }
        public virtual PRS_ENTREVISTA_INICIAL PRS_ENTREVISTA_INICIAL { get; set; }
    }
}
