//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECURSO
    {
        public RECURSO()
        {
            this.RECURSO_DELITO = new HashSet<RECURSO_DELITO>();
            this.RECURSO_DOCTO = new HashSet<RECURSO_DOCTO>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_CAUSA_PENAL { get; set; }
        public short ID_RECURSO { get; set; }
        public Nullable<short> ID_TIPO_RECURSO { get; set; }
        public Nullable<short> ID_TRIBUNAL { get; set; }
        public string FUERO { get; set; }
        public string RESULTADO { get; set; }
        public Nullable<System.DateTime> FEC_RECURSO { get; set; }
        public string TOCA_PENAL { get; set; }
        public string NO_OFICIO { get; set; }
        public string RESOLUCION { get; set; }
        public Nullable<System.DateTime> FEC_RESOLUCION { get; set; }
        public string MULTA { get; set; }
        public string REPARACION_DANIO { get; set; }
        public string SUSTITUCION_PENA { get; set; }
        public string MULTA_CONDICIONAL { get; set; }
        public Nullable<short> SENTENCIA_ANIOS { get; set; }
        public Nullable<short> SENTENCIA_MESES { get; set; }
        public Nullable<short> SENTENCIA_DIAS { get; set; }
        public Nullable<short> ID_SENTENCIA { get; set; }
    
        public virtual CAUSA_PENAL CAUSA_PENAL { get; set; }
        public virtual JUZGADO JUZGADO { get; set; }
        public virtual ICollection<RECURSO_DELITO> RECURSO_DELITO { get; set; }
        public virtual ICollection<RECURSO_DOCTO> RECURSO_DOCTO { get; set; }
        public virtual RECURSO_RESULTADO RECURSO_RESULTADO { get; set; }
        public virtual TIPO_RECURSO TIPO_RECURSO { get; set; }
    }
}
