//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQ_CENTRO_ESTATUS
    {
        public REQ_CENTRO_ESTATUS()
        {
            this.REQUISICION_CENTRO = new HashSet<REQUISICION_CENTRO>();
        }
    
        public string ID_ESTATUS { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<REQUISICION_CENTRO> REQUISICION_CENTRO { get; set; }
    }
}
