//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISICION
    {
        public REQUISICION()
        {
            this.REQUISICION_PRODUCTO = new HashSet<REQUISICION_PRODUCTO>();
            this.ORDEN_COMPRA = new HashSet<ORDEN_COMPRA>();
            this.REQUISICION_CENTRO = new HashSet<REQUISICION_CENTRO>();
        }
    
        public int ID_REQUISICION { get; set; }
        public Nullable<short> ID_PRODUCTO_TIPO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<short> ANIO { get; set; }
        public Nullable<short> MES { get; set; }
        public string OBSERV { get; set; }
        public string ESTATUS { get; set; }
        public string ID_USUARIO { get; set; }
        public string PERIODO { get; set; }
    
        public virtual ICollection<REQUISICION_PRODUCTO> REQUISICION_PRODUCTO { get; set; }
        public virtual ALMACEN_TIPO_CAT ALMACEN_TIPO_CAT { get; set; }
        public virtual ICollection<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public virtual REQUISICION_ESTATUS REQUISICION_ESTATUS { get; set; }
        public virtual ICollection<REQUISICION_CENTRO> REQUISICION_CENTRO { get; set; }
    }
}
