//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANCION
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_INCIDENTE { get; set; }
        public short ID_SANCION { get; set; }
        public Nullable<System.DateTime> INICIA_FEC { get; set; }
        public Nullable<System.DateTime> TERMINA_FEC { get; set; }
    
        public virtual SANCION_TIPO SANCION_TIPO { get; set; }
        public virtual INCIDENTE INCIDENTE { get; set; }
    }
}
