//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTOR_CLASIFICACION
    {
        public SECTOR_CLASIFICACION()
        {
            this.SECTOR_OBSERVACION = new HashSet<SECTOR_OBSERVACION>();
            this.GRUPO_VULNERABLE = new HashSet<GRUPO_VULNERABLE>();
            this.ENFERMEDAD = new HashSet<ENFERMEDAD>();
            this.PATOLOGICO_CAT = new HashSet<PATOLOGICO_CAT>();
        }
    
        public short ID_SECTOR_CLAS { get; set; }
        public string POBLACION { get; set; }
        public string OBSERV { get; set; }
        public string COLOR { get; set; }
        public string COLOR_TEXTO { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<short> ES_GRUPO_VULNERABLE { get; set; }
    
        public virtual ICollection<SECTOR_OBSERVACION> SECTOR_OBSERVACION { get; set; }
        public virtual ICollection<GRUPO_VULNERABLE> GRUPO_VULNERABLE { get; set; }
        public virtual ICollection<ENFERMEDAD> ENFERMEDAD { get; set; }
        public virtual ICollection<PATOLOGICO_CAT> PATOLOGICO_CAT { get; set; }
    }
}
