//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SENAS_PARTICULARES
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_SENA { get; set; }
        public Nullable<short> ID_REGION { get; set; }
        public string INTRAMUROS { get; set; }
        public Nullable<short> TIPO { get; set; }
        public Nullable<short> CANTIDAD { get; set; }
        public string CODIGO { get; set; }
        public string CLASIFICACION { get; set; }
        public Nullable<short> ID_TIPO_TATUAJE { get; set; }
        public string SIGNIFICADO { get; set; }
        public byte[] IMAGEN { get; set; }
    
        public virtual ANATOMIA_TOPOGRAFICA ANATOMIA_TOPOGRAFICA { get; set; }
        public virtual TATUAJE_CLASIFICACION TATUAJE_CLASIFICACION { get; set; }
        public virtual TATUAJE TATUAJE { get; set; }
        public virtual IMPUTADO IMPUTADO { get; set; }
    }
}
