//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO_AUXILIAR_RESULTADO
    {
        public decimal ID_SA_RESULTADO { get; set; }
        public Nullable<short> ID_CENTRO { get; set; }
        public Nullable<short> ID_ANIO { get; set; }
        public Nullable<int> ID_IMPUTADO { get; set; }
        public string ID_USUARIO { get; set; }
        public byte[] CAMPO_BLOB { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
        public Nullable<short> ID_FORMATO { get; set; }
        public Nullable<int> ID_SERV_AUX { get; set; }
        public string NOMBRE_ARCHIVO { get; set; }
        public Nullable<short> ID_INGRESO { get; set; }
    
        public virtual FORMATO_DOCUMENTO FORMATO_DOCUMENTO { get; set; }
        public virtual SERVICIO_AUX_DIAG_TRAT SERVICIO_AUX_DIAG_TRAT { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual INGRESO INGRESO { get; set; }
    }
}
