//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTEMA_ROL
    {
        public SISTEMA_ROL()
        {
            this.PROCESO_ROL = new HashSet<PROCESO_ROL>();
            this.MENSAJE_ROL = new HashSet<MENSAJE_ROL>();
            this.DEPARTAMENTO = new HashSet<DEPARTAMENTO>();
            this.PROCESO_USUARIO = new HashSet<PROCESO_USUARIO>();
            this.USUARIO_ROL = new HashSet<USUARIO_ROL>();
        }
    
        public short ID_ROL { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<PROCESO_ROL> PROCESO_ROL { get; set; }
        public virtual ICollection<MENSAJE_ROL> MENSAJE_ROL { get; set; }
        public virtual ICollection<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual ICollection<PROCESO_USUARIO> PROCESO_USUARIO { get; set; }
        public virtual ICollection<USUARIO_ROL> USUARIO_ROL { get; set; }
    }
}
