//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIOE_GPOFAMSEC
    {
        public SOCIOE_GPOFAMSEC()
        {
            this.SOCIOE_GPOFAMSEC_CARAC = new HashSet<SOCIOE_GPOFAMSEC_CARAC>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public string GRUPO_FAMILIAR { get; set; }
        public string RELACION_INTRAFAMILIAR { get; set; }
        public Nullable<short> PERSONAS_LABORAN { get; set; }
        public Nullable<int> INGRESO_MENSUAL { get; set; }
        public Nullable<int> EGRESO_MENSUAL { get; set; }
        public Nullable<decimal> FAM_ANTECEDENTE { get; set; }
        public string ANTECEDENTE { get; set; }
        public string VIVIENDA_ZONA { get; set; }
        public string VIVIENDA_CONDICIONES { get; set; }
        public string NIVEL_SOCIO_CULTURAL { get; set; }
        public Nullable<decimal> RECIBE_VISITA { get; set; }
        public string VISITA { get; set; }
        public string FRECUENCIA { get; set; }
        public Nullable<decimal> APOYO_ECONOMICO { get; set; }
        public string MOTIVO_NO_VISITA { get; set; }
    
        public virtual ICollection<SOCIOE_GPOFAMSEC_CARAC> SOCIOE_GPOFAMSEC_CARAC { get; set; }
        public virtual SOCIOECONOMICO SOCIOECONOMICO { get; set; }
    }
}
