//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIOE_GPOFAMPRI_CARAC
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public string ID_TIPO { get; set; }
        public short ID_CLAVE { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
    
        public virtual SOCIOE_GPOFAMPRI SOCIOE_GPOFAMPRI { get; set; }
        public virtual SOCIOECONOMICO_CAT SOCIOECONOMICO_CAT { get; set; }
    }
}
