//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIOECONOMICO_CAT
    {
        public SOCIOECONOMICO_CAT()
        {
            this.SOCIOE_GPOFAMPRI_CARAC = new HashSet<SOCIOE_GPOFAMPRI_CARAC>();
            this.SOCIOE_GPOFAMSEC_CARAC = new HashSet<SOCIOE_GPOFAMSEC_CARAC>();
        }
    
        public string ID_TIPO { get; set; }
        public short ID_CLAVE { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<SOCIOE_GPOFAMPRI_CARAC> SOCIOE_GPOFAMPRI_CARAC { get; set; }
        public virtual ICollection<SOCIOE_GPOFAMSEC_CARAC> SOCIOE_GPOFAMSEC_CARAC { get; set; }
    }
}
