//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOL_INTERCONSULTA_INTERNA
    {
        public SOL_INTERCONSULTA_INTERNA()
        {
            this.ESPECIALISTA_CITA = new HashSet<ESPECIALISTA_CITA>();
        }
    
        public int ID_SOLICITUD { get; set; }
        public Nullable<short> ID_CENTRO { get; set; }
        public string ID_USUARIO { get; set; }
        public string MOTIVO_INTERCONSULTA { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
        public Nullable<int> ID_INTERSOL { get; set; }
        public short ID_CENTRO_UBI { get; set; }
    
        public virtual CENTRO CENTRO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<ESPECIALISTA_CITA> ESPECIALISTA_CITA { get; set; }
        public virtual INTERCONSULTA_SOLICITUD INTERCONSULTA_SOLICITUD { get; set; }
    }
}
