//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DOCUMENTO
    {
        public TIPO_DOCUMENTO()
        {
            this.VISITA_DOCUMENTO = new HashSet<VISITA_DOCUMENTO>();
            this.ABOGADO_DOCUMENTO = new HashSet<ABOGADO_DOCUMENTO>();
            this.ABOGADO_ING_DOCTO = new HashSet<ABOGADO_ING_DOCTO>();
            this.ABOGADO_CP_DOCTO = new HashSet<ABOGADO_CP_DOCTO>();
        }
    
        public short ID_TIPO_VISITA { get; set; }
        public short ID_TIPO_DOCUMENTO { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<VISITA_DOCUMENTO> VISITA_DOCUMENTO { get; set; }
        public virtual ICollection<ABOGADO_DOCUMENTO> ABOGADO_DOCUMENTO { get; set; }
        public virtual TIPO_VISITA TIPO_VISITA { get; set; }
        public virtual ICollection<ABOGADO_ING_DOCTO> ABOGADO_ING_DOCTO { get; set; }
        public virtual ICollection<ABOGADO_CP_DOCTO> ABOGADO_CP_DOCTO { get; set; }
    }
}
