//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DEFECTO
    {
        public short ID_DEFECTO { get; set; }
        public string DESCR { get; set; }
        public Nullable<short> PM { get; set; }
        public string ESTATUS { get; set; }
    }
}
