//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRASLADO_INCIDENCIA_TIPO
    {
        public TRASLADO_INCIDENCIA_TIPO()
        {
            this.EXCARCELACION = new HashSet<EXCARCELACION>();
            this.EXCARCELACION1 = new HashSet<EXCARCELACION>();
            this.TRASLADO_DETALLE = new HashSet<TRASLADO_DETALLE>();
        }
    
        public short ID_INCIDENCIA_TRASLADO { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<EXCARCELACION> EXCARCELACION { get; set; }
        public virtual ICollection<EXCARCELACION> EXCARCELACION1 { get; set; }
        public virtual ICollection<TRASLADO_DETALLE> TRASLADO_DETALLE { get; set; }
    }
}
