//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRASLADO_DETALLE
    {
        public int ID_TRASLADO { get; set; }
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public string ID_ESTATUS { get; set; }
        public Nullable<short> ID_ESTATUS_ADMINISTRATIVO { get; set; }
        public Nullable<System.DateTime> EGRESO_FEC { get; set; }
        public short ID_CENTRO_TRASLADO { get; set; }
        public Nullable<short> ID_MOTIVO { get; set; }
        public Nullable<short> AMP_ID_CENTRO { get; set; }
        public Nullable<short> AMP_ID_ANIO { get; set; }
        public Nullable<int> AMP_ID_IMPUTADO { get; set; }
        public Nullable<short> AMP_ID_INGRESO { get; set; }
        public Nullable<short> AMP_ID_AMPARO_INDIRECTO { get; set; }
        public string CANCELADO_OBSERVA { get; set; }
        public Nullable<int> ID_ATENCION_MEDICA { get; set; }
        public Nullable<short> ID_INCIDENCIA_TRASLADO { get; set; }
        public string INCIDENCIA_OBSERVACION { get; set; }
        public Nullable<short> ID_CENTRO_UBI { get; set; }
    
        public virtual AMPARO_INDIRECTO AMPARO_INDIRECTO { get; set; }
        public virtual ATENCION_MEDICA ATENCION_MEDICA { get; set; }
        public virtual ESTATUS_ADMINISTRATIVO ESTATUS_ADMINISTRATIVO { get; set; }
        public virtual INGRESO INGRESO { get; set; }
        public virtual TRASLADO TRASLADO { get; set; }
        public virtual TRASLADO_CANCELA_MOTIVO TRASLADO_CANCELA_MOTIVO { get; set; }
        public virtual TRASLADO_INCIDENCIA_TIPO TRASLADO_INCIDENCIA_TIPO { get; set; }
        public virtual TRASLADO_DETALLE_ESTATUS TRASLADO_DETALLE_ESTATUS { get; set; }
    }
}
