//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRASLADO_ISLAS
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public short ID_ESTUDIO { get; set; }
        public string CRIMINOGENESIS { get; set; }
        public Nullable<short> EGOCENTRISMO { get; set; }
        public Nullable<short> LABILIDAD_AFECTIVA { get; set; }
        public string EN_CASO_ADICCION { get; set; }
        public string INTIMIDACION_PENA { get; set; }
        public Nullable<short> AGRESIVIDAD_INTRAMUROS { get; set; }
        public Nullable<short> ID_PELIGROSIDAD { get; set; }
        public string DICTAMEN_TRASLADO { get; set; }
        public string CONTINUE_TRATAMIENTO { get; set; }
        public string ANUENCIA_FIRMADA { get; set; }
        public string TRATAMIENTO_SUGERIDO { get; set; }
        public Nullable<System.DateTime> ESTUDIO_FEC { get; set; }
        public string DIRECTOR { get; set; }
        public string RESPONSABLE { get; set; }
    
        public virtual PFC_V_CAPACIDAD PFC_V_CAPACIDAD { get; set; }
        public virtual PFC_V_CAPACIDAD PFC_V_CAPACIDAD1 { get; set; }
        public virtual PFC_V_CAPACIDAD PFC_V_CAPACIDAD2 { get; set; }
        public virtual PFC_V_PELIGROSIDAD PFC_V_PELIGROSIDAD { get; set; }
        public virtual PERSONALIDAD PERSONALIDAD { get; set; }
    }
}
