//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRASLADO
    {
        public TRASLADO()
        {
            this.TRASLADO_DETALLE = new HashSet<TRASLADO_DETALLE>();
        }
    
        public int ID_TRASLADO { get; set; }
        public short ID_CENTRO { get; set; }
        public string ORIGEN_TIPO { get; set; }
        public Nullable<short> CENTRO_ORIGEN { get; set; }
        public string CENTRO_ORIGEN_FORANEO { get; set; }
        public System.DateTime TRASLADO_FEC { get; set; }
        public Nullable<short> ID_MOTIVO { get; set; }
        public string JUSTIFICACION { get; set; }
        public Nullable<short> CENTRO_DESTINO { get; set; }
        public string OFICIO_AUTORIZACION { get; set; }
        public string OFICIO_SALIDA { get; set; }
        public Nullable<short> ID_MOTIVO_SALIDA { get; set; }
        public string ID_ESTATUS { get; set; }
        public string AUTORIZA_TRASLADO { get; set; }
        public string AUTORIZA_SALIDA { get; set; }
        public Nullable<int> ID_CENTRO_ORIGEN_FORANEO { get; set; }
        public string RESPONSABLE { get; set; }
        public Nullable<int> ID_CENTRO_DESTINO_FORANEO { get; set; }
        public string OTRO_CENTRO_DESTINO_FORANEO { get; set; }
    
        public virtual CENTRO CENTRO { get; set; }
        public virtual CENTRO CENTRO1 { get; set; }
        public virtual CENTRO CENTRO2 { get; set; }
        public virtual EMISOR EMISOR { get; set; }
        public virtual EMISOR EMISOR1 { get; set; }
        public virtual PROGRAMA_HISTORICO PROGRAMA_HISTORICO { get; set; }
        public virtual TRASLADO_MOTIVO TRASLADO_MOTIVO { get; set; }
        public virtual TRASLADO_MOTIVO_SALIDA TRASLADO_MOTIVO_SALIDA { get; set; }
        public virtual TRASLADO_ESTATUS TRASLADO_ESTATUS { get; set; }
        public virtual ICollection<TRASLADO_DETALLE> TRASLADO_DETALLE { get; set; }
    }
}
