//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TV_HOJA_REFERENCIA_MEDICA
    {
        public int ID_TV_HOJA { get; set; }
        public Nullable<int> ID_TV_INTERSOL { get; set; }
        public Nullable<short> ID_HOSPITAL { get; set; }
        public Nullable<short> ID_TIPO_CITA { get; set; }
        public string EXP_HGT { get; set; }
        public string MOTIVO { get; set; }
        public string OBSERV { get; set; }
        public string HOSPITAL_OTRO { get; set; }
        public Nullable<System.DateTime> FECHA_CITA { get; set; }
        public short ID_CENTRO_UBI { get; set; }
    
        public virtual CITA_TIPO CITA_TIPO { get; set; }
        public virtual HOSPITAL HOSPITAL { get; set; }
        public virtual TV_INTERCONSULTA_SOLICITUD TV_INTERCONSULTA_SOLICITUD { get; set; }
    }
}
