//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.ADUANA = new HashSet<ADUANA>();
            this.GRUPO_PARTICIPANTE_CANCELADO = new HashSet<GRUPO_PARTICIPANTE_CANCELADO>();
            this.USUARIO_MENSAJE = new HashSet<USUARIO_MENSAJE>();
            this.DEPARTAMENTO_ACCESO = new HashSet<DEPARTAMENTO_ACCESO>();
            this.PROCESO_USUARIO = new HashSet<PROCESO_USUARIO>();
            this.USUARIO_ROL = new HashSet<USUARIO_ROL>();
            this.HISTORIA_CLINICA_DENTAL = new HashSet<HISTORIA_CLINICA_DENTAL>();
            this.CAMA_HOSPITAL = new HashSet<CAMA_HOSPITAL>();
            this.SERVICIO_AUXILIAR_RESULTADO = new HashSet<SERVICIO_AUXILIAR_RESULTADO>();
            this.VISITANTE_INGRESO = new HashSet<VISITANTE_INGRESO>();
            this.ATENCION_CITA_INCIDENCIA = new HashSet<ATENCION_CITA_INCIDENCIA>();
            this.ATENCION_RECIBIDA = new HashSet<ATENCION_RECIBIDA>();
            this.CANALIZACION = new HashSet<CANALIZACION>();
            this.HOSPITALIZACION = new HashSet<HOSPITALIZACION>();
            this.PROC_ATENCION_MEDICA = new HashSet<PROC_ATENCION_MEDICA>();
            this.PROC_ATENCION_MEDICA_PROG_INCI = new HashSet<PROC_ATENCION_MEDICA_PROG_INCI>();
            this.RECETA_MEDICA = new HashSet<RECETA_MEDICA>();
            this.SOL_INTERCONSULTA_INTERNA = new HashSet<SOL_INTERCONSULTA_INTERNA>();
            this.NOTIFICACION_TS = new HashSet<NOTIFICACION_TS>();
            this.ATENCION_CITA = new HashSet<ATENCION_CITA>();
            this.PROC_ATENCION_MEDICA_PROG = new HashSet<PROC_ATENCION_MEDICA_PROG>();
            this.ESPECIALISTA = new HashSet<ESPECIALISTA>();
            this.ESPECIALISTA_CITA = new HashSet<ESPECIALISTA_CITA>();
            this.LIQUIDO_HOJA_CTRL = new HashSet<LIQUIDO_HOJA_CTRL>();
            this.PRODUCTO_PRESENTACION_MED = new HashSet<PRODUCTO_PRESENTACION_MED>();
            this.HOJA_CONTROL_ENFERMERIA = new HashSet<HOJA_CONTROL_ENFERMERIA>();
            this.HOJA_ENFERMERIA_LECTURA = new HashSet<HOJA_ENFERMERIA_LECTURA>();
            this.INGRESO = new HashSet<INGRESO>();
            this.HOJA_ENFERMERIA_ULCERA = new HashSet<HOJA_ENFERMERIA_ULCERA>();
            this.HOJA_ENFERMERIA_MEDICAMENTO = new HashSet<HOJA_ENFERMERIA_MEDICAMENTO>();
            this.HOJA_ENFERMERIA = new HashSet<HOJA_ENFERMERIA>();
            this.NOTA_DEFUNCION = new HashSet<NOTA_DEFUNCION>();
            this.EXCARCELACION = new HashSet<EXCARCELACION>();
            this.HOJA_ENFERMERIA_CATETER = new HashSet<HOJA_ENFERMERIA_CATETER>();
            this.HOJA_ENFERMERIA_SONDA_GASOGAS = new HashSet<HOJA_ENFERMERIA_SONDA_GASOGAS>();
            this.INCIDENCIAS_CATETER = new HashSet<INCIDENCIAS_CATETER>();
            this.INCIDENCIAS_SONDA_GAS = new HashSet<INCIDENCIAS_SONDA_GAS>();
            this.TV_CANALIZACION = new HashSet<TV_CANALIZACION>();
            this.TV_SOL_INTERCONSULTA_INTERNA = new HashSet<TV_SOL_INTERCONSULTA_INTERNA>();
            this.INTERCONSULTA_SOLICITUD = new HashSet<INTERCONSULTA_SOLICITUD>();
            this.TV_INTERCONSULTA_SOLICITUD = new HashSet<TV_INTERCONSULTA_SOLICITUD>();
        }
    
        public string ID_USUARIO { get; set; }
        public Nullable<int> ID_PERSONA { get; set; }
        public string PASSWORD { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<System.DateTime> VENCE_PASS { get; set; }
    
        public virtual ICollection<ADUANA> ADUANA { get; set; }
        public virtual ICollection<GRUPO_PARTICIPANTE_CANCELADO> GRUPO_PARTICIPANTE_CANCELADO { get; set; }
        public virtual ICollection<USUARIO_MENSAJE> USUARIO_MENSAJE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<DEPARTAMENTO_ACCESO> DEPARTAMENTO_ACCESO { get; set; }
        public virtual ICollection<PROCESO_USUARIO> PROCESO_USUARIO { get; set; }
        public virtual ICollection<USUARIO_ROL> USUARIO_ROL { get; set; }
        public virtual ICollection<HISTORIA_CLINICA_DENTAL> HISTORIA_CLINICA_DENTAL { get; set; }
        public virtual ICollection<CAMA_HOSPITAL> CAMA_HOSPITAL { get; set; }
        public virtual ICollection<SERVICIO_AUXILIAR_RESULTADO> SERVICIO_AUXILIAR_RESULTADO { get; set; }
        public virtual ICollection<VISITANTE_INGRESO> VISITANTE_INGRESO { get; set; }
        public virtual ICollection<ATENCION_CITA_INCIDENCIA> ATENCION_CITA_INCIDENCIA { get; set; }
        public virtual ICollection<ATENCION_RECIBIDA> ATENCION_RECIBIDA { get; set; }
        public virtual ICollection<CANALIZACION> CANALIZACION { get; set; }
        public virtual ICollection<HOSPITALIZACION> HOSPITALIZACION { get; set; }
        public virtual ICollection<PROC_ATENCION_MEDICA> PROC_ATENCION_MEDICA { get; set; }
        public virtual ICollection<PROC_ATENCION_MEDICA_PROG_INCI> PROC_ATENCION_MEDICA_PROG_INCI { get; set; }
        public virtual ICollection<RECETA_MEDICA> RECETA_MEDICA { get; set; }
        public virtual ICollection<SOL_INTERCONSULTA_INTERNA> SOL_INTERCONSULTA_INTERNA { get; set; }
        public virtual ICollection<NOTIFICACION_TS> NOTIFICACION_TS { get; set; }
        public virtual ICollection<ATENCION_CITA> ATENCION_CITA { get; set; }
        public virtual ICollection<PROC_ATENCION_MEDICA_PROG> PROC_ATENCION_MEDICA_PROG { get; set; }
        public virtual ICollection<ESPECIALISTA> ESPECIALISTA { get; set; }
        public virtual ICollection<ESPECIALISTA_CITA> ESPECIALISTA_CITA { get; set; }
        public virtual ICollection<LIQUIDO_HOJA_CTRL> LIQUIDO_HOJA_CTRL { get; set; }
        public virtual ICollection<PRODUCTO_PRESENTACION_MED> PRODUCTO_PRESENTACION_MED { get; set; }
        public virtual ICollection<HOJA_CONTROL_ENFERMERIA> HOJA_CONTROL_ENFERMERIA { get; set; }
        public virtual ICollection<HOJA_ENFERMERIA_LECTURA> HOJA_ENFERMERIA_LECTURA { get; set; }
        public virtual ICollection<INGRESO> INGRESO { get; set; }
        public virtual ICollection<HOJA_ENFERMERIA_ULCERA> HOJA_ENFERMERIA_ULCERA { get; set; }
        public virtual ICollection<HOJA_ENFERMERIA_MEDICAMENTO> HOJA_ENFERMERIA_MEDICAMENTO { get; set; }
        public virtual ICollection<HOJA_ENFERMERIA> HOJA_ENFERMERIA { get; set; }
        public virtual ICollection<NOTA_DEFUNCION> NOTA_DEFUNCION { get; set; }
        public virtual ICollection<EXCARCELACION> EXCARCELACION { get; set; }
        public virtual ICollection<HOJA_ENFERMERIA_CATETER> HOJA_ENFERMERIA_CATETER { get; set; }
        public virtual ICollection<HOJA_ENFERMERIA_SONDA_GASOGAS> HOJA_ENFERMERIA_SONDA_GASOGAS { get; set; }
        public virtual ICollection<INCIDENCIAS_CATETER> INCIDENCIAS_CATETER { get; set; }
        public virtual ICollection<INCIDENCIAS_SONDA_GAS> INCIDENCIAS_SONDA_GAS { get; set; }
        public virtual ICollection<TV_CANALIZACION> TV_CANALIZACION { get; set; }
        public virtual ICollection<TV_SOL_INTERCONSULTA_INTERNA> TV_SOL_INTERCONSULTA_INTERNA { get; set; }
        public virtual ICollection<INTERCONSULTA_SOLICITUD> INTERCONSULTA_SOLICITUD { get; set; }
        public virtual ICollection<TV_INTERCONSULTA_SOLICITUD> TV_INTERCONSULTA_SOLICITUD { get; set; }
    }
}
