//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA_DIA
    {
        public VISITA_DIA()
        {
            this.VISITA_AGENDA = new HashSet<VISITA_AGENDA>();
            this.VISITA_APELLIDO = new HashSet<VISITA_APELLIDO>();
            this.VISITA_EDIFICIO = new HashSet<VISITA_EDIFICIO>();
        }
    
        public short ID_DIA { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<VISITA_AGENDA> VISITA_AGENDA { get; set; }
        public virtual ICollection<VISITA_APELLIDO> VISITA_APELLIDO { get; set; }
        public virtual ICollection<VISITA_EDIFICIO> VISITA_EDIFICIO { get; set; }
    }
}
