//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA_DOCUMENTO
    {
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public short ID_INGRESO { get; set; }
        public int ID_PERSONA { get; set; }
        public short ID_TIPO_DOCUMENTO { get; set; }
        public short ID_TIPO_VISITA { get; set; }
        public Nullable<System.DateTime> CAPTURA_FEC { get; set; }
        public string OBSERV { get; set; }
        public byte[] DOCUMENTO { get; set; }
    
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO { get; set; }
        public virtual VISITANTE_INGRESO VISITANTE_INGRESO { get; set; }
    }
}
