//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITANTE_INGRESO_PASE
    {
        public VISITANTE_INGRESO_PASE()
        {
            this.ADUANA_INGRESO = new HashSet<ADUANA_INGRESO>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public short ID_INGRESO { get; set; }
        public int ID_IMPUTADO { get; set; }
        public int ID_PERSONA { get; set; }
        public short ID_CONSEC { get; set; }
        public Nullable<short> ID_PASE { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public string AUTORIZADO { get; set; }
    
        public virtual PASE_CATALOGO PASE_CATALOGO { get; set; }
        public virtual ICollection<ADUANA_INGRESO> ADUANA_INGRESO { get; set; }
        public virtual VISITANTE_INGRESO VISITANTE_INGRESO { get; set; }
    }
}
